import { Lesson } from '../types';

export const ENGLISH_LESSONS: Partial<Lesson>[] = [
  // Primary 1
  { title: 'Phonics: S, A, T, P', level: 'Primary 1', intro: '🎥 Animation: Letters making sounds!', content: 'Learn the sounds: /s/ like snake, /a/ like ant, /t/ like tap, /p/ like pan.', practice: { instruction: 'Say the sound of S', task: 'ssssssss' }, quiz: [{ question: 'Which letter makes the /p/ sound?', options: ['S', 'A', 'P'], correctOption: 2 }], rewardPoints: 10 },
  { title: 'Rhyming Words', level: 'Primary 1', intro: '🎥 Animation: Cat and Hat dancing!', content: 'Rhyming words sound the same at the end. Like Cat and Bat.', practice: { instruction: 'Find a rhyme for "Dog"', task: 'Log' }, quiz: [{ question: 'Which rhymes with "Cat"?', options: ['Dog', 'Bat', 'Sun'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Action Words', level: 'Primary 1', intro: '🎥 Animation: A boy jumping!', content: 'Action words tell us what we do. Jump, Run, Eat, Sleep.', practice: { instruction: 'What is the boy doing?', task: 'Jumping' }, quiz: [{ question: 'Which is an action word?', options: ['Jump', 'Table', 'Red'], correctOption: 0 }], rewardPoints: 10 },
  { title: 'Colors and Names', level: 'Primary 1', intro: '🎥 Animation: Painting a rainbow!', content: 'Learn colors: Red, Blue, Green, Yellow.', practice: { instruction: 'What color is the sky?', task: 'Blue' }, quiz: [{ question: 'Which color is grass?', options: ['Red', 'Green', 'Blue'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'My Family Members', level: 'Primary 1', intro: '🎥 Animation: Family tree!', content: 'Father, Mother, Brother, Sister.', practice: { instruction: 'Who is your mother?', task: 'Parent' }, quiz: [{ question: 'Who is your brother?', options: ['Father', 'Brother', 'Sister'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Greeting People', level: 'Primary 1', intro: '🎥 Animation: Waving hello!', content: 'Good morning, Good afternoon, Hello.', practice: { instruction: 'Say hello.', task: 'Hello' }, quiz: [{ question: 'What do you say in the morning?', options: ['Good night', 'Good morning', 'Good bye'], correctOption: 1 }], rewardPoints: 10 },
  // Primary 2
  { title: 'Vowels and Consonants', level: 'Primary 2', intro: '🎥 Animation: Five friends A, E, I, O, U jumping!', content: 'Vowels are A, E, I, O, U. All other letters are consonants.', practice: { instruction: 'Fill in the missing vowel: c_t', task: 'cat' }, quiz: [{ question: 'Choose the vowel in "pen"', options: ['p', 'e', 'n'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Opposites (Antonyms)', level: 'Primary 2', intro: '🎥 Animation: A big elephant and a small mouse!', content: 'Opposites are words that are completely different. Big/Small, Hot/Cold.', practice: { instruction: 'What is the opposite of "Up"?', task: 'Down' }, quiz: [{ question: 'What is the opposite of "Happy"?', options: ['Sad', 'Angry', 'Fast'], correctOption: 0 }], rewardPoints: 10 },
  { title: 'Compound Words', level: 'Primary 2', intro: '🎥 Animation: Sun + Flower = Sunflower!', content: 'Two words can join to make a new word. Rain + Bow = Rainbow.', practice: { instruction: 'Join: Star + Fish', task: 'Starfish' }, quiz: [{ question: 'Which is a compound word?', options: ['Starfish', 'Apple', 'Running'], correctOption: 0 }], rewardPoints: 15 },
  { title: 'Singular and Plural', level: 'Primary 2', intro: '🎥 Animation: One cat, two cats!', content: 'Add -s to make most words plural.', practice: { instruction: 'Make "dog" plural.', task: 'dogs' }, quiz: [{ question: 'Which is plural?', options: ['cat', 'cats', 'dog'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Using "A" and "An"', level: 'Primary 2', intro: '🎥 Animation: Apple vs Ball!', content: 'Use "an" before vowels (a, e, i, o, u). Use "a" before consonants.', practice: { instruction: 'A or An apple?', task: 'An' }, quiz: [{ question: 'Which is correct?', options: ['a apple', 'an apple', 'an ball'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Days of the Week', level: 'Primary 2', intro: '🎥 Animation: Calendar turning!', content: 'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.', practice: { instruction: 'What day comes after Monday?', task: 'Tuesday' }, quiz: [{ question: 'Which day is the weekend?', options: ['Monday', 'Saturday', 'Tuesday'], correctOption: 1 }], rewardPoints: 15 },
  // Primary 3
  { title: 'Nouns: Common and Proper', level: 'Primary 3', intro: '🎥 Animation: A boy named John in Lagos!', content: 'A noun is a name of a person, place, or thing. Proper nouns start with capitals.', practice: { instruction: 'Identify nouns in "The boy has a book."', task: 'boy, book' }, quiz: [{ question: 'Which is a proper noun?', options: ['city', 'London', 'boy'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Punctuation: Marks', level: 'Primary 3', intro: '🎥 Animation: A stop sign at the end of a sentence!', content: 'Full stops (.), Question marks (?), and Commas (,) help us read.', practice: { instruction: 'Where does the full stop go? "I like cake"', task: 'I like cake.' }, quiz: [{ question: 'Which sentence is correct?', options: ['I am happy.', 'I am happy', 'i am happy'], correctOption: 0 }], rewardPoints: 15 },
  { title: 'Pronouns', level: 'Primary 3', intro: '🎥 Animation: "He" replacing "The boy"!', content: 'Pronouns take the place of nouns. Examples: He, She, It, They, We.', practice: { instruction: 'Replace "Sarah" with a pronoun.', task: 'She' }, quiz: [{ question: 'Which is a pronoun?', options: ['Table', 'They', 'Jump'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Adjectives', level: 'Primary 3', intro: '🎥 Animation: Describing things!', content: 'Adjectives describe nouns. Big, Red, Happy.', practice: { instruction: 'Describe a flower.', task: 'Beautiful' }, quiz: [{ question: 'Which is an adjective?', options: ['Run', 'Big', 'Table'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Verbs: Action', level: 'Primary 3', intro: '🎥 Animation: Doing things!', content: 'Verbs are action words. Run, Eat, Play.', practice: { instruction: 'What is the action in "He eats"?', task: 'eats' }, quiz: [{ question: 'Which is a verb?', options: ['Jump', 'Cat', 'Red'], correctOption: 0 }], rewardPoints: 15 },
  { title: 'Writing Sentences', level: 'Primary 3', intro: '🎥 Animation: Building blocks!', content: 'A sentence needs a subject and a verb.', practice: { instruction: 'Write a sentence.', task: 'I like school.' }, quiz: [{ question: 'Which is a sentence?', options: ['I eat.', 'Eat.', 'I.'], correctOption: 0 }], rewardPoints: 15 },
  // Primary 4
  { title: 'Verbs: Present and Past', level: 'Primary 4', intro: '🎥 Animation: A clock ticking!', content: 'Present tense is now. Past tense happened before. Walk -> Walked.', practice: { instruction: 'Convert "He ran" to present tense.', task: 'He runs' }, quiz: [{ question: 'Choose the correct present tense sentence:', options: ['He run yesterday', 'He is running now', 'He will run'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'Adverbs of Manner', level: 'Primary 4', intro: '🎥 Animation: A turtle walking slowly!', content: 'Adverbs tell us how an action is done. Usually end in -ly. Quickly, Softly.', practice: { instruction: 'How did he run? "He ran ___."', task: 'quickly' }, quiz: [{ question: 'Which is an adverb?', options: ['Slowly', 'Slow', 'Slowness'], correctOption: 0 }], rewardPoints: 25 },
  { title: 'Prepositions of Place', level: 'Primary 4', intro: '🎥 Animation: A ball moving around a box!', content: 'Prepositions tell us where something is. Under, On, In, Behind, Beside.', practice: { instruction: 'Where is the cat? (The cat is ___ the table)', task: 'on/under' }, quiz: [{ question: 'The book is ___ the bag.', options: ['in', 'at', 'to'], correctOption: 0 }], rewardPoints: 20 },
  { title: 'Conjunctions', level: 'Primary 4', intro: '🎥 Animation: Joining words!', content: 'Conjunctions join words or sentences. And, But, Or.', practice: { instruction: 'Join "I like tea" and "I like coffee".', task: 'I like tea and coffee.' }, quiz: [{ question: 'Which is a conjunction?', options: ['And', 'Big', 'Run'], correctOption: 0 }], rewardPoints: 20 },
  { title: 'Tenses: Future', level: 'Primary 4', intro: '🎥 Animation: Looking ahead!', content: 'Future tense uses "will". I will go.', practice: { instruction: 'Convert "I go" to future.', task: 'I will go' }, quiz: [{ question: 'Which is future tense?', options: ['I went.', 'I go.', 'I will go.'], correctOption: 2 }], rewardPoints: 20 },
  { title: 'Direct Speech', level: 'Primary 4', intro: '🎥 Animation: Speech bubble!', content: 'Using quotation marks for what someone said.', practice: { instruction: 'Punctuate: He said I am happy', task: 'He said, "I am happy."' }, quiz: [{ question: 'Which is correct?', options: ['"Hello," he said.', 'Hello, he said.', 'Hello he said.'], correctOption: 0 }], rewardPoints: 20 },
  // Primary 5
  { title: 'Structure of an Essay', level: 'Primary 5', intro: '🎥 Animation: Building an essay block by block!', content: 'An essay has an Introduction, Body paragraphs, and a Conclusion.', practice: { instruction: 'Arrange: Introduction, Body, Conclusion', task: 'Introduction -> Body -> Conclusion' }, quiz: [{ question: 'Which part summarizes the essay?', options: ['Introduction', 'Body', 'Conclusion'], correctOption: 2 }], rewardPoints: 30 },
  { title: 'Direct and Indirect Speech', level: 'Primary 5', intro: '🎥 Animation: A speech bubble vs a report!', content: 'Direct speech uses quotation marks. Indirect speech reports what was said.', practice: { instruction: 'Change to indirect: "I am hungry," said John.', task: 'John said that he was hungry.' }, quiz: [{ question: 'Which is direct speech?', options: ['He said he was tired.', '"I am tired," he said.', 'He told me he is tired.'], correctOption: 1 }], rewardPoints: 35 },
  { title: 'Active and Passive Voice', level: 'Primary 5', intro: '🎥 Animation: The boy kicks the ball vs The ball is kicked!', content: 'Active voice: Subject does action. Passive voice: Subject receives action.', practice: { instruction: 'Change to passive: "She wrote a letter."', task: 'A letter was written by her.' }, quiz: [{ question: 'Which is passive voice?', options: ['He ate an apple.', 'An apple was eaten.', 'He is eating.'], correctOption: 1 }], rewardPoints: 35 },
  { title: 'Paragraph Writing', level: 'Primary 5', intro: '🎥 Animation: Topic sentence!', content: 'A paragraph has a topic sentence, supporting sentences, and a concluding sentence.', practice: { instruction: 'What is the first sentence?', task: 'Topic sentence' }, quiz: [{ question: 'A paragraph should have:', options: ['One idea', 'Many ideas', 'No ideas'], correctOption: 0 }], rewardPoints: 30 },
  { title: 'Formal Letters', level: 'Primary 5', intro: '🎥 Animation: Writing to a principal!', content: 'Formal letters have addresses, a subject, and a formal tone.', practice: { instruction: 'What is a formal letter for?', task: 'Official business' }, quiz: [{ question: 'Which is formal?', options: ['Dear Mom', 'Dear Principal', 'Hey friend'], correctOption: 1 }], rewardPoints: 30 },
  { title: 'Synonyms', level: 'Primary 5', intro: '🎥 Animation: Same meaning!', content: 'Synonyms are words with similar meanings. Big/Huge, Happy/Glad.', practice: { instruction: 'Synonym for "Small".', task: 'Tiny' }, quiz: [{ question: 'Synonym for "Fast"?', options: ['Quick', 'Slow', 'Sad'], correctOption: 0 }], rewardPoints: 30 },
  // Primary 6
  { title: 'Summary Writing Skills', level: 'Primary 6', intro: '🎥 Animation: Shrinking a long story!', content: 'Summarizing means identifying the main points and writing them briefly.', practice: { instruction: 'Summarize a short passage.', task: 'Main points identification' }, quiz: [{ question: 'A summary should be:', options: ['Longer', 'Shorter', 'Same'], correctOption: 1 }], rewardPoints: 35 },
  { title: 'Figures of Speech', level: 'Primary 6', intro: '🎥 Animation: Comparing a person to a lion!', content: 'Similes use "as" or "like". Metaphors say something IS something else.', practice: { instruction: 'Is "He is as brave as a lion" a simile or metaphor?', task: 'Simile' }, quiz: [{ question: 'Which is a metaphor?', options: ['He is a lion in battle.', 'He is like a lion.', 'He fought bravely.'], correctOption: 0 }], rewardPoints: 45 },
  { title: 'Sentence Types', level: 'Primary 6', intro: '🎥 Animation: Simple, Compound, and Complex sentences!', content: 'Sentences can be simple, compound (using and/but), or complex (using because/although).', practice: { instruction: 'Identify: "I like tea but I hate coffee."', task: 'Compound' }, quiz: [{ question: 'Which is a complex sentence?', options: ['I ran.', 'I ran and I fell.', 'I ran because I was late.'], correctOption: 2 }], rewardPoints: 45 },
  { title: 'Debate Skills', level: 'Primary 6', intro: '🎥 Animation: Speaking clearly!', content: 'Debating involves presenting arguments for or against a motion.', practice: { instruction: 'What is a motion?', task: 'The topic' }, quiz: [{ question: 'A debate needs:', options: ['Arguments', 'Fighting', 'Silence'], correctOption: 0 }], rewardPoints: 40 },
  { title: 'Poetry Analysis', level: 'Primary 6', intro: '🎥 Animation: Rhyme and rhythm!', content: 'Poetry uses imagery, rhyme, and rhythm to express feelings.', practice: { instruction: 'What is a poem?', task: 'Creative writing' }, quiz: [{ question: 'Which is a poetic device?', options: ['Rhyme', 'Sentence', 'Verb'], correctOption: 0 }], rewardPoints: 40 },
  { title: 'Editing and Proofreading', level: 'Primary 6', intro: '🎥 Animation: Fixing mistakes!', content: 'Checking for spelling, grammar, and punctuation errors.', practice: { instruction: 'Fix: "I is happy."', task: 'I am happy.' }, quiz: [{ question: 'Proofreading checks:', options: ['Spelling', 'Cooking', 'Running'], correctOption: 0 }], rewardPoints: 40 }
];

export const MATH_LESSONS: Partial<Lesson>[] = [
  // Primary 1
  { title: 'Counting to 20', level: 'Primary 1', intro: '🎥 Animation: Numbers jumping on a line!', content: 'Let\'s count: 1, 2, 3... up to 20! Can you count backward?', practice: { instruction: 'What comes after 10?', task: '11' }, quiz: [{ question: 'What is 5 + 2?', options: ['6', '7', '8'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Basic Shapes', level: 'Primary 1', intro: '🎥 Animation: A square turning into a box!', content: 'Circle, Square, Triangle, Rectangle. Shapes are everywhere!', practice: { instruction: 'How many sides does a triangle have?', task: '3' }, quiz: [{ question: 'Which shape is round?', options: ['Square', 'Circle', 'Triangle'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Addition with Pictures', level: 'Primary 1', intro: '🎥 Animation: 2 apples + 3 apples = 5 apples!', content: 'Adding means putting things together to find the total.', practice: { instruction: '2 + 1 = ?', task: '3' }, quiz: [{ question: 'If you have 3 balls and get 1 more, how many do you have?', options: ['2', '4', '5'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Subtraction with Pictures', level: 'Primary 1', intro: '🎥 Animation: 5 apples - 2 apples = 3 apples!', content: 'Subtraction means taking away.', practice: { instruction: '5 - 1 = ?', task: '4' }, quiz: [{ question: 'If you have 4 cars and lose 1, how many?', options: ['2', '3', '5'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Comparing Numbers', level: 'Primary 1', intro: '🎥 Animation: Scales!', content: 'Which is bigger? 5 or 3?', practice: { instruction: 'Which is bigger: 8 or 2?', task: '8' }, quiz: [{ question: 'Which is smaller?', options: ['1', '9', '5'], correctOption: 0 }], rewardPoints: 10 },
  { title: 'Patterns', level: 'Primary 1', intro: '🎥 Animation: Red, Blue, Red, Blue!', content: 'Patterns repeat.', practice: { instruction: 'What comes after Red, Blue, Red?', task: 'Blue' }, quiz: [{ question: 'What comes next: 1, 2, 1, 2?', options: ['1', '2', '3'], correctOption: 0 }], rewardPoints: 10 },
  // Primary 2
  { title: 'Place Value: Tens and Units', level: 'Primary 2', intro: '🎥 Animation: Bundles of sticks!', content: 'In 25, 2 is Tens and 5 is Units. 20 + 5 = 25.', practice: { instruction: 'How many tens in 43?', task: '4' }, quiz: [{ question: 'What is the value of 3 in 38?', options: ['3', '30', '8'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Subtraction with Borrowing', level: 'Primary 2', intro: '🎥 Animation: Taking away from a group!', content: 'Subtraction means taking away. Sometimes we need to borrow from tens.', practice: { instruction: '15 - 7 = ?', task: '8' }, quiz: [{ question: 'What is 20 - 5?', options: ['10', '15', '25'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Measuring Length', level: 'Primary 2', intro: '🎥 Animation: A ruler measuring a pencil!', content: 'We use rulers to measure in centimeters (cm) and meters (m).', practice: { instruction: 'Measure your pencil.', task: 'cm' }, quiz: [{ question: 'Which is longer?', options: ['10cm', '5cm', '2cm'], correctOption: 0 }], rewardPoints: 15 },
  { title: 'Addition of 3 Numbers', level: 'Primary 2', intro: '🎥 Animation: Adding 1+2+3!', content: 'Add three numbers together.', practice: { instruction: '1+2+3 = ?', task: '6' }, quiz: [{ question: 'What is 2+2+2?', options: ['4', '6', '8'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Even and Odd Numbers', level: 'Primary 2', intro: '🎥 Animation: Pairs!', content: 'Even numbers can be paired. Odd cannot.', practice: { instruction: 'Is 2 even?', task: 'Yes' }, quiz: [{ question: 'Which is odd?', options: ['2', '4', '3'], correctOption: 2 }], rewardPoints: 15 },
  { title: 'Time: Half-Hours', level: 'Primary 2', intro: '🎥 Animation: Clock face!', content: 'Half past the hour.', practice: { instruction: 'What is half past 1?', task: '1:30' }, quiz: [{ question: 'Half past 2 is:', options: ['2:00', '2:30', '3:00'], correctOption: 1 }], rewardPoints: 15 },
  // Primary 3
  { title: 'Multiplication Tables', level: 'Primary 3', intro: '🎥 Animation: Groups of 2s!', content: 'Multiplication is repeated addition. 2 x 3 = 2 + 2 + 2 = 6.', practice: { instruction: 'What is 3 x 4?', task: '12' }, quiz: [{ question: '5 x 2 = ?', options: ['7', '10', '12'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'Fractions: Halves and Quarters', level: 'Primary 3', intro: '🎥 Animation: Cutting a pizza!', content: 'A half is 1/2. A quarter is 1/4. Two quarters make a half.', practice: { instruction: 'How many quarters make a whole?', task: '4' }, quiz: [{ question: 'Which is bigger?', options: ['1/2', '1/4', '1/8'], correctOption: 0 }], rewardPoints: 20 },
  { title: 'Telling Time', level: 'Primary 3', intro: '🎥 Animation: A clock face moving!', content: 'Long hand is minutes, short hand is hours. 60 minutes = 1 hour.', practice: { instruction: 'Where is the long hand at 3:30?', task: 'At 6' }, quiz: [{ question: 'How many minutes in an hour?', options: ['30', '60', '100'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'Division as Sharing', level: 'Primary 3', intro: '🎥 Animation: Sharing cookies!', content: 'Sharing equally.', practice: { instruction: 'Share 6 cookies among 2.', task: '3 each' }, quiz: [{ question: 'What is 8 / 2?', options: ['2', '4', '6'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'Perimeter', level: 'Primary 3', intro: '🎥 Animation: Walking around a shape!', content: 'Perimeter is the distance around a shape.', practice: { instruction: 'Perimeter of 2x2 square?', task: '8' }, quiz: [{ question: 'If sides are 3, 3, 3, 3, P = ?', options: ['9', '12', '15'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'Money: Addition', level: 'Primary 3', intro: '🎥 Animation: Counting coins!', content: 'Adding Naira and Kobo.', practice: { instruction: 'N10 + N5 = ?', task: 'N15' }, quiz: [{ question: 'N20 - N5 = ?', options: ['N10', 'N15', 'N25'], correctOption: 1 }], rewardPoints: 20 },
  // Primary 4
  { title: 'Long Division', level: 'Primary 4', intro: '🎥 Animation: Sharing 100 candies!', content: 'Division is sharing into equal groups. 100 divided by 4 is 25.', practice: { instruction: '100 / 4 = ?', task: '25' }, quiz: [{ question: 'What is 48 / 6?', options: ['7', '8', '9'], correctOption: 1 }], rewardPoints: 25 },
  { title: 'Decimals', level: 'Primary 4', intro: '🎥 Animation: Points between numbers!', content: 'Decimals are parts of a whole, like 0.5. They follow the decimal point.', practice: { instruction: 'Write 1/2 as a decimal.', task: '0.5' }, quiz: [{ question: 'Which is larger?', options: ['0.1', '0.5', '0.09'], correctOption: 1 }], rewardPoints: 25 },
  { title: 'Area of Rectangles', level: 'Primary 4', intro: '🎥 Animation: Filling a floor with tiles!', content: 'Area is the space inside a shape. Area = Length x Width.', practice: { instruction: 'Area of 5cm by 3cm rectangle?', task: '15 sq cm' }, quiz: [{ question: 'If L=4 and W=2, Area = ?', options: ['6', '8', '10'], correctOption: 1 }], rewardPoints: 25 },
  { title: 'Factors and Multiples', level: 'Primary 4', intro: '🎥 Animation: Building blocks!', content: 'Factors divide a number. Multiples are products.', practice: { instruction: 'Factor of 6?', task: '1, 2, 3, 6' }, quiz: [{ question: 'Which is a multiple of 3?', options: ['4', '6', '7'], correctOption: 1 }], rewardPoints: 25 },
  { title: 'Fractions: Equivalent', level: 'Primary 4', intro: '🎥 Animation: Same size!', content: '1/2 = 2/4 = 4/8.', practice: { instruction: 'Is 1/2 = 2/4?', task: 'Yes' }, quiz: [{ question: 'Which is equivalent to 1/3?', options: ['2/6', '1/6', '3/6'], correctOption: 0 }], rewardPoints: 25 },
  { title: 'Angles: Introduction', level: 'Primary 4', intro: '🎥 Animation: Opening a door!', content: 'Angles are the space between two lines.', practice: { instruction: 'What is a 90° angle?', task: 'Right angle' }, quiz: [{ question: 'Which angle is 90°?', options: ['Acute', 'Right', 'Obtuse'], correctOption: 1 }], rewardPoints: 25 },
  // Primary 5
  { title: 'Percentages', level: 'Primary 5', intro: '🎥 Animation: 100 squares being colored!', content: 'Percentage means "out of 100". 50% is 50/100 or 1/2.', practice: { instruction: 'What is 10% of 100?', task: '10' }, quiz: [{ question: '25% is the same as:', options: ['1/2', '1/4', '1/5'], correctOption: 1 }], rewardPoints: 30 },
  { title: 'Ratio and Proportion', level: 'Primary 5', intro: '🎥 Animation: Mixing paint 2:1!', content: 'Ratios compare two quantities. Proportion shows they are equal.', practice: { instruction: 'Ratio of 2 apples to 3 oranges?', task: '2:3' }, quiz: [{ question: 'If the ratio is 1:2, for every 1 boy there are ___ girls.', options: ['1', '2', '3'], correctOption: 1 }], rewardPoints: 30 },
  { title: 'Angles: Types', level: 'Primary 5', intro: '🎥 Animation: A pair of scissors opening!', content: 'Right angle = 90°. Acute < 90°. Obtuse > 90°.', practice: { instruction: 'What is a 45° angle called?', task: 'Acute' }, quiz: [{ question: 'A 120° angle is:', options: ['Acute', 'Right', 'Obtuse'], correctOption: 2 }], rewardPoints: 30 },
  { title: 'Prime Numbers', level: 'Primary 5', intro: '🎥 Animation: Only divisible by 1 and self!', content: '2, 3, 5, 7, 11...', practice: { instruction: 'Is 4 prime?', task: 'No' }, quiz: [{ question: 'Which is prime?', options: ['6', '7', '8'], correctOption: 1 }], rewardPoints: 30 },
  { title: 'Average', level: 'Primary 5', intro: '🎥 Animation: Balancing!', content: 'Sum divided by count.', practice: { instruction: 'Average of 2 and 4?', task: '3' }, quiz: [{ question: 'Average of 10, 20?', options: ['10', '15', '20'], correctOption: 1 }], rewardPoints: 30 },
  { title: 'Symmetry', level: 'Primary 5', intro: '🎥 Animation: Mirror image!', content: 'Same on both sides.', practice: { instruction: 'Is a butterfly symmetrical?', task: 'Yes' }, quiz: [{ question: 'Which shape has symmetry?', options: ['Circle', 'Irregular', 'Triangle'], correctOption: 0 }], rewardPoints: 30 },
  // Primary 6
  { title: 'Algebraic Expressions', level: 'Primary 6', intro: '🎥 Animation: X marks the spot!', content: 'Algebra uses letters for numbers. x + 5 = 10, so x = 5.', practice: { instruction: 'Solve for y: 2y = 10', task: 'y = 5' }, quiz: [{ question: 'If a = 2, what is 3a + 1?', options: ['5', '6', '7'], correctOption: 2 }], rewardPoints: 40 },
  { title: 'Data: Mean, Median, Mode', level: 'Primary 6', intro: '🎥 Animation: Sorting heights!', content: 'Mean is average. Median is middle. Mode is most frequent.', practice: { instruction: 'Mean of 2, 4, 6?', task: '4' }, quiz: [{ question: 'What is the mode of 1, 2, 2, 3?', options: ['1', '2', '3'], correctOption: 1 }], rewardPoints: 40 },
  { title: 'Volume of Cuboids', level: 'Primary 6', intro: '🎥 Animation: Filling a tank!', content: 'Volume = Length x Width x Height. Measured in cubic units.', practice: { instruction: 'Volume of 2x3x4 box?', task: '24 cubic units' }, quiz: [{ question: 'If L=2, W=2, H=2, Volume = ?', options: ['4', '6', '8'], correctOption: 2 }], rewardPoints: 40 },
  { title: 'Circles: Parts', level: 'Primary 6', intro: '🎥 Animation: Drawing a circle!', content: 'Radius, Diameter, Circumference.', practice: { instruction: 'Is diameter 2x radius?', task: 'Yes' }, quiz: [{ question: 'Which is the distance across?', options: ['Radius', 'Diameter', 'Circumference'], correctOption: 1 }], rewardPoints: 40 },
  { title: 'Probability', level: 'Primary 6', intro: '🎥 Animation: Tossing a coin!', content: 'Chance of something happening.', practice: { instruction: 'Chance of heads?', task: '1/2' }, quiz: [{ question: 'Chance of rolling 1 on a die?', options: ['1/6', '1/2', '1/3'], correctOption: 0 }], rewardPoints: 40 },
  { title: 'Integers', level: 'Primary 6', intro: '🎥 Animation: Below zero!', content: 'Positive and negative numbers.', practice: { instruction: 'What is -2 + 3?', task: '1' }, quiz: [{ question: 'Which is smaller?', options: ['-5', '0', '5'], correctOption: 0 }], rewardPoints: 40 }
];

export const SCIENCE_LESSONS: Partial<Lesson>[] = [
  // Primary 1
  { title: 'Living and Non-living', level: 'Primary 1', intro: '🎥 Animation: A puppy vs a rock!', content: 'Living things grow, eat, and move. Non-living things do not.', practice: { instruction: 'Is a tree living or non-living?', task: 'Living' }, quiz: [{ question: 'Which is living?', options: ['Car', 'Cat', 'Stone'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Parts of the Body', level: 'Primary 1', intro: '🎥 Animation: Head, shoulders, knees!', content: 'Head, Eyes, Nose, Mouth, Arms, Legs. We use them for different things.', practice: { instruction: 'What do you use to see?', task: 'Eyes' }, quiz: [{ question: 'Where are your toes?', options: ['On your hands', 'On your feet', 'On your head'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'The Five Senses', level: 'Primary 1', intro: '🎥 Animation: Smelling a flower!', content: 'Sight, Hearing, Smell, Taste, and Touch help us know the world.', practice: { instruction: 'What do you use to taste?', task: 'Tongue' }, quiz: [{ question: 'Which sense uses the ears?', options: ['Sight', 'Hearing', 'Smell'], correctOption: 1 }], rewardPoints: 10 },
  // Primary 2
  { title: 'Plants: Parts', level: 'Primary 2', intro: '🎥 Animation: A seed growing!', content: 'Plants have roots, stems, leaves, and flowers. They need sunlight.', practice: { instruction: 'What do plants need to grow?', task: 'Water, Sunlight, Soil' }, quiz: [{ question: 'Which part is underground?', options: ['Leaves', 'Roots', 'Flower'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Animals and Young', level: 'Primary 2', intro: '🎥 Animation: A cat and a kitten!', content: 'Dog -> Puppy, Cat -> Kitten, Cow -> Calf, Frog -> Tadpole.', practice: { instruction: 'What is a baby lion called?', task: 'Cub' }, quiz: [{ question: 'A baby frog is a:', options: ['Fry', 'Tadpole', 'Chick'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Water and Its Uses', level: 'Primary 2', intro: '🎥 Animation: Drinking and washing!', content: 'We use water for drinking, washing, cooking, and farming.', practice: { instruction: 'Name one use of water.', task: 'Drinking' }, quiz: [{ question: 'Can we live without water?', options: ['Yes', 'No'], correctOption: 1 }], rewardPoints: 15 },
  // Primary 3
  { title: 'The Solar System', level: 'Primary 3', intro: '🎥 Animation: Planets orbiting!', content: 'The Sun is at the center. There are 8 planets. Earth is the 3rd.', practice: { instruction: 'Which planet do we live on?', task: 'Earth' }, quiz: [{ question: 'Which is the largest planet?', options: ['Earth', 'Mars', 'Jupiter'], correctOption: 2 }], rewardPoints: 20 },
  { title: 'States of Matter', level: 'Primary 3', intro: '🎥 Animation: Ice melting!', content: 'Solid (Ice), Liquid (Water), Gas (Steam). Matter is everything.', practice: { instruction: 'Is steam a gas?', task: 'Yes' }, quiz: [{ question: 'Which is a solid?', options: ['Water', 'Ice', 'Air'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'Soil Types', level: 'Primary 3', intro: '🎥 Animation: Sandy vs Clay soil!', content: 'Sandy, Clay, and Loamy soil. Loamy is best for plants.', practice: { instruction: 'Which soil is best for farming?', task: 'Loamy' }, quiz: [{ question: 'Which soil feels sticky?', options: ['Sandy', 'Clay', 'Loamy'], correctOption: 1 }], rewardPoints: 20 },
  // Primary 4
  { title: 'Digestive System', level: 'Primary 4', intro: '🎥 Animation: Food traveling!', content: 'Mouth -> Esophagus -> Stomach -> Intestines. Digestion breaks down food.', practice: { instruction: 'Where does digestion start?', task: 'Mouth' }, quiz: [{ question: 'Which organ grinds food?', options: ['Heart', 'Stomach', 'Lungs'], correctOption: 1 }], rewardPoints: 25 },
  { title: 'Energy Forms', level: 'Primary 4', intro: '🎥 Animation: A light bulb!', content: 'Light, Heat, Sound, Electrical, and Chemical energy.', practice: { instruction: 'What energy comes from the sun?', task: 'Solar' }, quiz: [{ question: 'A battery stores ___ energy.', options: ['Chemical', 'Sound', 'Light'], correctOption: 0 }], rewardPoints: 25 },
  { title: 'Weather and Climate', level: 'Primary 4', intro: '🎥 Animation: Rain and Sun!', content: 'Weather is daily. Climate is long-term. We use a rain gauge for rain.', practice: { instruction: 'What measures temperature?', task: 'Thermometer' }, quiz: [{ question: 'Which measures wind direction?', options: ['Rain gauge', 'Wind vane', 'Barometer'], correctOption: 1 }], rewardPoints: 25 },
  // Primary 5
  { title: 'Circulatory System', level: 'Primary 5', intro: '🎥 Animation: A heart beating!', content: 'The heart pumps blood. Arteries carry oxygenated blood.', practice: { instruction: 'What pumps blood?', task: 'Heart' }, quiz: [{ question: 'Blood carries ___ to the body.', options: ['Food', 'Oxygen', 'Waste'], correctOption: 1 }], rewardPoints: 30 },
  { title: 'Simple Machines', level: 'Primary 5', intro: '🎥 Animation: Using a lever!', content: 'Lever, Pulley, Inclined Plane, Wheel and Axle. They make work easier.', practice: { instruction: 'Is a slide an inclined plane?', task: 'Yes' }, quiz: [{ question: 'A pair of scissors is a:', options: ['Pulley', 'Lever', 'Wedge'], correctOption: 1 }], rewardPoints: 30 },
  { title: 'The Respiratory System', level: 'Primary 5', intro: '🎥 Animation: Lungs expanding!', content: 'We breathe in Oxygen and breathe out Carbon Dioxide using our lungs.', practice: { instruction: 'What gas do we breathe in?', task: 'Oxygen' }, quiz: [{ question: 'Main organ for breathing?', options: ['Heart', 'Lungs', 'Liver'], correctOption: 1 }], rewardPoints: 30 },
  // Primary 6
  { title: 'Plant Reproduction', level: 'Primary 6', intro: '🎥 Animation: A bee and pollen!', content: 'Pollination is the transfer of pollen. Fertilization creates seeds.', practice: { instruction: 'What carries pollen?', task: 'Insects/Wind' }, quiz: [{ question: 'What carries pollen?', options: ['Insects/Wind', 'Water', 'Cars'], correctOption: 0 }], rewardPoints: 40 },
  { title: 'Electricity Basics', level: 'Primary 6', intro: '🎥 Animation: A complete circuit!', content: 'A circuit needs a power source, wires, and a load (bulb).', practice: { instruction: 'What happens if a circuit is broken?', task: 'Bulb won\'t light' }, quiz: [{ question: 'A material that allows electricity to pass is a:', options: ['Insulator', 'Conductor', 'Resistor'], correctOption: 1 }], rewardPoints: 40 },
  { title: 'Environmental Pollution', level: 'Primary 6', intro: '🎥 Animation: Smoke and Trash!', content: 'Air, Water, and Land pollution harm the earth. We must recycle.', practice: { instruction: 'Name one type of pollution.', task: 'Air/Water/Land' }, quiz: [{ question: 'Which helps the environment?', options: ['Littering', 'Recycling', 'Burning plastic'], correctOption: 1 }], rewardPoints: 40 }
];

export const SOCIAL_LESSONS: Partial<Lesson>[] = [
  // Primary 1
  { title: 'My Family', level: 'Primary 1', intro: '🎥 Animation: A happy family!', content: 'A family is a group of people related by blood or marriage. Parents and children.', practice: { instruction: 'Who are your parents?', task: 'Father and Mother' }, quiz: [{ question: 'Who is your father\'s wife?', options: ['Aunt', 'Mother', 'Sister'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'My School', level: 'Primary 1', intro: '🎥 Animation: A school building!', content: 'School is where we learn. We have teachers, classmates, and a principal.', practice: { instruction: 'What do you do at school?', task: 'Learn and Play' }, quiz: [{ question: 'Who teaches at school?', options: ['Doctor', 'Teacher', 'Pilot'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'My Home', level: 'Primary 1', intro: '🎥 Animation: A cozy house!', content: 'Home is where we live with our family. It keeps us safe and warm.', practice: { instruction: 'What do you do at home?', task: 'Sleep and Eat' }, quiz: [{ question: 'What protects us from rain?', options: ['A house', 'A car', 'A tree'], correctOption: 0 }], rewardPoints: 10 },
  // Primary 2
  { title: 'Our Community', level: 'Primary 2', intro: '🎥 Animation: People helping!', content: 'A community is a group of people living together. We help each other.', practice: { instruction: 'Who helps when we are sick?', task: 'Doctor' }, quiz: [{ question: 'Who keeps us safe?', options: ['Teacher', 'Police', 'Baker'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Good Manners', level: 'Primary 2', intro: '🎥 Animation: Saying "Please"!', content: 'Respect others by saying "Please", "Thank You", and "Sorry".', practice: { instruction: 'What do you say for a gift?', task: 'Thank You' }, quiz: [{ question: 'Which is a good manner?', options: ['Shouting', 'Sharing', 'Fighting'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Community Helpers', level: 'Primary 2', intro: '🎥 Animation: A firefighter!', content: 'Firefighters, Doctors, Teachers, and Farmers all help our community grow.', practice: { instruction: 'Who grows our food?', task: 'Farmer' }, quiz: [{ question: 'Who puts out fires?', options: ['Doctor', 'Firefighter', 'Pilot'], correctOption: 1 }], rewardPoints: 15 },
  // Primary 3
  { title: 'Nigerian Culture', level: 'Primary 3', intro: '🎥 Animation: Traditional dancers!', content: 'Nigeria has many cultures like Yoruba, Igbo, and Hausa. Each has unique food and dress.', practice: { instruction: 'Name a Nigerian food.', task: 'Jollof Rice' }, quiz: [{ question: 'How many major ethnic groups?', options: ['2', '3', '10'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'Transportation', level: 'Primary 3', intro: '🎥 Animation: Car, Plane, Boat!', content: 'Moving people and goods. Land (Car), Air (Plane), Water (Ship).', practice: { instruction: 'Which is an air transport?', task: 'Aeroplane' }, quiz: [{ question: 'Which travels on water?', options: ['Bus', 'Train', 'Ship'], correctOption: 2 }], rewardPoints: 20 },
  { title: 'Communication', level: 'Primary 3', intro: '🎥 Animation: Talking on a phone!', content: 'Sharing information. Long ago: Town Crier. Now: Phones, Internet.', practice: { instruction: 'How did people send messages long ago?', task: 'Town Crier' }, quiz: [{ question: 'Which is modern?', options: ['Town Crier', 'Mobile Phone', 'Smoke'], correctOption: 1 }], rewardPoints: 20 },
  // Primary 4
  { title: 'Leadership Qualities', level: 'Primary 4', intro: '🎥 Animation: A leader guiding!', content: 'A leader is honest, brave, and helpful. They guide others to do good.', practice: { instruction: 'Name a quality of a leader.', task: 'Honesty' }, quiz: [{ question: 'Who leads a school?', options: ['Prefect', 'Principal', 'Governor'], correctOption: 1 }], rewardPoints: 25 },
  { title: 'Our Environment', level: 'Primary 4', intro: '🎥 Animation: Cleaning up!', content: 'Keep our surroundings clean. Don\'t litter. Plant trees.', practice: { instruction: 'Where should we throw trash?', task: 'Dustbin' }, quiz: [{ question: 'Littering is good.', options: ['True', 'False'], correctOption: 1 }], rewardPoints: 25 },
  { title: 'Natural Resources', level: 'Primary 4', intro: '🎥 Animation: Water and Gold!', content: 'Things from nature we use: Water, Trees, Oil, Gold, Coal.', practice: { instruction: 'Name one resource.', task: 'Water' }, quiz: [{ question: 'Which is natural?', options: ['Plastic', 'Water', 'Glass'], correctOption: 1 }], rewardPoints: 25 },
  // Primary 5
  { title: 'Resources in Nigeria', level: 'Primary 5', intro: '🎥 Animation: Oil rigs!', content: 'Nigeria has Crude Oil, Cocoa, Coal, and Tin. Oil is the main export.', practice: { instruction: 'What is the main export?', task: 'Crude Oil' }, quiz: [{ question: 'Where is coal found?', options: ['Enugu', 'Lagos', 'Kano'], correctOption: 0 }], rewardPoints: 30 },
  { title: 'Rivers in Nigeria', level: 'Primary 5', intro: '🎥 Animation: River Niger!', content: 'Major rivers: Niger and Benue. They meet at Lokoja (Confluence).', practice: { instruction: 'Where do the rivers meet?', task: 'Lokoja' }, quiz: [{ question: 'Longest river in Nigeria?', options: ['Benue', 'Niger', 'Ogun'], correctOption: 1 }], rewardPoints: 30 },
  { title: 'Agriculture: Types', level: 'Primary 5', intro: '🎥 Animation: Harvesting yams!', content: 'Subsistence (for family) and Commercial (for sale) farming.', practice: { instruction: 'Name two crops.', task: 'Yam, Cassava' }, quiz: [{ question: 'Main crop in the North?', options: ['Cocoa', 'Groundnut', 'Palm Oil'], correctOption: 1 }], rewardPoints: 30 },
  // Primary 6
  { title: 'Global Citizenship', level: 'Primary 6', intro: '🎥 Animation: World children!', content: 'Caring about the whole world. Protecting the planet and helping others.', practice: { instruction: 'How can you help?', task: 'Recycling' }, quiz: [{ question: 'What does UN stand for?', options: ['United Nations', 'Union Network'], correctOption: 0 }], rewardPoints: 40 },
  { title: 'Human Rights', level: 'Primary 6', intro: '🎥 Animation: People together!', content: 'Basic freedoms for everyone: Right to life, education, and speech.', practice: { instruction: 'Name one right.', task: 'Right to life' }, quiz: [{ question: 'Who has human rights?', options: ['Adults', 'Rich', 'Everyone'], correctOption: 2 }], rewardPoints: 40 },
  { title: 'International Orgs', level: 'Primary 6', intro: '🎥 Animation: AU flag!', content: 'AU (African Union) and ECOWAS help countries work together for peace.', practice: { instruction: 'What is ECOWAS?', task: 'West African States' }, quiz: [{ question: 'Which is for all Africa?', options: ['ECOWAS', 'AU', 'UN'], correctOption: 1 }], rewardPoints: 40 }
];

export const ICT_LESSONS: Partial<Lesson>[] = [
  // Primary 1
  { title: 'Parts of a Computer', level: 'Primary 1', intro: '🎥 Animation: Monitor and Mouse!', content: 'A computer has a screen (monitor), a mouse, and a keyboard.', practice: { instruction: 'What do we use to type?', task: 'Keyboard' }, quiz: [{ question: 'Which part is the screen?', options: ['Mouse', 'Monitor', 'CPU'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'The Mouse: Click', level: 'Primary 1', intro: '🎥 Animation: Clicking!', content: 'The mouse helps us point and click on things on the screen.', practice: { instruction: 'What do you do with a mouse?', task: 'Click' }, quiz: [{ question: 'How many buttons usually?', options: ['1', '2', '10'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Computer Care', level: 'Primary 1', intro: '🎥 Animation: Cleaning!', content: 'Keep computers clean. No food or drinks near them.', practice: { instruction: 'Drink water near PC?', task: 'No' }, quiz: [{ question: 'Treat a computer:', options: ['Gently', 'Roughly', 'Throw'], correctOption: 0 }], rewardPoints: 10 },
  // Primary 2
  { title: 'Uses of Computers', level: 'Primary 2', intro: '🎥 Animation: Playing games!', content: 'Typing, playing games, watching videos, and learning.', practice: { instruction: 'Can you learn on a PC?', task: 'Yes' }, quiz: [{ question: 'Which can a PC NOT do?', options: ['Type', 'Cook food', 'Play music'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Types: Laptop & Tablet', level: 'Primary 2', intro: '🎥 Animation: Laptop!', content: 'Desktops stay on desks. Laptops and tablets are portable.', practice: { instruction: 'Which is portable?', task: 'Laptop' }, quiz: [{ question: 'Portable computer:', options: ['Desktop', 'Laptop', 'Fridge'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Turning On/Off', level: 'Primary 2', intro: '🎥 Animation: Power button!', content: 'Use the power button to turn on. Use "Shut Down" to turn off.', practice: { instruction: 'How to turn off?', task: 'Shut Down' }, quiz: [{ question: 'Should you just pull the plug?', options: ['Yes', 'No'], correctOption: 1 }], rewardPoints: 15 },
  // Primary 3
  { title: 'Input and Output', level: 'Primary 3', intro: '🎥 Animation: Typing vs Printing!', content: 'Input: Keyboard, Mouse. Output: Monitor, Printer, Speakers.', practice: { instruction: 'Is mouse input?', task: 'Yes' }, quiz: [{ question: 'Which is output?', options: ['Keyboard', 'Printer', 'Mouse'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'Storage Devices', level: 'Primary 3', intro: '🎥 Animation: Flash drive!', content: 'Hard drives, Flash drives, and CDs keep our work safe.', practice: { instruction: 'Where to save work?', task: 'Storage' }, quiz: [{ question: 'Which is storage?', options: ['Monitor', 'Flash Drive', 'Speaker'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'The Keyboard', level: 'Primary 3', intro: '🎥 Animation: Typing letters!', content: 'Letters, numbers, and special keys like Enter and Spacebar.', practice: { instruction: 'Longest key?', task: 'Spacebar' }, quiz: [{ question: 'Which key starts a new line?', options: ['Space', 'Enter', 'Shift'], correctOption: 1 }], rewardPoints: 20 },
  // Primary 4
  { title: 'The System Unit', level: 'Primary 4', intro: '🎥 Animation: Inside the box!', content: 'The system unit houses the CPU (Central Processing Unit) - the brain.', practice: { instruction: 'What is the brain?', task: 'CPU' }, quiz: [{ question: 'What is the brain?', options: ['CPU', 'Monitor', 'Mouse'], correctOption: 0 }], rewardPoints: 25 },
  { title: 'Computer Software', level: 'Primary 4', intro: '🎥 Animation: App icons!', content: 'Software are programs like Windows, Word, and Games.', practice: { instruction: 'Is a game software?', task: 'Yes' }, quiz: [{ question: 'Which is software?', options: ['Mouse', 'Windows', 'Monitor'], correctOption: 1 }], rewardPoints: 25 },
  { title: 'Operating Systems', level: 'Primary 4', intro: '🎥 Animation: Windows logo!', content: 'The OS manages everything. Examples: Windows, macOS, Android.', practice: { instruction: 'Name an OS.', task: 'Windows' }, quiz: [{ question: 'Is Android an OS?', options: ['Yes', 'No'], correctOption: 0 }], rewardPoints: 25 },
  // Primary 5
  { title: 'The Internet: WWW', level: 'Primary 5', intro: '🎥 Animation: A web!', content: 'Global network of computers. WWW = World Wide Web.', practice: { instruction: 'What to use to browse?', task: 'Browser' }, quiz: [{ question: 'What is WWW?', options: ['World Wide Web', 'Web World Wide'], correctOption: 0 }], rewardPoints: 30 },
  { title: 'Email Basics', level: 'Primary 5', intro: '🎥 Animation: Flying envelope!', content: 'Fast electronic mail. Needs an email address like user@mail.com.', practice: { instruction: 'What do you need?', task: 'Email address' }, quiz: [{ question: 'Which is an email?', options: ['www.google.com', 'user@gmail.com', '123 St'], correctOption: 1 }], rewardPoints: 30 },
  { title: 'Search Engines', level: 'Primary 5', intro: '🎥 Animation: Google search!', content: 'Tools to find info. Examples: Google, Bing, Yahoo.', practice: { instruction: 'Name a search engine.', task: 'Google' }, quiz: [{ question: 'Which is a search engine?', options: ['Word', 'Google', 'Excel'], correctOption: 1 }], rewardPoints: 30 },
  // Primary 6
  { title: 'Intro to Coding', level: 'Primary 6', intro: '🎥 Animation: Robot commands!', content: 'Coding is giving instructions. A set of steps is an Algorithm.', practice: { instruction: 'What is an algorithm?', task: 'Steps' }, quiz: [{ question: 'Which is a language?', options: ['Python', 'Snake', 'Apple'], correctOption: 0 }], rewardPoints: 45 },
  { title: 'Online Safety', level: 'Primary 6', intro: '🎥 Animation: A shield!', content: 'Don\'t share passwords. Be kind. Tell adults about mean people.', practice: { instruction: 'Share password?', task: 'No' }, quiz: [{ question: 'If someone is mean:', options: ['Mean back', 'Tell adult', 'Nothing'], correctOption: 1 }], rewardPoints: 45 },
  { title: 'Word Processing', level: 'Primary 6', intro: '🎥 Animation: Typing a letter!', content: 'Creating documents. Bold, Italic, and Underline help style text.', practice: { instruction: 'What makes text dark?', task: 'Bold' }, quiz: [{ question: 'Which is for documents?', options: ['Excel', 'Word', 'Paint'], correctOption: 1 }], rewardPoints: 40 }
];

export const CIVIC_LESSONS: Partial<Lesson>[] = [
  // Primary 1
  { title: 'Showing Respect', level: 'Primary 1', intro: '🎥 Animation: Bowing!', content: 'Be kind and polite to elders, teachers, and friends.', practice: { instruction: 'How to show respect?', task: 'Polite words' }, quiz: [{ question: 'Is shouting respectful?', options: ['Yes', 'No'], correctOption: 1 }], rewardPoints: 10 },
  { title: 'Obedience', level: 'Primary 1', intro: '🎥 Animation: Listening!', content: 'Obey parents and teachers. Follow school rules.', practice: { instruction: 'Who to obey?', task: 'Parents/Teachers' }, quiz: [{ question: 'Is it good to obey?', options: ['Yes', 'No'], correctOption: 0 }], rewardPoints: 10 },
  { title: 'Greeting Others', level: 'Primary 1', intro: '🎥 Animation: Waving!', content: 'Say "Good Morning", "Good Afternoon", and "Good Evening".', practice: { instruction: 'Morning greeting?', task: 'Good Morning' }, quiz: [{ question: 'Is greeting good?', options: ['Yes', 'No'], correctOption: 0 }], rewardPoints: 10 },
  // Primary 2
  { title: 'Honesty', level: 'Primary 2', intro: '🎥 Animation: Telling truth!', content: 'Always tell the truth. Don\'t take what isn\'t yours.', practice: { instruction: 'What is honesty?', task: 'Truth' }, quiz: [{ question: 'Find a pen, you should:', options: ['Keep it', 'Find owner', 'Hide it'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Self-Control', level: 'Primary 2', intro: '🎥 Animation: Deep breath!', content: 'Control your feelings. Don\'t hit or shout when angry.', practice: { instruction: 'When angry, do what?', task: 'Stay calm' }, quiz: [{ question: 'Is hitting self-control?', options: ['Yes', 'No'], correctOption: 1 }], rewardPoints: 15 },
  { title: 'Helping Others', level: 'Primary 2', intro: '🎥 Animation: Helping a friend!', content: 'Help those in need. Share your toys and books.', practice: { instruction: 'Should we share?', task: 'Yes' }, quiz: [{ question: 'Helping is:', options: ['Good', 'Bad', 'Boring'], correctOption: 0 }], rewardPoints: 15 },
  // Primary 3
  { title: 'National Symbols', level: 'Primary 3', intro: '🎥 Animation: Flag waving!', content: 'Flag (Green-White-Green), Coat of Arms, Anthem, Pledge.', practice: { instruction: 'Flag colors?', task: 'Green, White' }, quiz: [{ question: 'How many colors in flag?', options: ['2', '3', '4'], correctOption: 0 }], rewardPoints: 20 },
  { title: 'National Identity', level: 'Primary 3', intro: '🎥 Animation: Proud Nigerian!', content: 'We are Nigerians. We love our country and its symbols.', practice: { instruction: 'Your nationality?', task: 'Nigerian' }, quiz: [{ question: 'Which is a symbol?', options: ['Toy', 'Flag', 'Car'], correctOption: 1 }], rewardPoints: 20 },
  { title: 'The National Anthem', level: 'Primary 3', intro: '🎥 Animation: Singing!', content: 'Stand at attention when singing the anthem. It shows respect.', practice: { instruction: 'What to do during anthem?', task: 'Stand still' }, quiz: [{ question: 'Should we talk during anthem?', options: ['Yes', 'No'], correctOption: 1 }], rewardPoints: 20 },
  // Primary 4
  { title: 'Our Rights', level: 'Primary 4', intro: '🎥 Animation: Kids at school!', content: 'Right to life, education, health, and protection from harm.', practice: { instruction: 'Name one right.', task: 'Education' }, quiz: [{ question: 'Which is a right?', options: ['To play', 'To work hard', 'To be sad'], correctOption: 0 }], rewardPoints: 25 },
  { title: 'Our Duties', level: 'Primary 4', intro: '🎥 Animation: Cleaning street!', content: 'Duties: Obey laws, pay taxes, protect public property.', practice: { instruction: 'Name one duty.', task: 'Obey laws' }, quiz: [{ question: 'Is paying tax a duty?', options: ['Yes', 'No'], correctOption: 0 }], rewardPoints: 25 },
  { title: 'Traffic Rules', level: 'Primary 4', intro: '🎥 Animation: Traffic light!', content: 'Red (Stop), Yellow (Wait), Green (Go). Use zebra crossings.', practice: { instruction: 'What does Red mean?', task: 'Stop' }, quiz: [{ question: 'Where to cross road?', options: ['Anywhere', 'Zebra crossing', 'Corner'], correctOption: 1 }], rewardPoints: 25 },
  // Primary 5
  { title: 'The Constitution', level: 'Primary 5', intro: '🎥 Animation: Law book!', content: 'The highest law. It tells us how the country is run.', practice: { instruction: 'What is highest law?', task: 'Constitution' }, quiz: [{ question: 'Does it protect us?', options: ['Yes', 'No'], correctOption: 0 }], rewardPoints: 30 },
  { title: 'Local Government', level: 'Primary 5', intro: '🎥 Animation: LG office!', content: 'Provides markets, local roads, and health centers. Led by Chairman.', practice: { instruction: 'Who leads LG?', task: 'Chairman' }, quiz: [{ question: 'LG service:', options: ['Markets', 'Army', 'Airports'], correctOption: 0 }], rewardPoints: 30 },
  { title: 'State Government', level: 'Primary 5', intro: '🎥 Animation: State house!', content: 'Led by the Governor. Provides state roads, schools, and hospitals.', practice: { instruction: 'Who leads a state?', task: 'Governor' }, quiz: [{ question: 'Is Governor a leader?', options: ['Yes', 'No'], correctOption: 0 }], rewardPoints: 30 },
  // Primary 6
  { title: 'Democracy', level: 'Primary 6', intro: '🎥 Animation: Voting!', content: 'Government by the people. We choose leaders by voting.', practice: { instruction: 'How to choose leaders?', task: 'Voting' }, quiz: [{ question: 'Voting age?', options: ['16', '18', '21'], correctOption: 1 }], rewardPoints: 40 },
  { title: 'The Rule of Law', level: 'Primary 6', intro: '🎥 Animation: Judge!', content: 'Everyone must obey the law. No one is above it.', practice: { instruction: 'Who obeys law?', task: 'Everyone' }, quiz: [{ question: 'Is anyone above law?', options: ['Yes', 'No'], correctOption: 1 }], rewardPoints: 45 },
  { title: 'Federal Government', level: 'Primary 6', intro: '🎥 Animation: Aso Rock!', content: 'Led by the President. Manages the whole country, army, and money.', practice: { instruction: 'Who leads Nigeria?', task: 'President' }, quiz: [{ question: 'Where is the capital?', options: ['Lagos', 'Abuja', 'Kano'], correctOption: 1 }], rewardPoints: 45 }
];
