export const PRIMARY_4_ENGLISH_POOL = [
  // Verbs: Present and Past (Regular and Irregular)
  { topic: "Verbs: Present and Past", question: "What is the past tense of 'Go'?", options: ["Goes", "Went", "Gone"], correctOption: 1, explanation: "'Went' is the irregular past tense of 'go'." },
  { topic: "Verbs: Present and Past", question: "What is the past tense of 'Eat'?", options: ["Eats", "Eated", "Ate"], correctOption: 2, explanation: "'Ate' is the irregular past tense of 'eat'." },
  { topic: "Verbs: Present and Past", question: "What is the past tense of 'Run'?", options: ["Ran", "Running", "Runs"], correctOption: 0, explanation: "'Ran' is the irregular past tense of 'run'." },
  { topic: "Verbs: Present and Past", question: "Identify the past tense verb: 'She sang a song.'", options: ["She", "Sang", "Song"], correctOption: 1, explanation: "'Sang' is the past tense of 'sing'." },
  { topic: "Verbs: Present and Past", question: "What is the past tense of 'Write'?", options: ["Writes", "Wrote", "Written"], correctOption: 1, explanation: "'Wrote' is the past tense of 'write'." },
  { topic: "Verbs: Present and Past", question: "What is the past tense of 'Buy'?", options: ["Buys", "Bought", "Buyed"], correctOption: 1, explanation: "'Bought' is the past tense of 'buy'." },
  { topic: "Verbs: Present and Past", question: "What is the past tense of 'Sleep'?", options: ["Sleeps", "Slept", "Sleeped"], correctOption: 1, explanation: "'Slept' is the past tense of 'sleep'." },
  { topic: "Verbs: Present and Past", question: "What is the past tense of 'Drink'?", options: ["Drank", "Drinks", "Drunk"], correctOption: 0, explanation: "'Drank' is the past tense of 'drink'." },
  { topic: "Verbs: Present and Past", question: "What is the past tense of 'Speak'?", options: ["Speaks", "Spoke", "Spoken"], correctOption: 1, explanation: "'Spoke' is the past tense of 'speak'." },
  { topic: "Verbs: Present and Past", question: "What is the past tense of 'Take'?", options: ["Takes", "Took", "Taken"], correctOption: 1, explanation: "'Took' is the past tense of 'take'." },

  // Adverbs of Manner
  { topic: "Adverbs of Manner", question: "Which word is an adverb?", options: ["Quickly", "Quick", "Quicker"], correctOption: 0, explanation: "Adverbs of manner often end in -ly." },
  { topic: "Adverbs of Manner", question: "Identify the adverb: 'He ran fast.'", options: ["He", "Ran", "Fast"], correctOption: 2, explanation: "'Fast' describes how he ran." },
  { topic: "Adverbs of Manner", question: "Which adverb describes how someone speaks softly?", options: ["Loudly", "Softly", "Quiet"], correctOption: 1, explanation: "'Softly' describes the manner of speaking." },
  { topic: "Adverbs of Manner", question: "Identify the adverb: 'She smiled happily.'", options: ["She", "Smiled", "Happily"], correctOption: 2, explanation: "'Happily' describes how she smiled." },
  { topic: "Adverbs of Manner", question: "Which word is an adverb of manner?", options: ["Slowly", "Slow", "Slowness"], correctOption: 0, explanation: "'Slowly' tells us how an action is done." },
  { topic: "Adverbs of Manner", question: "Identify the adverb: 'The turtle moves slowly.'", options: ["Turtle", "Moves", "Slowly"], correctOption: 2, explanation: "'Slowly' describes the movement." },
  { topic: "Adverbs of Manner", question: "Which adverb means 'in a brave way'?", options: ["Bravery", "Brave", "Bravely"], correctOption: 2, explanation: "'Bravely' is the adverb form." },
  { topic: "Adverbs of Manner", question: "Identify the adverb: 'They played quietly.'", options: ["They", "Played", "Quietly"], correctOption: 2, explanation: "'Quietly' describes how they played." },
  { topic: "Adverbs of Manner", question: "Which word is an adverb?", options: ["Carefully", "Careful", "Caring"], correctOption: 0, explanation: "'Carefully' is an adverb." },
  { topic: "Adverbs of Manner", question: "Identify the adverb: 'He shouted loudly.'", options: ["He", "Shouted", "Loudly"], correctOption: 2, explanation: "'Loudly' describes the shouting." },

  // Prepositions of Place and Time
  { topic: "Prepositions of Place and Time", question: "The book is ___ the table.", options: ["on", "at", "to"], correctOption: 0, explanation: "'On' indicates position on a surface." },
  { topic: "Prepositions of Place and Time", question: "We go to school ___ the morning.", options: ["on", "in", "at"], correctOption: 1, explanation: "Use 'in' for parts of the day." },
  { topic: "Prepositions of Place and Time", question: "The cat is hiding ___ the bed.", options: ["under", "on", "in"], correctOption: 0, explanation: "'Under' indicates position below." },
  { topic: "Prepositions of Place and Time", question: "My birthday is ___ June.", options: ["on", "in", "at"], correctOption: 1, explanation: "Use 'in' for months." },
  { topic: "Prepositions of Place and Time", question: "The ball is ___ the two boxes.", options: ["between", "among", "in"], correctOption: 0, explanation: "'Between' is used for two things." },
  { topic: "Prepositions of Place and Time", question: "We have lunch ___ noon.", options: ["on", "in", "at"], correctOption: 2, explanation: "Use 'at' for specific times." },
  { topic: "Prepositions of Place and Time", question: "The bird flew ___ the house.", options: ["over", "under", "in"], correctOption: 0, explanation: "'Over' means above something." },
  { topic: "Prepositions of Place and Time", question: "I will see you ___ Monday.", options: ["on", "in", "at"], correctOption: 0, explanation: "Use 'on' for days of the week." },
  { topic: "Prepositions of Place and Time", question: "The keys are ___ my pocket.", options: ["on", "in", "at"], correctOption: 1, explanation: "'In' indicates being inside." },
  { topic: "Prepositions of Place and Time", question: "The movie starts ___ 7 o'clock.", options: ["on", "in", "at"], correctOption: 2, explanation: "Use 'at' for time." },

  // Conjunctions (And, But, Or, Because, So)
  { topic: "Conjunctions: Because and So", question: "I like tea ___ I don't like coffee.", options: ["and", "but", "or"], correctOption: 1, explanation: "Use 'but' for contrast." },
  { topic: "Conjunctions: Because and So", question: "I stayed home ___ it was raining.", options: ["because", "so", "but"], correctOption: 0, explanation: "Use 'because' to give a reason." },
  { topic: "Conjunctions: Because and So", question: "Do you want an apple ___ an orange?", options: ["and", "but", "or"], correctOption: 2, explanation: "Use 'or' for choices." },
  { topic: "Conjunctions: Because and So", question: "It was cold, ___ I wore a coat.", options: ["because", "so", "but"], correctOption: 1, explanation: "Use 'so' to show a result." },
  { topic: "Conjunctions: Because and So", question: "I have a brother ___ a sister.", options: ["and", "but", "or"], correctOption: 0, explanation: "Use 'and' to join similar items." },
  { topic: "Conjunctions: Because and So", question: "He is small ___ he is very strong.", options: ["and", "but", "or"], correctOption: 1, explanation: "Use 'but' for contrast." },
  { topic: "Conjunctions: Because and So", question: "I am hungry ___ I will eat.", options: ["because", "so", "but"], correctOption: 1, explanation: "Use 'so' for result." },
  { topic: "Conjunctions: Because and So", question: "She is crying ___ she lost her toy.", options: ["because", "so", "but"], correctOption: 0, explanation: "Use 'because' for reason." },
  { topic: "Conjunctions: Because and So", question: "Is it a cat ___ a dog?", options: ["and", "but", "or"], correctOption: 2, explanation: "Use 'or' for choice." },
  { topic: "Conjunctions: Because and So", question: "I studied hard, ___ I passed the test.", options: ["because", "so", "but"], correctOption: 1, explanation: "Use 'so' for result." },

  // Tenses: Future (using 'will')
  { topic: "Future Tense: Will", question: "Which sentence is in the future tense?", options: ["I go.", "I went.", "I will go."], correctOption: 2, explanation: "'Will' indicates future action." },
  { topic: "Future Tense: Will", question: "Tomorrow, it ___ rain.", options: ["is", "was", "will"], correctOption: 2, explanation: "Use 'will' for future predictions." },
  { topic: "Future Tense: Will", question: "I ___ help you later.", options: ["will", "am", "was"], correctOption: 0, explanation: "'Will' is used for future promises." },
  { topic: "Future Tense: Will", question: "They ___ arrive soon.", options: ["will", "are", "were"], correctOption: 0, explanation: "'Will' indicates future." },
  { topic: "Future Tense: Will", question: "She ___ be ten next year.", options: ["is", "was", "will"], correctOption: 2, explanation: "Future state." },
  { topic: "Future Tense: Will", question: "We ___ play football on Saturday.", options: ["will", "do", "did"], correctOption: 0, explanation: "Future plan." },
  { topic: "Future Tense: Will", question: "I think he ___ win the race.", options: ["will", "is", "was"], correctOption: 0, explanation: "Future prediction." },
  { topic: "Future Tense: Will", question: "The train ___ leave at 5 PM.", options: ["will", "is", "was"], correctOption: 0, explanation: "Scheduled future event." },
  { topic: "Future Tense: Will", question: "I ___ call you tonight.", options: ["will", "am", "was"], correctOption: 0, explanation: "Future intention." },
  { topic: "Future Tense: Will", question: "It ___ be sunny tomorrow.", options: ["will", "is", "was"], correctOption: 0, explanation: "Future weather." },

  // Direct Speech (basic)
  { topic: "Direct Speech", question: "Which sentence uses correct quotation marks?", options: ["He said, I am happy.", "He said, 'I am happy.'", "He said, I am happy'"], correctOption: 1, explanation: "Direct speech needs quotation marks." },
  { topic: "Direct Speech", question: "Where does the comma go? He said ___ 'Hello.'", options: ["before", "after", "none"], correctOption: 0, explanation: "A comma usually precedes the quotation." },
  { topic: "Direct Speech", question: "Which is correct?", options: ["'Stop!' she shouted.", "Stop! she shouted.", "'Stop! she shouted'"], correctOption: 0, explanation: "Quotation marks enclose the spoken words." },
  { topic: "Direct Speech", question: "Identify the spoken words: John asked, 'Where is my book?'", options: ["John asked", "Where is my book?", "Where"], correctOption: 1, explanation: "The words inside the marks are spoken." },
  { topic: "Direct Speech", question: "Which sentence is correct?", options: ["'I am hungry', said Tom.", "I am hungry, said Tom.", "'I am hungry' said Tom."], correctOption: 0, explanation: "Correct punctuation for direct speech." },
  { topic: "Direct Speech", question: "What is missing? 'How are you?' ___ asked.", options: ["he", "He", "he."], correctOption: 1, explanation: "Capitalize the speaker's name or pronoun if it starts the sentence part." },
  { topic: "Direct Speech", question: "Which is correct?", options: ["She said, 'I love cake.'", "She said 'I love cake'.", "She said, I love cake."], correctOption: 0, explanation: "Standard direct speech format." },
  { topic: "Direct Speech", question: "Identify the speaker: 'Come here,' called Mother.", options: ["Come here", "Mother", "Called"], correctOption: 1, explanation: "Mother is the one speaking." },
  { topic: "Direct Speech", question: "Which is correct?", options: ["'Wait for me!'", "Wait for me!", "'Wait for me'!"], correctOption: 0, explanation: "Exclamation mark inside the quotes." },
  { topic: "Direct Speech", question: "What are the marks called: ' ' ?", options: ["Full stops", "Quotation marks", "Commas"], correctOption: 1, explanation: "They are quotation or speech marks." },

  // Nouns: Collective and Abstract
  { topic: "Nouns: Collective and Abstract", question: "What is a collective noun for a group of lions?", options: ["Flock", "Pride", "Herd"], correctOption: 1, explanation: "A 'pride' of lions." },
  { topic: "Nouns: Collective and Abstract", question: "What is a collective noun for a group of birds?", options: ["Flock", "School", "Pack"], correctOption: 0, explanation: "A 'flock' of birds." },
  { topic: "Nouns: Collective and Abstract", question: "Which word is an abstract noun?", options: ["Table", "Happiness", "Dog"], correctOption: 1, explanation: "Abstract nouns are feelings or ideas." },
  { topic: "Nouns: Collective and Abstract", question: "What is a collective noun for a group of fish?", options: ["Herd", "School", "Flock"], correctOption: 1, explanation: "A 'school' of fish." },
  { topic: "Nouns: Collective and Abstract", question: "Which word is an abstract noun?", options: ["Brave", "Bravery", "Soldier"], correctOption: 1, explanation: "'Bravery' is an abstract noun." },
  { topic: "Nouns: Collective and Abstract", question: "What is a collective noun for a group of wolves?", options: ["Pack", "Herd", "Swarm"], correctOption: 0, explanation: "A 'pack' of wolves." },
  { topic: "Nouns: Collective and Abstract", question: "Which word is an abstract noun?", options: ["Love", "Rose", "Heart"], correctOption: 0, explanation: "'Love' is an abstract noun." },
  { topic: "Nouns: Collective and Abstract", question: "What is a collective noun for a group of bees?", options: ["Herd", "Swarm", "Flock"], correctOption: 1, explanation: "A 'swarm' of bees." },
  { topic: "Nouns: Collective and Abstract", question: "Which word is an abstract noun?", options: ["Friend", "Friendship", "House"], correctOption: 1, explanation: "'Friendship' is an abstract noun." },
  { topic: "Nouns: Collective and Abstract", question: "What is a collective noun for a group of cows?", options: ["Herd", "Pack", "School"], correctOption: 0, explanation: "A 'herd' of cows." },

  // Comparison of Adjectives (Comparative and Superlative)
  { topic: "Comparison of Adjectives", question: "What is the comparative of 'Big'?", options: ["Big", "Bigger", "Biggest"], correctOption: 1, explanation: "Comparative compares two things." },
  { topic: "Comparison of Adjectives", question: "What is the superlative of 'Small'?", options: ["Smaller", "Smallest", "Small"], correctOption: 1, explanation: "Superlative compares three or more." },
  { topic: "Comparison of Adjectives", question: "An elephant is ___ than a mouse.", options: ["big", "bigger", "biggest"], correctOption: 1, explanation: "Use comparative for two things." },
  { topic: "Comparison of Adjectives", question: "He is the ___ boy in the class.", options: ["tall", "taller", "tallest"], correctOption: 2, explanation: "Use superlative for the whole group." },
  { topic: "Comparison of Adjectives", question: "What is the comparative of 'Fast'?", options: ["Faster", "Fastest", "Fast"], correctOption: 0, explanation: "Fast -> Faster." },
  { topic: "Comparison of Adjectives", question: "This is the ___ book I have read.", options: ["good", "better", "best"], correctOption: 2, explanation: "Superlative of 'good' is 'best'." },
  { topic: "Comparison of Adjectives", question: "A car is ___ than a bicycle.", options: ["fast", "faster", "fastest"], correctOption: 1, explanation: "Comparative for two." },
  { topic: "Comparison of Adjectives", question: "What is the comparative of 'Happy'?", options: ["Happier", "Happiest", "Happy"], correctOption: 0, explanation: "Happy -> Happier." },
  { topic: "Comparison of Adjectives", question: "She is the ___ girl I know.", options: ["kind", "kinder", "kindest"], correctOption: 2, explanation: "Superlative for 'kind'." },
  { topic: "Comparison of Adjectives", question: "What is the comparative of 'Bad'?", options: ["Badder", "Worse", "Worst"], correctOption: 1, explanation: "Comparative of 'bad' is 'worse'." },

  // Pronouns: Possessive and Relative
  { topic: "Pronouns: Possessive and Relative", question: "Which is a possessive pronoun?", options: ["He", "His", "Him"], correctOption: 1, explanation: "'His' shows ownership." },
  { topic: "Pronouns: Possessive and Relative", question: "This book is ___.", options: ["me", "my", "mine"], correctOption: 2, explanation: "'Mine' is a possessive pronoun." },
  { topic: "Pronouns: Possessive and Relative", question: "The girl ___ is wearing red is my sister.", options: ["who", "which", "whose"], correctOption: 0, explanation: "Use 'who' for people." },
  { topic: "Pronouns: Possessive and Relative", question: "Is this bag ___?", options: ["you", "your", "yours"], correctOption: 2, explanation: "'Yours' is a possessive pronoun." },
  { topic: "Pronouns: Possessive and Relative", question: "The dog ___ barked is mine.", options: ["who", "that", "whose"], correctOption: 1, explanation: "Use 'that' or 'which' for animals/things." },
  { topic: "Pronouns: Possessive and Relative", question: "That house is ___.", options: ["them", "their", "theirs"], correctOption: 2, explanation: "'Theirs' is a possessive pronoun." },
  { topic: "Pronouns: Possessive and Relative", question: "The man ___ car was stolen is sad.", options: ["who", "whose", "which"], correctOption: 1, explanation: "Use 'whose' for possession." },
  { topic: "Pronouns: Possessive and Relative", question: "This is ___ pencil.", options: ["me", "my", "mine"], correctOption: 1, explanation: "'My' is a possessive adjective." },
  { topic: "Pronouns: Possessive and Relative", question: "The book ___ I read was good.", options: ["who", "which", "whose"], correctOption: 1, explanation: "Use 'which' for things." },
  { topic: "Pronouns: Possessive and Relative", question: "These toys are ___.", options: ["us", "our", "ours"], correctOption: 2, explanation: "'Ours' is a possessive pronoun." },

  // Punctuation: Quotation marks, Apostrophes
  { topic: "Punctuation: Marks", question: "Which shows possession (belonging)?", options: ["The boys", "The boy's", "The boys,"], correctOption: 1, explanation: "Apostrophe + s shows possession." },
  { topic: "Punctuation: Marks", question: "What is the contraction for 'Do not'?", options: ["Dont", "Don't", "Do'nt"], correctOption: 1, explanation: "Apostrophe replaces the missing letter." },
  { topic: "Punctuation: Marks", question: "Which is correct for 'The cat of Sarah'?", options: ["Sarahs cat", "Sarah's cat", "Sarahs' cat"], correctOption: 1, explanation: "Possessive apostrophe." },
  { topic: "Punctuation: Marks", question: "What is the contraction for 'I am'?", options: ["Im", "I'm", "I am"], correctOption: 1, explanation: "I'm." },
  { topic: "Punctuation: Marks", question: "Which shows plural possession (many boys)?", options: ["The boy's", "The boys's", "The boys'"], correctOption: 2, explanation: "Apostrophe after the 's' for plural." },
  { topic: "Punctuation: Marks", question: "What is the contraction for 'It is'?", options: ["Its", "It's", "Is't"], correctOption: 1, explanation: "It's." },
  { topic: "Punctuation: Marks", question: "Which is correct?", options: ["They're coming.", "Theyre coming.", "Theyr'e coming."], correctOption: 0, explanation: "They're (They are)." },
  { topic: "Punctuation: Marks", question: "What is the contraction for 'We are'?", options: ["Were", "We're", "Weare"], correctOption: 1, explanation: "We're." },
  { topic: "Punctuation: Marks", question: "Which shows possession?", options: ["The car's wheel", "The cars wheel", "The cars's wheel"], correctOption: 0, explanation: "Car's wheel." },
  { topic: "Punctuation: Marks", question: "What is the contraction for 'You are'?", options: ["Your", "You're", "Youre"], correctOption: 1, explanation: "You're." }
];
