export const PRIMARY_5_ENGLISH_POOL = [
  // Essay Structure
  { question: "Which part of an essay introduces the topic?", options: ["Body", "Conclusion", "Introduction"], correctOption: 2, explanation: "The introduction presents the main idea of the essay." },
  { question: "Where do you find the main details and arguments in an essay?", options: ["Introduction", "Body paragraphs", "Title"], correctOption: 1, explanation: "The body contains the detailed information." },
  { question: "Which part summarizes the main points of an essay?", options: ["Introduction", "Body", "Conclusion"], correctOption: 2, explanation: "The conclusion wraps up the essay." },
  { question: "What is the first sentence of a paragraph called?", options: ["Topic sentence", "Closing sentence", "Middle sentence"], correctOption: 0, explanation: "The topic sentence tells what the paragraph is about." },
  { question: "An essay should have at least ___ parts.", options: ["2", "3", "5"], correctOption: 1, explanation: "Introduction, Body, and Conclusion." },
  { question: "Which part of an essay should be the longest?", options: ["Introduction", "Body", "Conclusion"], correctOption: 1, explanation: "The body contains all the main details." },
  { question: "What is the purpose of a conclusion?", options: ["To start a new idea", "To summarize the essay", "To ask a question"], correctOption: 1, explanation: "It brings the essay to a close." },
  { question: "A good essay should be ___.", options: ["Messy", "Organized", "Too long"], correctOption: 1, explanation: "Organization is key to a good essay." },
  { question: "What do we call the main idea of an essay?", options: ["The Title", "The Thesis statement", "The Conclusion"], correctOption: 1, explanation: "The thesis statement expresses the main point." },
  { question: "Paragraphs in an essay should be ___.", options: ["Linked together", "Separated by colors", "Random"], correctOption: 0, explanation: "Paragraphs should flow logically." },

  // Direct and Indirect Speech
  { question: "Which sentence is in direct speech?", options: ["He said he was tired.", "'I am tired,' he said.", "He told me he is tired."], correctOption: 1, explanation: "Direct speech uses quotation marks." },
  { question: "Change to indirect: 'I am hungry,' said John.", options: ["John said I am hungry.", "John said that he was hungry.", "John says he is hungry."], correctOption: 1, explanation: "Indirect speech reports what was said." },
  { question: "In indirect speech, 'now' often changes to ___.", options: ["then", "today", "yesterday"], correctOption: 0, explanation: "Time words often change in reported speech." },
  { question: "Which is correct indirect speech for: 'I will go,' she said.", options: ["She said she will go.", "She said that she would go.", "She said I will go."], correctOption: 1, explanation: "'Will' changes to 'would' in indirect speech." },
  { question: "In indirect speech, 'tomorrow' often changes to ___.", options: ["the next day", "yesterday", "today"], correctOption: 0, explanation: "Tomorrow becomes the next day." },
  { question: "Which sentence uses correct punctuation for direct speech?", options: ["She asked, 'Where is it?'", "She asked 'Where is it.'", "She asked, Where is it?"], correctOption: 0, explanation: "Comma before quotes, question mark inside." },
  { question: "Change to indirect: 'We are playing,' they said.", options: ["They said they are playing.", "They said that they were playing.", "They said we were playing."], correctOption: 1, explanation: "'Are' changes to 'were' in past reporting." },
  { question: "In indirect speech, 'here' often changes to ___.", options: ["there", "where", "near"], correctOption: 0, explanation: "Here becomes there." },
  { question: "Which is direct speech?", options: ["He asked if I was okay.", "'Are you okay?' he asked.", "He wanted to know if I was okay."], correctOption: 1, explanation: "Uses quotation marks." },
  { question: "Change to indirect: 'I can swim,' said Mary.", options: ["Mary said she can swim.", "Mary said that she could swim.", "Mary said I could swim."], correctOption: 1, explanation: "'Can' changes to 'could'." },

  // Active and Passive Voice
  { question: "Which sentence is in the active voice?", options: ["The ball was kicked.", "The boy kicked the ball.", "The ball is being kicked."], correctOption: 1, explanation: "The subject (boy) performs the action." },
  { question: "Which sentence is in the passive voice?", options: ["She wrote a letter.", "A letter was written by her.", "She is writing a letter."], correctOption: 1, explanation: "The subject (letter) receives the action." },
  { question: "Change to passive: 'The cat chased the mouse.'", options: ["The mouse chased the cat.", "The mouse was chased by the cat.", "The cat was chasing the mouse."], correctOption: 1, explanation: "Object becomes the subject." },
  { question: "In passive voice, we often use the word ___.", options: ["and", "by", "but"], correctOption: 1, explanation: "'By' introduces the doer of the action." },
  { question: "Change to active: 'The cake was eaten by Tom.'", options: ["Tom eats the cake.", "Tom ate the cake.", "Tom was eating the cake."], correctOption: 1, explanation: "Tom becomes the subject." },
  { question: "Which is passive voice?", options: ["He built a house.", "A house was built.", "He is building."], correctOption: 1, explanation: "Focus is on the house." },
  { question: "Change to passive: 'They clean the room.'", options: ["The room is cleaned by them.", "The room was cleaned.", "They are cleaning."], correctOption: 0, explanation: "Present tense passive." },
  { question: "Which is active voice?", options: ["The song was sung.", "She sang the song.", "The song is sung by her."], correctOption: 1, explanation: "Subject performs the action." },
  { question: "Change to active: 'The window was broken by the wind.'", options: ["The wind breaks the window.", "The wind broke the window.", "The wind is breaking."], correctOption: 1, explanation: "Past tense active." },
  { question: "Passive voice focuses more on the ___.", options: ["Action/Object", "Subject", "Verb"], correctOption: 0, explanation: "It focuses on what happened to the object." },

  // Formal Letters
  { question: "A formal letter is usually written to ___.", options: ["A friend", "A principal or manager", "Your mother"], correctOption: 1, explanation: "Formal letters are for official business." },
  { question: "How many addresses does a formal letter have?", options: ["One", "Two", "None"], correctOption: 1, explanation: "The writer's address and the receiver's address." },
  { question: "Which is a formal way to start a letter to someone you don't know?", options: ["Hey there,", "Dear Sir/Madam,", "Hi friend,"], correctOption: 1, explanation: "Standard formal greeting." },
  { question: "What is the 'Subject' line in a formal letter for?", options: ["To say hello", "To tell what the letter is about", "To write your name"], correctOption: 1, explanation: "It summarizes the purpose of the letter." },
  { question: "Which is a formal way to end a letter?", options: ["Yours faithfully,", "See ya,", "Bye for now,"], correctOption: 0, explanation: "Standard formal closing." },
  { question: "Where does the date go in a formal letter?", options: ["At the bottom", "Below the writer's address", "In the middle"], correctOption: 1, explanation: "Usually below the first address." },
  { question: "A formal letter should have a ___ tone.", options: ["Funny", "Polite and official", "Angry"], correctOption: 1, explanation: "Maintain professionalism." },
  { question: "Which part comes after the greeting in a formal letter?", options: ["The Subject", "The Body", "The Conclusion"], correctOption: 0, explanation: "The subject line usually follows the greeting." },
  { question: "When do you use 'Yours sincerely'?", options: ["When you don't know the name", "When you know the name of the person", "To a friend"], correctOption: 1, explanation: "Used when the recipient's name is known." },
  { question: "A formal letter is also called an ___ letter.", options: ["Official", "Informal", "Friendly"], correctOption: 0, explanation: "It's used for official purposes." },

  // Synonyms and Antonyms (Advanced)
  { question: "What is a synonym for 'Courageous'?", options: ["Scared", "Brave", "Weak"], correctOption: 1, explanation: "Both mean having courage." },
  { question: "What is an antonym for 'Ancient'?", options: ["Old", "Modern", "Historic"], correctOption: 1, explanation: "Modern is the opposite of ancient." },
  { question: "What is a synonym for 'Fragile'?", options: ["Strong", "Delicate", "Heavy"], correctOption: 1, explanation: "Both mean easily broken." },
  { question: "What is an antonym for 'Generous'?", options: ["Kind", "Selfish", "Giving"], correctOption: 1, explanation: "Selfish is the opposite of generous." },
  { question: "What is a synonym for 'Abundant'?", options: ["Plentiful", "Scarce", "Small"], correctOption: 0, explanation: "Both mean having a lot of something." },
  { question: "What is an antonym for 'Victory'?", options: ["Win", "Defeat", "Success"], correctOption: 1, explanation: "Defeat is the opposite of victory." },
  { question: "What is a synonym for 'Enormous'?", options: ["Tiny", "Huge", "Thin"], correctOption: 1, explanation: "Both mean very large." },
  { question: "What is an antonym for 'Arrive'?", options: ["Come", "Depart", "Reach"], correctOption: 1, explanation: "Depart (leave) is the opposite of arrive." },
  { question: "What is a synonym for 'Wealthy'?", options: ["Poor", "Rich", "Broke"], correctOption: 1, explanation: "Both mean having a lot of money." },
  { question: "What is an antonym for 'Difficult'?", options: ["Hard", "Easy", "Complex"], correctOption: 1, explanation: "Easy is the opposite of difficult." },

  // Tenses: Perfect Tenses
  { question: "Which sentence is in the Present Perfect tense?", options: ["I go.", "I have gone.", "I went."], correctOption: 1, explanation: "Uses 'have/has' + past participle." },
  { question: "She ___ finished her homework.", options: ["have", "has", "is"], correctOption: 1, explanation: "Use 'has' for she/he/it." },
  { question: "Which is the past participle of 'Eat'?", options: ["Ate", "Eaten", "Eating"], correctOption: 1, explanation: "Eat, Ate, Eaten." },
  { question: "They ___ lived here for ten years.", options: ["has", "have", "are"], correctOption: 1, explanation: "Use 'have' for they/we/you/I." },
  { question: "Which sentence is in the Past Perfect tense?", options: ["I had eaten.", "I have eaten.", "I was eating."], correctOption: 0, explanation: "Uses 'had' + past participle." },
  { question: "By the time I arrived, the bus ___ left.", options: ["has", "had", "is"], correctOption: 1, explanation: "Past perfect for an action before another past action." },
  { question: "I ___ never seen that movie before.", options: ["has", "have", "had"], correctOption: 1, explanation: "Present perfect experience." },
  { question: "Which is the past participle of 'Write'?", options: ["Wrote", "Written", "Writing"], correctOption: 1, explanation: "Write, Wrote, Written." },
  { question: "He ___ already left when I called.", options: ["has", "had", "was"], correctOption: 1, explanation: "Past perfect." },
  { question: "We ___ finished the project.", options: ["have", "has", "had"], correctOption: 0, explanation: "Present perfect." },

  // Modals (Can, Could, May, Might, Should, Must)
  { question: "Which modal shows ability?", options: ["Should", "Can", "Must"], correctOption: 1, explanation: "'Can' shows what you are able to do." },
  { question: "Which modal shows a strong obligation (something you have to do)?", options: ["Might", "Must", "May"], correctOption: 1, explanation: "'Must' shows necessity." },
  { question: "You ___ brush your teeth every day.", options: ["should", "might", "could"], correctOption: 0, explanation: "'Should' is used for advice." },
  { question: "___ I come in?", options: ["Must", "May", "Should"], correctOption: 1, explanation: "'May' is used for asking permission." },
  { question: "It ___ rain today, so take an umbrella.", options: ["must", "might", "should"], correctOption: 1, explanation: "'Might' shows possibility." },
  { question: "When I was young, I ___ run fast.", options: ["can", "could", "must"], correctOption: 1, explanation: "'Could' is the past of 'can' for ability." },
  { question: "You ___ not steal.", options: ["must", "might", "could"], correctOption: 0, explanation: "Prohibition." },
  { question: "___ you help me with this box?", options: ["Must", "Could", "Should"], correctOption: 1, explanation: "Polite request." },
  { question: "He ___ be at home; his car is there.", options: ["must", "might", "should"], correctOption: 0, explanation: "Strong probability." },
  { question: "We ___ respect our elders.", options: ["should", "might", "could"], correctOption: 0, explanation: "Advice/Duty." },

  // Relative Clauses (Who, Which, That, Whose)
  { question: "The man ___ lives next door is a doctor.", options: ["which", "who", "whose"], correctOption: 1, explanation: "Use 'who' for people." },
  { question: "The book ___ I bought is interesting.", options: ["who", "which", "whose"], correctOption: 1, explanation: "Use 'which' or 'that' for things." },
  { question: "The girl ___ bag was lost is crying.", options: ["who", "which", "whose"], correctOption: 2, explanation: "Use 'whose' for possession." },
  { question: "This is the house ___ Jack built.", options: ["who", "that", "whose"], correctOption: 1, explanation: "Use 'that' for things." },
  { question: "The teacher ___ taught us was kind.", options: ["who", "which", "whose"], correctOption: 0, explanation: "Use 'who' for people." },
  { question: "The dog ___ barked is mine.", options: ["who", "that", "whose"], correctOption: 1, explanation: "Use 'that' for animals." },
  { question: "The car ___ color is red is fast.", options: ["who", "which", "whose"], correctOption: 2, explanation: "Use 'whose' for possession." },
  { question: "The cake ___ she made was delicious.", options: ["who", "which", "whose"], correctOption: 1, explanation: "Use 'which' for things." },
  { question: "The people ___ work here are friendly.", options: ["who", "which", "whose"], correctOption: 0, explanation: "Use 'who' for people." },
  { question: "The tree ___ leaves are falling is an oak.", options: ["who", "which", "whose"], correctOption: 2, explanation: "Use 'whose' for possession." },

  // Idioms and Proverbs
  { question: "What does 'A piece of cake' mean?", options: ["A slice of food", "Something very easy", "A difficult task"], correctOption: 1, explanation: "Idiom for something easy." },
  { question: "What does 'Under the weather' mean?", options: ["Standing in the rain", "Feeling sick", "Being outside"], correctOption: 1, explanation: "Idiom for feeling unwell." },
  { question: "What does 'Once in a blue moon' mean?", options: ["Every night", "Very rarely", "When the moon is blue"], correctOption: 1, explanation: "Idiom for something that rarely happens." },
  { question: "What does 'Break a leg' mean?", options: ["To get hurt", "Good luck", "To fall down"], correctOption: 1, explanation: "Idiom used to wish someone luck, especially in performance." },
  { question: "What does 'Cost an arm and a leg' mean?", options: ["To be very expensive", "To be cheap", "To lose a limb"], correctOption: 0, explanation: "Idiom for very high price." },
  { question: "What does 'Better late than never' mean?", options: ["Don't come at all", "It's better to arrive late than not at all", "Always be late"], correctOption: 1, explanation: "A common proverb." },
  { question: "What does 'A friend in need is a friend indeed' mean?", options: ["Friends only help when they need something", "A true friend helps you when you have a problem", "Friends are not important"], correctOption: 1, explanation: "A proverb about true friendship." },
  { question: "What does 'Actions speak louder than words' mean?", options: ["Shouting is good", "What you do is more important than what you say", "Talking is better than doing"], correctOption: 1, explanation: "A proverb about behavior." },
  { question: "What does 'Don't judge a book by its cover' mean?", options: ["Don't look at books", "Don't judge something only by its appearance", "Only buy pretty books"], correctOption: 1, explanation: "A proverb about looking deeper." },
  { question: "What does 'Hit the nail on the head' mean?", options: ["To use a hammer", "To describe exactly what is causing a situation", "To hurt yourself"], correctOption: 1, explanation: "Idiom for being exactly right." },

  // Mixed Grammar Review
  { question: "Which is the correct spelling?", options: ["Receive", "Recieve", "Receve"], correctOption: 0, explanation: "I before E except after C." },
  { question: "Identify the adverb: 'He spoke quite loudly.'", options: ["Spoke", "Quite", "Loudly"], correctOption: 2, explanation: "Loudly describes the speaking." },
  { question: "Which is a collective noun for a group of students?", options: ["Class", "Team", "Pack"], correctOption: 0, explanation: "A class of students." },
  { question: "What is the plural of 'Child'?", options: ["Childs", "Children", "Childrens"], correctOption: 1, explanation: "Irregular plural." },
  { question: "Which is a conjunction?", options: ["Although", "Happy", "Run"], correctOption: 0, explanation: "Although joins clauses." },
  { question: "Identify the preposition: 'The cat jumped over the fence.'", options: ["Cat", "Jumped", "Over"], correctOption: 2, explanation: "Over shows the relation of place." },
  { question: "What is the past tense of 'Fly'?", options: ["Flies", "Flew", "Flown"], correctOption: 1, explanation: "Fly, Flew, Flown." },
  { question: "Which is an abstract noun?", options: ["Freedom", "Bird", "Cloud"], correctOption: 0, explanation: "Freedom is an idea." },
  { question: "Identify the adjective: 'The mysterious man left.'", options: ["Mysterious", "Man", "Left"], correctOption: 0, explanation: "Mysterious describes the man." },
  { question: "Which is correct?", options: ["Its a sunny day.", "It's a sunny day.", "Its' a sunny day."], correctOption: 1, explanation: "It's = It is." }
];
