export const PRIMARY_3_ENGLISH_POOL = [
  // Nouns: Common and Proper
  { topic: "Nouns: Common and Proper", question: "Which of these is a proper noun?", options: ["city", "London", "boy"], correctOption: 1, explanation: "London is a specific name of a city." },
  { topic: "Nouns: Common and Proper", question: "A noun is a name of a person, place, or ___.", options: ["action", "thing", "color"], correctOption: 1, explanation: "Nouns are names of people, places, or things." },
  { topic: "Nouns: Common and Proper", question: "Which word is a common noun?", options: ["Nigeria", "Country", "Lagos"], correctOption: 1, explanation: "Country is a general name." },
  { topic: "Nouns: Common and Proper", question: "Proper nouns always start with a ___ letter.", options: ["small", "capital", "fancy"], correctOption: 1, explanation: "Specific names start with capital letters." },
  { topic: "Nouns: Common and Proper", question: "Identify the proper noun: 'My dog is named Bingo.'", options: ["Dog", "Bingo", "My"], correctOption: 1, explanation: "Bingo is the specific name of the dog." },
  { topic: "Nouns: Common and Proper", question: "Which is a common noun for a place?", options: ["Market", "Abuja", "Shoprite"], correctOption: 0, explanation: "Market is a general name for a place." },
  { topic: "Nouns: Common and Proper", question: "Which is a proper noun for a person?", options: ["Teacher", "Mr. John", "Doctor"], correctOption: 1, explanation: "Mr. John is a specific name." },
  { topic: "Nouns: Common and Proper", question: "Identify the common noun: 'The car is red.'", options: ["Car", "Red", "The"], correctOption: 0, explanation: "Car is a thing." },
  { topic: "Nouns: Common and Proper", question: "Which of these is NOT a noun?", options: ["Table", "Run", "School"], correctOption: 1, explanation: "Run is a verb (action)." },
  { topic: "Nouns: Common and Proper", question: "Proper nouns are names of ___ people or places.", options: ["general", "specific", "all"], correctOption: 1, explanation: "They name specific things." },

  // Punctuation Marks
  { topic: "Punctuation: Marks", question: "Which mark goes at the end of a question?", options: [".", "?", ","], correctOption: 1, explanation: "Use a question mark (?) for questions." },
  { topic: "Punctuation: Marks", question: "Which mark is used to separate items in a list?", options: [".", "?", ","], correctOption: 2, explanation: "Use a comma (,) to separate items." },
  { topic: "Punctuation: Marks", question: "Which mark goes at the end of a telling sentence?", options: [".", "?", "!"], correctOption: 0, explanation: "Use a full stop (.) at the end." },
  { topic: "Punctuation: Marks", question: "Which sentence is punctuated correctly?", options: ["where are you.", "Where are you?", "where are you?"], correctOption: 1, explanation: "Starts with a capital and ends with a question mark." },
  { topic: "Punctuation: Marks", question: "Where does the comma go? 'I like apples pears and grapes.'", options: ["After apples", "After pears", "After grapes"], correctOption: 0, explanation: "I like apples, pears and grapes." },
  { topic: "Punctuation: Marks", question: "Which mark shows strong feeling or excitement?", options: [".", "?", "!"], correctOption: 2, explanation: "Use an exclamation mark (!) for excitement." },
  { topic: "Punctuation: Marks", question: "Which sentence is correct?", options: ["i am happy.", "I am happy.", "I am happy"], correctOption: 1, explanation: "Capital letter and full stop." },
  { topic: "Punctuation: Marks", question: "What is missing? 'He said hello'", options: ["Full stop", "Question mark", "Comma"], correctOption: 0, explanation: "It needs a full stop at the end." },
  { topic: "Punctuation: Marks", question: "Which is used for a pause in a sentence?", options: [".", "?", ","], correctOption: 2, explanation: "A comma provides a short pause." },
  { topic: "Punctuation: Marks", question: "A sentence always starts with a ___ letter.", options: ["small", "capital", "big"], correctOption: 1, explanation: "Always start with a capital letter." },

  // Pronouns
  { topic: "Pronouns", question: "Which pronoun replaces 'The boy'?", options: ["She", "He", "It"], correctOption: 1, explanation: "Use 'He' for a boy." },
  { topic: "Pronouns", question: "Which pronoun replaces 'Sarah'?", options: ["He", "She", "It"], correctOption: 1, explanation: "Use 'She' for a girl." },
  { topic: "Pronouns", question: "Which pronoun replaces 'The book'?", options: ["He", "She", "It"], correctOption: 2, explanation: "Use 'It' for a thing." },
  { topic: "Pronouns", question: "Which pronoun replaces 'John and I'?", options: ["They", "We", "You"], correctOption: 1, explanation: "Use 'We' when including yourself." },
  { topic: "Pronouns", question: "Which pronoun replaces 'The children'?", options: ["We", "They", "He"], correctOption: 1, explanation: "Use 'They' for more than one person." },
  { topic: "Pronouns", question: "Identify the pronoun: 'She is my sister.'", options: ["She", "My", "Sister"], correctOption: 0, explanation: "She is the pronoun." },
  { topic: "Pronouns", question: "Which pronoun is used for yourself?", options: ["Me", "I", "You"], correctOption: 1, explanation: "Use 'I' as the subject." },
  { topic: "Pronouns", question: "Identify the pronoun: 'They are playing.'", options: ["They", "Are", "Playing"], correctOption: 0, explanation: "They is the pronoun." },
  { topic: "Pronouns", question: "Which pronoun replaces 'The cat'?", options: ["He", "She", "It"], correctOption: 2, explanation: "Use 'It' for animals." },
  { topic: "Pronouns", question: "Identify the pronoun: 'We love school.'", options: ["We", "Love", "School"], correctOption: 0, explanation: "We is the pronoun." },

  // Adjectives (Describing Words)
  { topic: "Adjectives", question: "Which word is an adjective?", options: ["Run", "Big", "Table"], correctOption: 1, explanation: "Big describes a noun." },
  { topic: "Adjectives", question: "Identify the adjective: 'The red car.'", options: ["The", "Red", "Car"], correctOption: 1, explanation: "Red describes the car." },
  { topic: "Adjectives", question: "Which adjective describes a person's feeling?", options: ["Happy", "Blue", "Fast"], correctOption: 0, explanation: "Happy describes a feeling." },
  { topic: "Adjectives", question: "Identify the adjective: 'A tall building.'", options: ["A", "Tall", "Building"], correctOption: 1, explanation: "Tall describes the building." },
  { topic: "Adjectives", question: "Which word describes a sound?", options: ["Loud", "Green", "Soft"], correctOption: 0, explanation: "Loud describes a sound." },
  { topic: "Adjectives", question: "Identify the adjective: 'The sweet orange.'", options: ["The", "Sweet", "Orange"], correctOption: 1, explanation: "Sweet describes the taste." },
  { topic: "Adjectives", question: "Which adjective describes a shape?", options: ["Round", "Bitter", "Slow"], correctOption: 0, explanation: "Round is a shape." },
  { topic: "Adjectives", question: "Identify the adjective: 'A small mouse.'", options: ["A", "Small", "Mouse"], correctOption: 1, explanation: "Small describes the size." },
  { topic: "Adjectives", question: "Which word describes a color?", options: ["Blue", "Fast", "High"], correctOption: 0, explanation: "Blue is a color." },
  { topic: "Adjectives", question: "Identify the adjective: 'The hot sun.'", options: ["The", "Hot", "Sun"], correctOption: 1, explanation: "Hot describes the temperature." },

  // Verbs: Action (Present and Past)
  { topic: "Verbs: Action", question: "Which is a verb?", options: ["Jump", "Cat", "Red"], correctOption: 0, explanation: "Jump is an action." },
  { topic: "Verbs: Action", question: "What is the past tense of 'Walk'?", options: ["Walking", "Walks", "Walked"], correctOption: 2, explanation: "Add -ed for past tense." },
  { topic: "Verbs: Action", question: "What is the past tense of 'Play'?", options: ["Played", "Playing", "Plays"], correctOption: 0, explanation: "Add -ed for past tense." },
  { topic: "Verbs: Action", question: "Identify the verb: 'He eats an apple.'", options: ["He", "Eats", "Apple"], correctOption: 1, explanation: "Eats is the action." },
  { topic: "Verbs: Action", question: "What is the past tense of 'Jump'?", options: ["Jumping", "Jumps", "Jumped"], correctOption: 2, explanation: "Add -ed for past tense." },
  { topic: "Verbs: Action", question: "Identify the verb: 'The dog barks.'", options: ["Dog", "Barks", "Loud"], correctOption: 1, explanation: "Barks is the action." },
  { topic: "Verbs: Action", question: "What is the past tense of 'Cook'?", options: ["Cooked", "Cooking", "Cooks"], correctOption: 0, explanation: "Add -ed for past tense." },
  { topic: "Verbs: Action", question: "Identify the verb: 'We run fast.'", options: ["We", "Run", "Fast"], correctOption: 1, explanation: "Run is the action." },
  { topic: "Verbs: Action", question: "What is the past tense of 'Laugh'?", options: ["Laughing", "Laughed", "Laughs"], correctOption: 1, explanation: "Add -ed for past tense." },
  { topic: "Verbs: Action", question: "Identify the verb: 'She writes a letter.'", options: ["She", "Writes", "Letter"], correctOption: 1, explanation: "Writes is the action." },

  // Writing Sentences (Subject and Verb)
  { topic: "Writing Sentences", question: "A sentence needs a subject and a ___.", options: ["color", "verb", "adjective"], correctOption: 1, explanation: "A sentence needs an action (verb)." },
  { topic: "Writing Sentences", question: "Identify the subject: 'The boy runs.'", options: ["The", "Boy", "Runs"], correctOption: 1, explanation: "The boy is who the sentence is about." },
  { topic: "Writing Sentences", question: "Identify the verb: 'The bird sings.'", options: ["The", "Bird", "Sings"], correctOption: 2, explanation: "Sings is the action." },
  { topic: "Writing Sentences", question: "Which is a complete sentence?", options: ["I eat.", "Eat.", "I."], correctOption: 0, explanation: "It has a subject (I) and a verb (eat)." },
  { topic: "Writing Sentences", question: "Identify the subject: 'Sarah loves cake.'", options: ["Sarah", "Loves", "Cake"], correctOption: 0, explanation: "Sarah is the subject." },
  { topic: "Writing Sentences", question: "Identify the verb: 'We play games.'", options: ["We", "Play", "Games"], correctOption: 1, explanation: "Play is the action." },
  { topic: "Writing Sentences", question: "Which is a complete sentence?", options: ["The cat.", "The cat sleeps.", "Sleeps."], correctOption: 1, explanation: "It has a subject and a verb." },
  { topic: "Writing Sentences", question: "Identify the subject: 'The sun shines.'", options: ["The", "Sun", "Shines"], correctOption: 1, explanation: "The sun is the subject." },
  { topic: "Writing Sentences", question: "Identify the verb: 'I read books.'", options: ["I", "Read", "Books"], correctOption: 1, explanation: "Read is the action." },
  { topic: "Writing Sentences", question: "A sentence starts with a ___ letter.", options: ["small", "capital", "fancy"], correctOption: 1, explanation: "Always start with a capital." },

  // Synonyms and Antonyms
  { topic: "Synonyms and Antonyms", question: "What is a synonym for 'Big'?", options: ["Small", "Large", "Fast"], correctOption: 1, explanation: "Large means the same as big." },
  { topic: "Synonyms and Antonyms", question: "What is an antonym for 'Happy'?", options: ["Sad", "Glad", "Joyful"], correctOption: 0, explanation: "Sad is the opposite of happy." },
  { topic: "Synonyms and Antonyms", question: "What is a synonym for 'Quick'?", options: ["Slow", "Fast", "Heavy"], correctOption: 1, explanation: "Fast means the same as quick." },
  { topic: "Synonyms and Antonyms", question: "What is an antonym for 'Hot'?", options: ["Warm", "Cold", "Burning"], correctOption: 1, explanation: "Cold is the opposite of hot." },
  { topic: "Synonyms and Antonyms", question: "What is a synonym for 'Small'?", options: ["Tiny", "Huge", "Wide"], correctOption: 0, explanation: "Tiny means the same as small." },
  { topic: "Synonyms and Antonyms", question: "What is an antonym for 'Up'?", options: ["Down", "Left", "Right"], correctOption: 0, explanation: "Down is the opposite of up." },
  { topic: "Synonyms and Antonyms", question: "What is a synonym for 'Happy'?", options: ["Sad", "Glad", "Angry"], correctOption: 1, explanation: "Glad means the same as happy." },
  { topic: "Synonyms and Antonyms", question: "What is an antonym for 'Fast'?", options: ["Quick", "Slow", "Rapid"], correctOption: 1, explanation: "Slow is the opposite of fast." },
  { topic: "Synonyms and Antonyms", question: "What is a synonym for 'Hard'?", options: ["Soft", "Difficult", "Easy"], correctOption: 1, explanation: "Difficult can mean the same as hard." },
  { topic: "Synonyms and Antonyms", question: "What is an antonym for 'Clean'?", options: ["Dirty", "Neat", "Fresh"], correctOption: 0, explanation: "Dirty is the opposite of clean." },

  // Prepositions of Place
  { topic: "Prepositions of Place", question: "The cat is ___ the table.", options: ["in", "on", "at"], correctOption: 1, explanation: "On describes being on top of something." },
  { topic: "Prepositions of Place", question: "The ball is ___ the box.", options: ["under", "in", "between"], correctOption: 1, explanation: "In describes being inside something." },
  { topic: "Prepositions of Place", question: "The dog is sleeping ___ the bed.", options: ["under", "on", "at"], correctOption: 0, explanation: "Under describes being below something." },
  { topic: "Prepositions of Place", question: "The book is ___ the bag.", options: ["in", "on", "at"], correctOption: 0, explanation: "In describes being inside the bag." },
  { topic: "Prepositions of Place", question: "The bird is ___ the tree.", options: ["in", "on", "at"], correctOption: 0, explanation: "In the tree (among the branches)." },
  { topic: "Prepositions of Place", question: "The pen is ___ the desk.", options: ["on", "in", "at"], correctOption: 0, explanation: "On the desk." },
  { topic: "Prepositions of Place", question: "The shoes are ___ the door.", options: ["behind", "in", "on"], correctOption: 0, explanation: "Behind the door." },
  { topic: "Prepositions of Place", question: "The apple is ___ the plate.", options: ["on", "in", "at"], correctOption: 0, explanation: "On the plate." },
  { topic: "Prepositions of Place", question: "The boy is hiding ___ the curtain.", options: ["behind", "on", "in"], correctOption: 0, explanation: "Behind the curtain." },
  { topic: "Prepositions of Place", question: "The milk is ___ the fridge.", options: ["in", "on", "at"], correctOption: 0, explanation: "In the fridge." },

  // Conjunctions (And, But, Or)
  { topic: "Conjunctions", question: "I like apples ___ oranges.", options: ["and", "but", "or"], correctOption: 0, explanation: "Use 'and' to join similar things." },
  { topic: "Conjunctions", question: "I am tired ___ I am happy.", options: ["and", "but", "or"], correctOption: 1, explanation: "Use 'but' for different ideas." },
  { question: "Do you want tea ___ coffee?", options: ["and", "but", "or"], correctOption: 2, explanation: "Use 'or' for choices." },
  { question: "It is raining ___ I have an umbrella.", options: ["and", "but", "or"], correctOption: 1, explanation: "Use 'but' to show contrast." },
  { question: "I have a pen ___ a pencil.", options: ["and", "but", "or"], correctOption: 0, explanation: "Use 'and' to join items." },
  { question: "He is small ___ he is strong.", options: ["and", "but", "or"], correctOption: 1, explanation: "Use 'but' for contrast." },
  { question: "Is it red ___ blue?", options: ["and", "but", "or"], correctOption: 2, explanation: "Use 'or' for a choice." },
  { question: "I ran fast ___ I missed the bus.", options: ["and", "but", "or"], correctOption: 1, explanation: "Use 'but' for an unexpected result." },
  { question: "She likes to sing ___ dance.", options: ["and", "but", "or"], correctOption: 0, explanation: "Use 'and' to join actions." },
  { question: "Would you like a cat ___ a dog?", options: ["and", "but", "or"], correctOption: 2, explanation: "Use 'or' for a choice." },

  // Tenses (Simple Present and Simple Past)
  { question: "I ___ to school every day.", options: ["go", "went", "going"], correctOption: 0, explanation: "Simple present for daily habits." },
  { question: "Yesterday, I ___ to the park.", options: ["go", "went", "goes"], correctOption: 1, explanation: "Simple past for yesterday." },
  { question: "She ___ her breakfast now.", options: ["eat", "eats", "ate"], correctOption: 1, explanation: "Simple present for habits (she eats)." },
  { question: "Last night, we ___ a movie.", options: ["watch", "watched", "watching"], correctOption: 1, explanation: "Simple past for last night." },
  { question: "The sun ___ in the morning.", options: ["rise", "rises", "rose"], correctOption: 1, explanation: "Simple present for facts." },
  { question: "He ___ his homework an hour ago.", options: ["finish", "finished", "finishes"], correctOption: 1, explanation: "Simple past for 'ago'." },
  { question: "They ___ football on Saturdays.", options: ["play", "played", "plays"], correctOption: 0, explanation: "Simple present for habits." },
  { question: "I ___ my teeth this morning.", options: ["brush", "brushed", "brushes"], correctOption: 1, explanation: "Simple past for earlier today." },
  { question: "Birds ___ in the sky.", options: ["fly", "flies", "flew"], correctOption: 0, explanation: "Simple present for facts." },
  { question: "She ___ a song at the party yesterday.", options: ["sing", "sang", "sings"], correctOption: 1, explanation: "Simple past of 'sing' is 'sang'." }
];
