export const PRIMARY_2_MATH_POOL = [
  // Place Value: Tens and Units
  { topic: "Place Value: Tens and Units", question: "In the number 25, which digit is in the Tens place?", options: ["2", "5", "20"], correctOption: 0, explanation: "25 is 2 tens and 5 units." },
  { topic: "Place Value: Tens and Units", question: "What is the value of 4 in 43?", options: ["4", "40", "3"], correctOption: 1, explanation: "The 4 is in the tens place, so it means 40." },
  { topic: "Place Value: Tens and Units", question: "How many units are in 17?", options: ["1", "7", "10"], correctOption: 1, explanation: "17 is 1 ten and 7 units." },
  { topic: "Place Value: Tens and Units", question: "What number is 3 tens and 0 units?", options: ["3", "30", "33"], correctOption: 1, explanation: "3 tens is 30." },
  { topic: "Place Value: Tens and Units", question: "In 58, the 8 is in the ___ place.", options: ["Tens", "Units", "Hundreds"], correctOption: 1, explanation: "The last digit is the units place." },
  { topic: "Place Value: Tens and Units", question: "What is 20 + 7?", options: ["20", "27", "72"], correctOption: 1, explanation: "2 tens and 7 units make 27." },
  { topic: "Place Value: Tens and Units", question: "Which number has 6 tens?", options: ["16", "61", "6"], correctOption: 1, explanation: "61 has 6 in the tens place." },
  { topic: "Place Value: Tens and Units", question: "What is the value of the 9 in 90?", options: ["9", "90", "0"], correctOption: 1, explanation: "9 tens is 90." },
  { topic: "Place Value: Tens and Units", question: "How many tens are in 84?", options: ["8", "4", "80"], correctOption: 0, explanation: "84 has 8 tens." },
  { topic: "Place Value: Tens and Units", question: "What is 5 tens and 5 units?", options: ["10", "50", "55"], correctOption: 2, explanation: "5 tens (50) + 5 units = 55." },

  // Addition of 3 Numbers
  { topic: "Addition of 3 Numbers", question: "What is 20 + 30?", options: ["40", "50", "60"], correctOption: 1, explanation: "2 tens + 3 tens = 5 tens (50)." },
  { topic: "Addition of 3 Numbers", question: "What is 15 + 5?", options: ["10", "20", "25"], correctOption: 1, explanation: "15 plus 5 is 20." },
  { topic: "Addition of 3 Numbers", question: "What is 42 + 10?", options: ["42", "52", "62"], correctOption: 1, explanation: "Adding 10 increases the tens by 1." },
  { topic: "Addition of 3 Numbers", question: "What is 35 + 12?", options: ["45", "47", "57"], correctOption: 1, explanation: "35 + 10 = 45, then 45 + 2 = 47." },
  { topic: "Addition of 3 Numbers", question: "What is 50 + 50?", options: ["90", "100", "110"], correctOption: 1, explanation: "50 and 50 make 100." },
  { topic: "Addition of 3 Numbers", question: "What is 11 + 11?", options: ["20", "22", "24"], correctOption: 1, explanation: "11 + 11 = 22." },
  { topic: "Addition of 3 Numbers", question: "What is 60 + 5?", options: ["60", "65", "56"], correctOption: 1, explanation: "60 + 5 = 65." },
  { topic: "Addition of 3 Numbers", question: "What is 25 + 25?", options: ["40", "50", "60"], correctOption: 1, explanation: "25 + 25 = 50." },
  { topic: "Addition of 3 Numbers", question: "What is 80 + 10?", options: ["70", "90", "100"], correctOption: 1, explanation: "8 tens + 1 ten = 9 tens." },
  { topic: "Addition of 3 Numbers", question: "What is 14 + 6?", options: ["18", "20", "22"], correctOption: 1, explanation: "14 + 6 = 20." },

  // Subtraction with Borrowing
  { topic: "Subtraction with Borrowing", question: "What is 50 - 20?", options: ["20", "30", "40"], correctOption: 1, explanation: "5 tens - 2 tens = 3 tens (30)." },
  { topic: "Subtraction with Borrowing", question: "What is 25 - 5?", options: ["15", "20", "30"], correctOption: 1, explanation: "25 take away 5 is 20." },
  { topic: "Subtraction with Borrowing", question: "What is 40 - 10?", options: ["30", "20", "50"], correctOption: 0, explanation: "4 tens - 1 ten = 3 tens." },
  { topic: "Subtraction with Borrowing", question: "What is 18 - 9?", options: ["7", "8", "9"], correctOption: 2, explanation: "9 + 9 = 18, so 18 - 9 = 9." },
  { topic: "Subtraction with Borrowing", question: "What is 100 - 50?", options: ["40", "50", "60"], correctOption: 1, explanation: "Half of 100 is 50." },
  { topic: "Subtraction with Borrowing", question: "What is 33 - 3?", options: ["30", "33", "0"], correctOption: 0, explanation: "33 take away 3 is 30." },
  { topic: "Subtraction with Borrowing", question: "What is 75 - 10?", options: ["65", "70", "85"], correctOption: 0, explanation: "Subtract 1 from the tens place." },
  { topic: "Subtraction with Borrowing", question: "What is 20 - 12?", options: ["6", "8", "10"], correctOption: 1, explanation: "20 - 10 = 10, 10 - 2 = 8." },
  { topic: "Subtraction with Borrowing", question: "What is 60 - 30?", options: ["20", "30", "40"], correctOption: 1, explanation: "60 - 30 = 30." },
  { topic: "Subtraction with Borrowing", question: "What is 15 - 15?", options: ["15", "0", "1"], correctOption: 1, explanation: "Any number minus itself is zero." },

  // Multiplication (2, 5, 10 tables)
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 2 x 3?", options: ["5", "6", "7"], correctOption: 1, explanation: "2 groups of 3 is 6." },
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 5 x 2?", options: ["7", "10", "12"], correctOption: 1, explanation: "5 groups of 2 is 10." },
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 10 x 4?", options: ["14", "40", "44"], correctOption: 1, explanation: "10 groups of 4 is 40." },
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 2 x 5?", options: ["10", "12", "7"], correctOption: 0, explanation: "2 x 5 = 10." },
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 5 x 5?", options: ["20", "25", "30"], correctOption: 1, explanation: "5, 10, 15, 20, 25." },
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 10 x 10?", options: ["20", "100", "110"], correctOption: 1, explanation: "10 groups of 10 is 100." },
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 2 x 8?", options: ["14", "16", "18"], correctOption: 1, explanation: "2 x 8 = 16." },
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 5 x 3?", options: ["10", "15", "20"], correctOption: 1, explanation: "5 x 3 = 15." },
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 10 x 6?", options: ["16", "60", "66"], correctOption: 1, explanation: "10 x 6 = 60." },
  { topic: "Multiplication (2, 5, 10 tables)", question: "What is 2 x 10?", options: ["12", "20", "22"], correctOption: 1, explanation: "2 x 10 = 20." },

  // Division (Sharing)
  { topic: "Division (Sharing)", question: "Share 10 cookies between 2 children. How many each?", options: ["2", "5", "10"], correctOption: 1, explanation: "10 divided by 2 is 5." },
  { topic: "Division (Sharing)", question: "What is 6 ÷ 2?", options: ["2", "3", "4"], correctOption: 1, explanation: "6 shared into 2 groups is 3." },
  { topic: "Division (Sharing)", question: "What is 20 ÷ 5?", options: ["2", "4", "5"], correctOption: 1, explanation: "20 shared into 5 groups is 4." },
  { topic: "Division (Sharing)", question: "What is 30 ÷ 10?", options: ["3", "10", "30"], correctOption: 0, explanation: "30 shared into 10 groups is 3." },
  { topic: "Division (Sharing)", question: "Share 12 pencils between 2 friends.", options: ["4", "6", "8"], correctOption: 1, explanation: "12 ÷ 2 = 6." },
  { topic: "Division (Sharing)", question: "What is 15 ÷ 3?", options: ["3", "5", "15"], correctOption: 1, explanation: "15 ÷ 3 = 5." },
  { topic: "Division (Sharing)", question: "What is 8 ÷ 2?", options: ["2", "4", "6"], correctOption: 1, explanation: "8 ÷ 2 = 4." },
  { topic: "Division (Sharing)", question: "What is 50 ÷ 10?", options: ["5", "10", "50"], correctOption: 0, explanation: "50 ÷ 10 = 5." },
  { topic: "Division (Sharing)", question: "Share 25 sweets among 5 kids.", options: ["4", "5", "6"], correctOption: 1, explanation: "25 ÷ 5 = 5." },
  { topic: "Division (Sharing)", question: "What is 14 ÷ 2?", options: ["6", "7", "8"], correctOption: 1, explanation: "14 ÷ 2 = 7." },

  // Fractions (Halves and Quarters)
  { topic: "Fractions (Halves and Quarters)", question: "What is half of 10?", options: ["2", "5", "10"], correctOption: 1, explanation: "Half means dividing by 2." },
  { topic: "Fractions (Halves and Quarters)", question: "How many halves make a whole?", options: ["1", "2", "4"], correctOption: 1, explanation: "Two halves make one whole." },
  { topic: "Fractions (Halves and Quarters)", question: "What is 1/2 of 8?", options: ["2", "4", "6"], correctOption: 1, explanation: "Half of 8 is 4." },
  { topic: "Fractions (Halves and Quarters)", question: "How many quarters make a whole?", options: ["2", "3", "4"], correctOption: 2, explanation: "Four quarters make one whole." },
  { topic: "Fractions (Halves and Quarters)", question: "What is 1/4 of 4?", options: ["1", "2", "4"], correctOption: 0, explanation: "A quarter of 4 is 1." },
  { topic: "Fractions (Halves and Quarters)", question: "Which is bigger: 1/2 or 1/4?", options: ["1/2", "1/4", "They are same"], correctOption: 0, explanation: "A half is bigger than a quarter." },
  { topic: "Fractions (Halves and Quarters)", question: "What is half of 20?", options: ["5", "10", "15"], correctOption: 1, explanation: "Half of 20 is 10." },
  { topic: "Fractions (Halves and Quarters)", question: "What is 1/2 of 12?", options: ["4", "6", "8"], correctOption: 1, explanation: "Half of 12 is 6." },
  { topic: "Fractions (Halves and Quarters)", question: "How many quarters make a half?", options: ["1", "2", "4"], correctOption: 1, explanation: "Two quarters make a half." },
  { topic: "Fractions (Halves and Quarters)", question: "What is 1/4 of 8?", options: ["2", "4", "8"], correctOption: 0, explanation: "8 divided by 4 is 2." },

  // Measuring Length
  { topic: "Measuring Length", question: "What do we use to measure length?", options: ["Clock", "Ruler", "Scale"], correctOption: 1, explanation: "Rulers measure how long something is." },
  { topic: "Measuring Length", question: "Which is longer: 10cm or 10m?", options: ["10cm", "10m", "Same"], correctOption: 1, explanation: "Meters are much longer than centimeters." },
  { topic: "Measuring Length", question: "What unit do we use for weight?", options: ["Liters", "Kilograms", "Meters"], correctOption: 1, explanation: "Kilograms (kg) measure weight." },
  { topic: "Measuring Length", question: "What unit do we use for milk or water?", options: ["Liters", "Grams", "Centimeters"], correctOption: 0, explanation: "Liters (L) measure liquids." },
  { topic: "Measuring Length", question: "Which is heavier: A bag of rice or a pencil?", options: ["Rice", "Pencil"], correctOption: 0, explanation: "Rice is much heavier." },
  { topic: "Measuring Length", question: "How many centimeters are in a small ruler?", options: ["15cm", "100cm", "1m"], correctOption: 0, explanation: "Most small school rulers are 15cm or 30cm." },
  { topic: "Measuring Length", question: "Which holds more: A cup or a bucket?", options: ["Cup", "Bucket"], correctOption: 1, explanation: "A bucket holds more liters." },
  { topic: "Measuring Length", question: "Which is shorter: 5cm or 2cm?", options: ["5cm", "2cm"], correctOption: 1, explanation: "2 is less than 5." },
  { topic: "Measuring Length", question: "What do we use to measure weight?", options: ["Ruler", "Measuring Tape", "Weighing Scale"], correctOption: 2, explanation: "Scales measure weight." },
  { topic: "Measuring Length", question: "Which is lighter: A feather or a book?", options: ["Feather", "Book"], correctOption: 0, explanation: "A feather is very light." },

  // Time: Half-Hours
  { topic: "Time: Half-Hours", question: "How many minutes are in one hour?", options: ["30", "60", "100"], correctOption: 1, explanation: "There are 60 minutes in an hour." },
  { topic: "Time: Half-Hours", question: "What is 'half past 2' in numbers?", options: ["2:00", "2:30", "3:00"], correctOption: 1, explanation: "Half past means 30 minutes." },
  { topic: "Time: Half-Hours", question: "If the big hand is on 12 and the small hand is on 5, what time is it?", options: ["5:00", "12:05", "6:00"], correctOption: 0, explanation: "Big hand on 12 means 'o'clock'." },
  { topic: "Time: Half-Hours", question: "How many hours are in a day?", options: ["12", "24", "60"], correctOption: 1, explanation: "A full day has 24 hours." },
  { topic: "Time: Half-Hours", question: "What is 1:30 called?", options: ["One o'clock", "Half past one", "Two o'clock"], correctOption: 1, explanation: "1:30 is half past one." },
  { topic: "Time: Half-Hours", question: "Which hand on a clock is the hour hand?", options: ["The long hand", "The short hand", "The fast hand"], correctOption: 1, explanation: "The short hand tells the hour." },
  { topic: "Time: Half-Hours", question: "What time is 10 o'clock?", options: ["10:00", "10:30", "12:10"], correctOption: 0, explanation: "O'clock means :00." },
  { topic: "Time: Half-Hours", question: "If it is 3:00 now, what time will it be in one hour?", options: ["3:30", "4:00", "2:00"], correctOption: 1, explanation: "3 + 1 = 4." },
  { topic: "Time: Half-Hours", question: "How many minutes are in half an hour?", options: ["15", "30", "60"], correctOption: 1, explanation: "Half of 60 is 30." },
  { topic: "Time: Half-Hours", question: "What time is half past 7?", options: ["7:00", "7:30", "8:00"], correctOption: 1, explanation: "Half past is 30 minutes." },

  // Money: Addition
  { topic: "Money: Addition", question: "What is the currency of Nigeria?", options: ["Dollars", "Naira", "Pounds"], correctOption: 1, explanation: "We use Naira and Kobo." },
  { topic: "Money: Addition", question: "How many 50 Naira notes make 100 Naira?", options: ["2", "3", "5"], correctOption: 0, explanation: "50 + 50 = 100." },
  { topic: "Money: Addition", question: "What is N20 + N10?", options: ["N10", "N30", "N40"], correctOption: 1, explanation: "20 + 10 = 30." },
  { topic: "Money: Addition", question: "If a pen costs N50 and you pay with N100, what is your change?", options: ["N20", "N50", "N70"], correctOption: 1, explanation: "100 - 50 = 50." },
  { topic: "Money: Addition", question: "Which is more: N200 or N500?", options: ["N200", "N500", "They are same"], correctOption: 1, explanation: "500 is a larger number." },
  { topic: "Money: Addition", question: "How many 10 Naira notes make 50 Naira?", options: ["2", "5", "10"], correctOption: 1, explanation: "10, 20, 30, 40, 50." },
  { topic: "Money: Addition", question: "What is N500 - N200?", options: ["N100", "N300", "N700"], correctOption: 1, explanation: "5 - 2 = 3, so 500 - 200 = 300." },
  { topic: "Money: Addition", question: "Which note is green in color?", options: ["N100", "N200", "N1000"], correctOption: 1, explanation: "The 200 Naira note is green." },
  { topic: "Money: Addition", question: "What is N50 + N50?", options: ["N50", "N100", "N150"], correctOption: 1, explanation: "50 + 50 = 100." },
  { topic: "Money: Addition", question: "If you buy a sweet for N10 and a biscuit for N20, how much total?", options: ["N20", "N30", "N40"], correctOption: 1, explanation: "10 + 20 = 30." },

  // Shapes and Data
  { topic: "Shapes and Data", question: "Which shape has 4 sides but they are NOT all equal?", options: ["Square", "Rectangle", "Triangle"], correctOption: 1, explanation: "A rectangle has 2 long sides and 2 short sides." },
  { topic: "Shapes and Data", question: "Which 3D shape looks like a ball?", options: ["Cube", "Sphere", "Cylinder"], correctOption: 1, explanation: "A sphere is round like a ball." },
  { topic: "Shapes and Data", question: "Which 3D shape looks like a tin of milk?", options: ["Cube", "Sphere", "Cylinder"], correctOption: 2, explanation: "A cylinder is round with flat ends." },
  { topic: "Shapes and Data", question: "How many corners does a rectangle have?", options: ["3", "4", "6"], correctOption: 1, explanation: "A rectangle has 4 corners." },
  { topic: "Shapes and Data", question: "Which shape looks like a party hat?", options: ["Cube", "Cone", "Sphere"], correctOption: 1, explanation: "A cone has a point and a round base." },
  { topic: "Shapes and Data", question: "Which 3D shape looks like a dice?", options: ["Cube", "Cylinder", "Cone"], correctOption: 0, explanation: "A cube has 6 equal square faces." },
  { topic: "Shapes and Data", question: "How many sides does a pentagon have?", options: ["4", "5", "6"], correctOption: 1, explanation: "Penta means 5." },
  { topic: "Shapes and Data", question: "A brick is shaped like a ___.", options: ["Cube", "Cuboid", "Sphere"], correctOption: 1, explanation: "A cuboid is a long cube." },
  { topic: "Shapes and Data", question: "Which shape has 6 sides?", options: ["Pentagon", "Hexagon", "Octagon"], correctOption: 1, explanation: "Hexa means 6." },
  { topic: "Shapes and Data", question: "A pyramid has a ___ base.", options: ["Round", "Square or Triangle", "Oval"], correctOption: 1, explanation: "Pyramids usually have flat bases." },

  // Mixed Review
  { question: "What is 10 + 10 + 10?", options: ["20", "30", "40"], correctOption: 1, explanation: "Counting by 10s: 10, 20, 30." },
  { question: "What is half of 100?", options: ["25", "50", "75"], correctOption: 1, explanation: "50 + 50 = 100." },
  { question: "What is 2 x 9?", options: ["11", "18", "20"], correctOption: 1, explanation: "2 groups of 9 is 18." },
  { question: "What is 15 - 7?", options: ["7", "8", "9"], correctOption: 1, explanation: "7 + 8 = 15." },
  { question: "Which number is even?", options: ["3", "5", "8"], correctOption: 2, explanation: "Even numbers can be divided by 2." },
  { question: "Which number is odd?", options: ["2", "7", "10"], correctOption: 1, explanation: "Odd numbers cannot be divided by 2 equally." },
  { question: "What is 5 x 4?", options: ["15", "20", "25"], correctOption: 1, explanation: "5, 10, 15, 20." },
  { question: "What is 12 ÷ 2?", options: ["4", "6", "8"], correctOption: 1, explanation: "Half of 12 is 6." },
  { question: "What is 40 + 7?", options: ["40", "47", "74"], correctOption: 1, explanation: "4 tens and 7 units." },
  { question: "What number comes before 50?", options: ["48", "49", "51"], correctOption: 1, explanation: "49 comes right before 50." }
];
