export const PRIMARY_1_MATH_POOL = [
  // Counting to 20
  { topic: "Counting to 20", question: "What number comes after 10?", options: ["9", "11", "12"], correctOption: 1, explanation: "10, 11, 12..." },
  { topic: "Counting to 20", question: "What number comes before 5?", options: ["4", "6", "3"], correctOption: 0, explanation: "4 comes right before 5." },
  { topic: "Counting to 20", question: "Count the stars: ⭐⭐⭐", options: ["2", "3", "4"], correctOption: 1, explanation: "There are three stars." },
  { topic: "Counting to 20", question: "Which is the largest number?", options: ["10", "15", "5"], correctOption: 1, explanation: "15 is bigger than 10 and 5." },
  { topic: "Counting to 20", question: "Which is the smallest number?", options: ["2", "8", "0"], correctOption: 2, explanation: "0 is the smallest." },
  { topic: "Counting to 20", question: "What is 10 + 1?", options: ["11", "12", "10"], correctOption: 0, explanation: "10 plus 1 is 11." },
  { topic: "Counting to 20", question: "What is 20 - 1?", options: ["18", "19", "20"], correctOption: 1, explanation: "20 take away 1 is 19." },
  { topic: "Counting to 20", question: "How many fingers do you have on one hand?", options: ["4", "5", "10"], correctOption: 1, explanation: "Most people have 5 fingers on one hand." },
  { topic: "Counting to 20", question: "What number is between 14 and 16?", options: ["13", "15", "17"], correctOption: 1, explanation: "14, 15, 16." },
  { topic: "Counting to 20", question: "How many legs does a dog have?", options: ["2", "4", "6"], correctOption: 1, explanation: "Dogs have 4 legs." },

  // Basic Shapes
  { topic: "Basic Shapes", question: "Which shape has 3 sides?", options: ["Square", "Circle", "Triangle"], correctOption: 2, explanation: "A triangle has three sides." },
  { topic: "Basic Shapes", question: "Which shape is round like a ball?", options: ["Square", "Circle", "Rectangle"], correctOption: 1, explanation: "A circle is round." },
  { topic: "Basic Shapes", question: "Which shape has 4 equal sides?", options: ["Square", "Triangle", "Circle"], correctOption: 0, explanation: "A square has four equal sides." },
  { topic: "Basic Shapes", question: "A door is usually shaped like a ___.", options: ["Circle", "Triangle", "Rectangle"], correctOption: 2, explanation: "Doors are usually rectangles." },
  { topic: "Basic Shapes", question: "How many corners does a square have?", options: ["3", "4", "0"], correctOption: 1, explanation: "A square has 4 corners." },
  { topic: "Basic Shapes", question: "Which shape has NO corners?", options: ["Square", "Circle", "Triangle"], correctOption: 1, explanation: "A circle has no corners." },
  { topic: "Basic Shapes", question: "An egg is shaped like an ___.", options: ["Oval", "Square", "Triangle"], correctOption: 0, explanation: "Eggs are ovals." },
  { topic: "Basic Shapes", question: "A slice of pizza is shaped like a ___.", options: ["Circle", "Triangle", "Square"], correctOption: 1, explanation: "Pizza slices are triangular." },
  { topic: "Basic Shapes", question: "A window is often a ___.", options: ["Circle", "Square", "Triangle"], correctOption: 1, explanation: "Many windows are squares." },
  { topic: "Basic Shapes", question: "A wheel is a ___.", options: ["Square", "Triangle", "Circle"], correctOption: 2, explanation: "Wheels are circles." },

  // Addition
  { topic: "Addition", question: "What is 2 + 2?", options: ["3", "4", "5"], correctOption: 1, explanation: "2 and 2 make 4." },
  { topic: "Addition", question: "What is 1 + 3?", options: ["4", "5", "2"], correctOption: 0, explanation: "1 and 3 make 4." },
  { topic: "Addition", question: "What is 5 + 0?", options: ["0", "5", "10"], correctOption: 1, explanation: "Adding zero doesn't change the number." },
  { topic: "Addition", question: "What is 4 + 2?", options: ["5", "6", "7"], correctOption: 1, explanation: "4 plus 2 is 6." },
  { topic: "Addition", question: "What is 3 + 3?", options: ["6", "7", "5"], correctOption: 0, explanation: "3 plus 3 is 6." },
  { topic: "Addition", question: "What is 1 + 1?", options: ["1", "2", "3"], correctOption: 1, explanation: "1 and 1 make 2." },
  { topic: "Addition", question: "What is 0 + 8?", options: ["0", "8", "18"], correctOption: 1, explanation: "0 + 8 = 8." },
  { topic: "Addition", question: "What is 7 + 2?", options: ["8", "9", "10"], correctOption: 1, explanation: "7 plus 2 is 9." },
  { topic: "Addition", question: "What is 6 + 1?", options: ["5", "6", "7"], correctOption: 2, explanation: "6 plus 1 is 7." },
  { topic: "Addition", question: "What is 4 + 4?", options: ["7", "8", "9"], correctOption: 1, explanation: "4 plus 4 is 8." },

  // Subtraction
  { topic: "Subtraction", question: "What is 5 - 1?", options: ["4", "3", "6"], correctOption: 0, explanation: "5 take away 1 is 4." },
  { topic: "Subtraction", question: "What is 3 - 2?", options: ["1", "2", "0"], correctOption: 0, explanation: "3 take away 2 is 1." },
  { topic: "Subtraction", question: "What is 4 - 4?", options: ["4", "0", "1"], correctOption: 1, explanation: "Any number minus itself is zero." },
  { topic: "Subtraction", question: "What is 10 - 5?", options: ["4", "5", "6"], correctOption: 1, explanation: "10 take away 5 is 5." },
  { topic: "Subtraction", question: "What is 8 - 2?", options: ["5", "6", "7"], correctOption: 1, explanation: "8 take away 2 is 6." },
  { topic: "Subtraction", question: "What is 6 - 3?", options: ["2", "3", "4"], correctOption: 1, explanation: "6 take away 3 is 3." },
  { topic: "Subtraction", question: "What is 9 - 0?", options: ["0", "9", "1"], correctOption: 1, explanation: "Taking away zero changes nothing." },
  { topic: "Subtraction", question: "What is 7 - 4?", options: ["2", "3", "4"], correctOption: 1, explanation: "7 take away 4 is 3." },
  { topic: "Subtraction", question: "What is 2 - 1?", options: ["0", "1", "2"], correctOption: 1, explanation: "2 take away 1 is 1." },
  { topic: "Subtraction", question: "What is 5 - 5?", options: ["5", "0", "10"], correctOption: 1, explanation: "5 - 5 = 0." },

  // Comparing
  { topic: "Comparing", question: "Which is more?", options: ["5 apples", "2 apples", "1 apple"], correctOption: 0, explanation: "5 is the biggest number." },
  { topic: "Comparing", question: "Which is less?", options: ["10 pens", "8 pens", "12 pens"], correctOption: 1, explanation: "8 is smaller than 10 and 12." },
  { topic: "Comparing", question: "Is 5 equal to 5?", options: ["Yes", "No"], correctOption: 0, explanation: "5 and 5 are the same." },
  { topic: "Comparing", question: "Which is greater than 7?", options: ["6", "7", "8"], correctOption: 2, explanation: "8 is greater than 7." },
  { topic: "Comparing", question: "Which is less than 3?", options: ["2", "3", "4"], correctOption: 0, explanation: "2 is less than 3." },
  { topic: "Comparing", question: "Which group has more: 🍎🍎 or 🍎🍎🍎?", options: ["First group", "Second group"], correctOption: 1, explanation: "3 is more than 2." },
  { topic: "Comparing", question: "Which number is the biggest?", options: ["11", "19", "13"], correctOption: 1, explanation: "19 is the largest." },
  { topic: "Comparing", question: "Which number is the smallest?", options: ["14", "11", "17"], correctOption: 1, explanation: "11 is the smallest." },
  { topic: "Comparing", question: "Is 10 greater than 2?", options: ["Yes", "No"], correctOption: 0, explanation: "10 is much bigger than 2." },
  { topic: "Comparing", question: "Is 1 less than 9?", options: ["Yes", "No"], correctOption: 0, explanation: "1 is smaller than 9." },

  // Patterns
  { topic: "Patterns", question: "What comes next: 1, 2, 1, 2, ___?", options: ["1", "2", "3"], correctOption: 0, explanation: "The pattern repeats 1, 2." },
  { topic: "Patterns", question: "What comes next: Red, Blue, Red, Blue, ___?", options: ["Red", "Blue", "Green"], correctOption: 0, explanation: "The pattern repeats Red, Blue." },
  { topic: "Patterns", question: "What comes next: 2, 4, 6, ___?", options: ["7", "8", "9"], correctOption: 1, explanation: "These are even numbers (counting by 2s)." },
  { topic: "Patterns", question: "What comes next: 5, 10, 15, ___?", options: ["16", "20", "25"], correctOption: 1, explanation: "Counting by 5s." },
  { topic: "Patterns", question: "What comes next: 🍎, 🍌, 🍎, 🍌, ___?", options: ["🍎", "🍌", "🍇"], correctOption: 0, explanation: "The pattern repeats Apple, Banana." },
  { topic: "Patterns", question: "What comes next: 10, 9, 8, ___?", options: ["7", "6", "11"], correctOption: 0, explanation: "Counting backward." },
  { topic: "Patterns", question: "What comes next: A, B, A, B, ___?", options: ["A", "B", "C"], correctOption: 0, explanation: "The pattern repeats A, B." },
  { topic: "Patterns", question: "What comes next: Up, Down, Up, Down, ___?", options: ["Up", "Down", "Left"], correctOption: 0, explanation: "The pattern repeats Up, Down." },
  { topic: "Patterns", question: "What comes next: 1, 1, 2, 2, 3, ___?", options: ["3", "4", "2"], correctOption: 0, explanation: "Each number repeats twice." },
  { topic: "Patterns", question: "What comes next: ⚪, ⚫, ⚪, ⚫, ___?", options: ["⚪", "⚫", "🔴"], correctOption: 0, explanation: "The pattern repeats White, Black." },

  // Measurement
  { topic: "Measurement", question: "Which is heavier?", options: ["A feather", "A stone", "A leaf"], correctOption: 1, explanation: "A stone is much heavier than a feather." },
  { topic: "Measurement", question: "Which is longer?", options: ["A pencil", "A bus", "A spoon"], correctOption: 1, explanation: "A bus is very long." },
  { topic: "Measurement", question: "Which is taller?", options: ["A cat", "A giraffe", "A dog"], correctOption: 1, explanation: "Giraffes are very tall." },
  { topic: "Measurement", question: "Which holds more water?", options: ["A cup", "A bucket", "A spoon"], correctOption: 1, explanation: "A bucket is much bigger than a cup." },
  { topic: "Measurement", question: "Which is faster?", options: ["A turtle", "A car", "A snail"], correctOption: 1, explanation: "Cars move very fast." },
  { topic: "Measurement", question: "Which is colder?", options: ["Ice", "Hot tea", "Warm milk"], correctOption: 0, explanation: "Ice is frozen and cold." },
  { topic: "Measurement", question: "Which is hotter?", options: ["The sun", "The moon", "A cloud"], correctOption: 0, explanation: "The sun is a hot star." },
  { topic: "Measurement", question: "Which is shorter?", options: ["A ruler", "A pencil", "A building"], correctOption: 1, explanation: "A pencil is shorter than a ruler." },
  { topic: "Measurement", question: "Which is lighter?", options: ["A bag of rice", "A balloon", "A table"], correctOption: 1, explanation: "Balloons are filled with air and very light." },
  { topic: "Measurement", question: "Which is wider?", options: ["A road", "A path", "A thread"], correctOption: 0, explanation: "A road is wide for cars." },

  // Time and Money
  { topic: "Time and Money", question: "What do we use to tell time?", options: ["A ruler", "A clock", "A scale"], correctOption: 1, explanation: "Clocks tell us the time." },
  { topic: "Time and Money", question: "How many days are in a week?", options: ["5", "7", "10"], correctOption: 1, explanation: "There are 7 days." },
  { topic: "Time and Money", question: "Which day is for school?", options: ["Sunday", "Monday", "Saturday"], correctOption: 1, explanation: "Monday is a school day." },
  { topic: "Time and Money", question: "What is the color of the 200 Naira note?", options: ["Blue", "Green", "Red"], correctOption: 1, explanation: "The 200 Naira note is green." },
  { topic: "Time and Money", question: "What is the color of the 100 Naira note?", options: ["Purple", "Blue", "Green"], correctOption: 1, explanation: "The 100 Naira note is blue." },
  { topic: "Time and Money", question: "What do we use to buy things?", options: ["Paper", "Money", "Leaves"], correctOption: 1, explanation: "We use money to buy things." },
  { topic: "Time and Money", question: "Morning comes after ___.", options: ["Afternoon", "Night", "Evening"], correctOption: 1, explanation: "Morning starts after the night ends." },
  { topic: "Time and Money", question: "We sleep at ___.", options: ["Morning", "Noon", "Night"], correctOption: 2, explanation: "Night is for sleeping." },
  { topic: "Time and Money", question: "A clock has ___ hands.", options: ["2", "5", "0"], correctOption: 0, explanation: "Most clocks have a big hand and a small hand." },
  { topic: "Time and Money", question: "Which is a coin?", options: ["N100", "N50", "N2"], correctOption: 2, explanation: "N2 is a coin in Nigeria." },

  // Logic and Sets
  { topic: "Logic and Sets", question: "Which one does NOT belong?", options: ["Apple", "Banana", "Car"], correctOption: 2, explanation: "Apple and Banana are fruits, but a car is a vehicle." },
  { topic: "Logic and Sets", question: "Which one is an animal?", options: ["Table", "Lion", "Chair"], correctOption: 1, explanation: "A lion is an animal." },
  { topic: "Logic and Sets", question: "Which one is a fruit?", options: ["Orange", "Potato", "Onion"], correctOption: 0, explanation: "Orange is a fruit." },
  { topic: "Logic and Sets", question: "Which one can fly?", options: ["Cow", "Bird", "Pig"], correctOption: 1, explanation: "Birds have wings to fly." },
  { topic: "Logic and Sets", question: "Which one lives in water?", options: ["Fish", "Cat", "Bird"], correctOption: 0, explanation: "Fish breathe in water." },
  { topic: "Logic and Sets", question: "Which one is a toy?", options: ["Hammer", "Doll", "Spoon"], correctOption: 1, explanation: "A doll is a toy." },
  { topic: "Logic and Sets", question: "Which one do you wear?", options: ["Shirt", "Plate", "Book"], correctOption: 0, explanation: "You wear a shirt." },
  { topic: "Logic and Sets", question: "Which one do you eat with?", options: ["Spoon", "Pencil", "Comb"], correctOption: 0, explanation: "You use a spoon to eat." },
  { topic: "Logic and Sets", question: "Which one is a vegetable?", options: ["Carrot", "Mango", "Cake"], correctOption: 0, explanation: "Carrot is a vegetable." },
  { topic: "Logic and Sets", question: "Which one is a vehicle?", options: ["Bus", "Tree", "House"], correctOption: 0, explanation: "A bus is a vehicle." },

  // Mixed Review
  { question: "What is 10 + 10?", options: ["10", "20", "30"], correctOption: 1, explanation: "10 and 10 make 20." },
  { question: "What is 20 - 10?", options: ["5", "10", "15"], correctOption: 1, explanation: "20 minus 10 is 10." },
  { question: "How many sides does a circle have?", options: ["0", "1", "4"], correctOption: 0, explanation: "A circle has no straight sides." },
  { question: "What is 1 + 2 + 3?", options: ["5", "6", "7"], correctOption: 1, explanation: "1+2=3, and 3+3=6." },
  { question: "Which number comes before 20?", options: ["19", "21", "18"], correctOption: 0, explanation: "19, 20." },
  { question: "Which number comes after 19?", options: ["18", "20", "21"], correctOption: 1, explanation: "19, 20." },
  { question: "What is 5 + 5 + 5?", options: ["10", "15", "20"], correctOption: 1, explanation: "Counting by 5s: 5, 10, 15." },
  { question: "What is 4 - 0?", options: ["0", "4", "1"], correctOption: 1, explanation: "Subtracting zero changes nothing." },
  { question: "Which is the biggest: 2, 12, 20?", options: ["2", "12", "20"], correctOption: 2, explanation: "20 is the largest." },
  { question: "How many corners does a triangle have?", options: ["2", "3", "4"], correctOption: 1, explanation: "A triangle has 3 corners." }
];
