export const PRIMARY_1_ENGLISH_POOL = [
  // Alphabetical Order
  { topic: "Alphabetical Order", question: "Which letter comes after 'A'?", options: ["B", "C", "D"], correctOption: 0, explanation: "The alphabet goes A, B, C..." },
  { topic: "Alphabetical Order", question: "Which letter comes before 'Z'?", options: ["X", "Y", "W"], correctOption: 1, explanation: "Y comes right before Z." },
  { topic: "Alphabetical Order", question: "What is the first letter of the alphabet?", options: ["Z", "A", "M"], correctOption: 1, explanation: "A is the very first letter." },
  { topic: "Alphabetical Order", question: "What is the last letter of the alphabet?", options: ["Y", "X", "Z"], correctOption: 2, explanation: "Z is the final letter." },
  { topic: "Alphabetical Order", question: "Which letter is between 'F' and 'H'?", options: ["G", "I", "E"], correctOption: 0, explanation: "F, G, H." },
  { topic: "Alphabetical Order", question: "Which letter comes after 'M'?", options: ["L", "N", "O"], correctOption: 1, explanation: "M, N, O." },
  { topic: "Alphabetical Order", question: "Which letter comes before 'E'?", options: ["D", "F", "C"], correctOption: 0, explanation: "D, E, F." },
  { topic: "Alphabetical Order", question: "Which letter is between 'R' and 'T'?", options: ["S", "Q", "U"], correctOption: 0, explanation: "R, S, T." },
  { topic: "Alphabetical Order", question: "What letter comes after 'S'?", options: ["R", "T", "U"], correctOption: 1, explanation: "S, T, U." },
  { topic: "Alphabetical Order", question: "What letter comes before 'B'?", options: ["A", "C", "D"], correctOption: 0, explanation: "A is the first letter." },

  // Opposites
  { topic: "Opposites", question: "What is the opposite of 'Big'?", options: ["Large", "Small", "Tall"], correctOption: 1, explanation: "Small is the opposite of big." },
  { topic: "Opposites", question: "What is the opposite of 'Up'?", options: ["Down", "Left", "Right"], correctOption: 0, explanation: "Up and Down are opposites." },
  { topic: "Opposites", question: "What is the opposite of 'Hot'?", options: ["Warm", "Cold", "Sunny"], correctOption: 1, explanation: "Cold is the opposite of hot." },
  { topic: "Opposites", question: "What is the opposite of 'Happy'?", options: ["Glad", "Sad", "Angry"], correctOption: 1, explanation: "Sad is the opposite of happy." },
  { topic: "Opposites", question: "What is the opposite of 'Day'?", options: ["Morning", "Night", "Afternoon"], correctOption: 1, explanation: "Night is the opposite of day." },
  { topic: "Opposites", question: "What is the opposite of 'Fast'?", options: ["Quick", "Slow", "Run"], correctOption: 1, explanation: "Slow is the opposite of fast." },
  { topic: "Opposites", question: "What is the opposite of 'In'?", options: ["On", "Out", "Under"], correctOption: 1, explanation: "In and Out are opposites." },
  { topic: "Opposites", question: "What is the opposite of 'Boy'?", options: ["Man", "Girl", "Child"], correctOption: 1, explanation: "Girl is the opposite of boy." },
  { topic: "Opposites", question: "What is the opposite of 'Tall'?", options: ["Short", "Long", "Big"], correctOption: 0, explanation: "Short is the opposite of tall." },
  { topic: "Opposites", question: "What is the opposite of 'Open'?", options: ["Close", "Shut", "Both A and B"], correctOption: 2, explanation: "Both close and shut mean the opposite of open." },

  // Action Words (Verbs)
  { topic: "Action Words", question: "Which is an action word?", options: ["Table", "Jump", "Red"], correctOption: 1, explanation: "Jump is something you do." },
  { topic: "Action Words", question: "Which word tells us what a bird does?", options: ["Fly", "Green", "Tree"], correctOption: 0, explanation: "Birds fly." },
  { topic: "Action Words", question: "Which is an action word?", options: ["Eat", "Apple", "Sweet"], correctOption: 0, explanation: "Eat is an action." },
  { topic: "Action Words", question: "What do you do with a book?", options: ["Read", "Sleep", "Run"], correctOption: 0, explanation: "You read a book." },
  { topic: "Action Words", question: "Which is an action word?", options: ["Sleep", "Bed", "Pillow"], correctOption: 0, explanation: "Sleep is an action." },
  { topic: "Action Words", question: "What do you do with water?", options: ["Eat", "Drink", "Walk"], correctOption: 1, explanation: "You drink water." },
  { topic: "Action Words", question: "Which is an action word?", options: ["Run", "Fast", "Shoes"], correctOption: 0, explanation: "Run is an action." },
  { topic: "Action Words", question: "What do you do with a ball?", options: ["Kick", "Sit", "Read"], correctOption: 0, explanation: "You kick a ball." },
  { topic: "Action Words", question: "Which is an action word?", options: ["Write", "Pencil", "Paper"], correctOption: 0, explanation: "Write is an action." },
  { topic: "Action Words", question: "What do you do with your ears?", options: ["See", "Hear", "Smell"], correctOption: 1, explanation: "You hear with your ears." },

  // Colors
  { topic: "Colors and Names", question: "What color is the sky on a sunny day?", options: ["Green", "Blue", "Red"], correctOption: 1, explanation: "The sky is blue." },
  { topic: "Colors and Names", question: "What color is grass?", options: ["Yellow", "Blue", "Green"], correctOption: 2, explanation: "Grass is green." },
  { topic: "Colors and Names", question: "What color is a ripe tomato?", options: ["Red", "Purple", "Black"], correctOption: 0, explanation: "Tomatoes are red." },
  { topic: "Colors and Names", question: "What color is a banana?", options: ["Pink", "Yellow", "Orange"], correctOption: 1, explanation: "Bananas are yellow." },
  { topic: "Colors and Names", question: "What color is coal?", options: ["White", "Grey", "Black"], correctOption: 2, explanation: "Coal is black." },
  { topic: "Colors and Names", question: "What color is milk?", options: ["White", "Yellow", "Blue"], correctOption: 0, explanation: "Milk is white." },
  { topic: "Colors and Names", question: "What color is an orange fruit?", options: ["Red", "Orange", "Yellow"], correctOption: 1, explanation: "Oranges are orange." },
  { topic: "Colors and Names", question: "What color is a crow?", options: ["White", "Black", "Brown"], correctOption: 1, explanation: "Crows are black." },
  { topic: "Colors and Names", question: "What color is a carrot?", options: ["Orange", "Green", "Blue"], correctOption: 0, explanation: "Carrots are orange." },
  { topic: "Colors and Names", question: "What color is the sun?", options: ["Blue", "Yellow", "Green"], correctOption: 1, explanation: "The sun looks yellow." },

  // Family Members
  { topic: "My Family Members", question: "Who is your father's wife?", options: ["Sister", "Mother", "Aunt"], correctOption: 1, explanation: "Your father's wife is your mother." },
  { topic: "My Family Members", question: "Who is your mother's son?", options: ["Sister", "Brother", "Father"], correctOption: 1, explanation: "Your mother's son is your brother." },
  { topic: "My Family Members", question: "Who is your father's father?", options: ["Uncle", "Grandfather", "Brother"], correctOption: 1, explanation: "Your father's father is your grandfather." },
  { topic: "My Family Members", question: "Who is your mother's sister?", options: ["Aunt", "Grandmother", "Cousin"], correctOption: 0, explanation: "Your mother's sister is your aunt." },
  { topic: "My Family Members", question: "Who is your father's brother?", options: ["Uncle", "Nephew", "Grandfather"], correctOption: 0, explanation: "Your father's brother is your uncle." },
  { topic: "My Family Members", question: "Who is your mother's daughter?", options: ["Brother", "Sister", "Mother"], correctOption: 1, explanation: "Your mother's daughter is your sister." },
  { topic: "My Family Members", question: "Who is your mother's mother?", options: ["Aunt", "Grandmother", "Sister"], correctOption: 1, explanation: "Your mother's mother is your grandmother." },
  { topic: "My Family Members", question: "A family with father, mother, and children is a ___ family.", options: ["Big", "Nuclear", "Extended"], correctOption: 1, explanation: "A nuclear family has parents and children." },
  { topic: "My Family Members", question: "Your aunt's child is your ___.", options: ["Brother", "Sister", "Cousin"], correctOption: 2, explanation: "Your aunt's child is your cousin." },
  { topic: "My Family Members", question: "Who is the head of a nuclear family?", options: ["Children", "Father", "Baby"], correctOption: 1, explanation: "Usually, the father is the head of the nuclear family." },

  // Greetings
  { topic: "Greeting People", question: "What do you say in the morning?", options: ["Good night", "Good morning", "Good bye"], correctOption: 1, explanation: "We say good morning in the morning." },
  { topic: "Greeting People", question: "What do you say when you go to bed?", options: ["Good afternoon", "Good night", "Hello"], correctOption: 1, explanation: "We say good night before sleeping." },
  { topic: "Greeting People", question: "What do you say when you meet someone?", options: ["Hello", "Good bye", "Sorry"], correctOption: 0, explanation: "We say hello when we meet." },
  { topic: "Greeting People", question: "What do you say when you want something?", options: ["Give me", "Please", "Now"], correctOption: 1, explanation: "We say please to be polite." },
  { topic: "Greeting People", question: "What do you say when someone gives you a gift?", options: ["Thank you", "Welcome", "Hello"], correctOption: 0, explanation: "We say thank you for gifts." },
  { topic: "Greeting People", question: "What do you say when you hurt someone?", options: ["Happy", "Sorry", "Good"], correctOption: 1, explanation: "We say sorry when we make a mistake." },
  { topic: "Greeting People", question: "What do you say in the afternoon?", options: ["Good morning", "Good afternoon", "Good night"], correctOption: 1, explanation: "We say good afternoon." },
  { topic: "Greeting People", question: "What do you say when leaving?", options: ["Hello", "Hi", "Goodbye"], correctOption: 2, explanation: "We say goodbye when leaving." },
  { topic: "Greeting People", question: "What do you say when someone says 'Thank you'?", options: ["You are welcome", "Sorry", "Please"], correctOption: 0, explanation: "We say 'You are welcome'." },
  { topic: "Greeting People", question: "What do you say in the evening?", options: ["Good morning", "Good evening", "Good night"], correctOption: 1, explanation: "We say good evening." },

  // Vowels and Consonants
  { topic: "Vowels and Consonants", question: "How many vowels are in the English alphabet?", options: ["5", "21", "26"], correctOption: 0, explanation: "The vowels are A, E, I, O, U." },
  { topic: "Vowels and Consonants", question: "Which of these is a vowel?", options: ["B", "E", "D"], correctOption: 1, explanation: "E is a vowel." },
  { topic: "Vowels and Consonants", question: "Which of these is a consonant?", options: ["A", "I", "M"], correctOption: 2, explanation: "M is a consonant." },
  { topic: "Vowels and Consonants", question: "Choose the vowel in 'Cat'.", options: ["C", "A", "T"], correctOption: 1, explanation: "A is the vowel." },
  { topic: "Vowels and Consonants", question: "Choose the vowel in 'Dog'.", options: ["D", "O", "G"], correctOption: 1, explanation: "O is the vowel." },
  { topic: "Vowels and Consonants", question: "Which letter is NOT a vowel?", options: ["U", "O", "S"], correctOption: 2, explanation: "S is a consonant." },
  { topic: "Vowels and Consonants", question: "How many consonants are in the alphabet?", options: ["5", "21", "26"], correctOption: 1, explanation: "26 total - 5 vowels = 21 consonants." },
  { topic: "Vowels and Consonants", question: "Which is the first vowel?", options: ["E", "I", "A"], correctOption: 2, explanation: "A is the first vowel." },
  { topic: "Vowels and Consonants", question: "Which is the last vowel?", options: ["O", "U", "Y"], correctOption: 1, explanation: "U is the fifth vowel." },
  { topic: "Vowels and Consonants", question: "Choose the vowel in 'Sun'.", options: ["S", "U", "N"], correctOption: 1, explanation: "U is the vowel." },

  // Singular and Plural
  { topic: "Singular and Plural", question: "What is the plural of 'Boy'?", options: ["Boyes", "Boys", "Boies"], correctOption: 1, explanation: "We add -s to make boys." },
  { topic: "Singular and Plural", question: "What is the plural of 'Girl'?", options: ["Girls", "Girles", "Girlys"], correctOption: 0, explanation: "Girls is the plural." },
  { topic: "Singular and Plural", question: "What is the plural of 'Cat'?", options: ["Cat", "Cats", "Cates"], correctOption: 1, explanation: "Cats is the plural." },
  { topic: "Singular and Plural", question: "What is the plural of 'Dog'?", options: ["Dogs", "Doges", "Doggi"], correctOption: 0, explanation: "Dogs is the plural." },
  { topic: "Singular and Plural", question: "What is the plural of 'Book'?", options: ["Books", "Bookes", "Bookies"], correctOption: 0, explanation: "Books is the plural." },
  { topic: "Singular and Plural", question: "What is the plural of 'Pen'?", options: ["Penes", "Pens", "Penies"], correctOption: 1, explanation: "Pens is the plural." },
  { topic: "Singular and Plural", question: "What is the plural of 'Apple'?", options: ["Apples", "Applees", "Applis"], correctOption: 0, explanation: "Apples is the plural." },
  { topic: "Singular and Plural", question: "What is the plural of 'Table'?", options: ["Tables", "Tablis", "Tablees"], correctOption: 0, explanation: "Tables is the plural." },
  { topic: "Singular and Plural", question: "What is the plural of 'Chair'?", options: ["Chairs", "Chaires", "Chairis"], correctOption: 0, explanation: "Chairs is the plural." },
  { topic: "Singular and Plural", question: "What is the plural of 'Cup'?", options: ["Cupes", "Cups", "Cupis"], correctOption: 1, explanation: "Cups is the plural." },

  // A and An
  { topic: "Using 'A' and 'An'", question: "We use 'An' before words starting with ___.", options: ["Consonants", "Vowels", "Numbers"], correctOption: 1, explanation: "An is used before vowels (A, E, I, O, U)." },
  { topic: "Using 'A' and 'An'", question: "___ Apple.", options: ["A", "An", "The"], correctOption: 1, explanation: "Apple starts with A (vowel)." },
  { topic: "Using 'A' and 'An'", question: "___ Ball.", options: ["A", "An", "The"], correctOption: 0, explanation: "Ball starts with B (consonant)." },
  { topic: "Using 'A' and 'An'", question: "___ Egg.", options: ["A", "An", "The"], correctOption: 1, explanation: "Egg starts with E (vowel)." },
  { topic: "Using 'A' and 'An'", question: "___ Cat.", options: ["A", "An", "The"], correctOption: 0, explanation: "Cat starts with C (consonant)." },
  { topic: "Using 'A' and 'An'", question: "___ Ice cream.", options: ["A", "An", "The"], correctOption: 1, explanation: "Ice cream starts with I (vowel)." },
  { topic: "Using 'A' and 'An'", question: "___ Orange.", options: ["A", "An", "The"], correctOption: 1, explanation: "Orange starts with O (vowel)." },
  { topic: "Using 'A' and 'An'", question: "___ Umbrella.", options: ["A", "An", "The"], correctOption: 1, explanation: "Umbrella starts with U (vowel)." },
  { topic: "Using 'A' and 'An'", question: "___ Dog.", options: ["A", "An", "The"], correctOption: 0, explanation: "Dog starts with D (consonant)." },
  { topic: "Using 'A' and 'An'", question: "___ Fish.", options: ["A", "An", "The"], correctOption: 0, explanation: "Fish starts with F (consonant)." },

  // Days and Months
  { topic: "Days of the Week", question: "How many days are in a week?", options: ["5", "7", "12"], correctOption: 1, explanation: "There are 7 days in a week." },
  { question: "Which day comes after Monday?", options: ["Sunday", "Tuesday", "Wednesday"], correctOption: 1, explanation: "Monday, Tuesday..." },
  { question: "Which day comes before Friday?", options: ["Thursday", "Saturday", "Wednesday"], correctOption: 0, explanation: "Thursday, Friday..." },
  { question: "What is the first day of the week?", options: ["Monday", "Sunday", "Saturday"], correctOption: 1, explanation: "Sunday is usually the first day." },
  { question: "How many months are in a year?", options: ["7", "10", "12"], correctOption: 2, explanation: "There are 12 months." },
  { question: "What is the first month of the year?", options: ["January", "February", "March"], correctOption: 0, explanation: "January is the first month." },
  { question: "What is the last month of the year?", options: ["November", "December", "October"], correctOption: 1, explanation: "December is the last month." },
  { question: "Which month comes after June?", options: ["May", "July", "August"], correctOption: 1, explanation: "June, July..." },
  { question: "Which month comes before April?", options: ["March", "May", "June"], correctOption: 0, explanation: "March, April..." },
  { question: "Which day is a weekend?", options: ["Monday", "Wednesday", "Saturday"], correctOption: 2, explanation: "Saturday and Sunday are weekends." }
];
