export const PRIMARY_2_ENGLISH_POOL = [
  // Vowels and Consonants
  { topic: "Vowels and Consonants", question: "Which of these is a vowel?", options: ["B", "E", "D"], correctOption: 1, explanation: "The vowels are A, E, I, O, U." },
  { topic: "Vowels and Consonants", question: "How many vowels are in the word 'Apple'?", options: ["1", "2", "3"], correctOption: 1, explanation: "A and E are vowels." },
  { topic: "Vowels and Consonants", question: "Which letter is a consonant?", options: ["I", "O", "M"], correctOption: 2, explanation: "M is a consonant." },
  { topic: "Vowels and Consonants", question: "Choose the vowel in 'Pen'.", options: ["P", "E", "N"], correctOption: 1, explanation: "E is the vowel." },
  { topic: "Vowels and Consonants", question: "Which word starts with a vowel?", options: ["Dog", "Egg", "Cat"], correctOption: 1, explanation: "Egg starts with E." },
  { topic: "Vowels and Consonants", question: "How many consonants are in 'Sun'?", options: ["1", "2", "3"], correctOption: 1, explanation: "S and N are consonants." },
  { topic: "Vowels and Consonants", question: "Which is the third vowel?", options: ["E", "I", "O"], correctOption: 1, explanation: "A, E, I..." },
  { topic: "Vowels and Consonants", question: "Which letter is NOT a vowel?", options: ["U", "A", "T"], correctOption: 2, explanation: "T is a consonant." },
  { topic: "Vowels and Consonants", question: "Choose the word with two vowels.", options: ["Sky", "Book", "Fly"], correctOption: 1, explanation: "Book has two 'o's." },
  { topic: "Vowels and Consonants", question: "Which vowel comes after 'O'?", options: ["U", "I", "E"], correctOption: 0, explanation: "A, E, I, O, U." },

  // Opposites (Antonyms)
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Hard'?", options: ["Soft", "Strong", "Heavy"], correctOption: 0, explanation: "Soft is the opposite of hard." },
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Near'?", options: ["Close", "Far", "Next"], correctOption: 1, explanation: "Far is the opposite of near." },
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Heavy'?", options: ["Big", "Light", "Small"], correctOption: 1, explanation: "Light is the opposite of heavy." },
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Fast'?", options: ["Quick", "Slow", "Run"], correctOption: 1, explanation: "Slow is the opposite of fast." },
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Clean'?", options: ["Dirty", "Neat", "Wash"], correctOption: 0, explanation: "Dirty is the opposite of clean." },
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Rich'?", options: ["Poor", "Money", "Gold"], correctOption: 0, explanation: "Poor is the opposite of rich." },
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Laugh'?", options: ["Smile", "Cry", "Happy"], correctOption: 1, explanation: "Cry is the opposite of laugh." },
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Full'?", options: ["Empty", "Half", "Many"], correctOption: 0, explanation: "Empty is the opposite of full." },
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Old'?", options: ["New", "Young", "Both A and B"], correctOption: 2, explanation: "New (for things) and Young (for people) are opposites of old." },
  { topic: "Opposites (Antonyms)", question: "What is the opposite of 'Sweet'?", options: ["Sugar", "Bitter", "Tasty"], correctOption: 1, explanation: "Bitter is the opposite of sweet." },

  // Compound Words
  { topic: "Compound Words", question: "Sun + Flower = ___", options: ["Sunlight", "Sunflower", "Sunflow"], correctOption: 1, explanation: "Sun and Flower make Sunflower." },
  { topic: "Compound Words", question: "Rain + Bow = ___", options: ["Rainbow", "Raincoat", "Rainy"], correctOption: 0, explanation: "Rain and Bow make Rainbow." },
  { topic: "Compound Words", question: "Star + Fish = ___", options: ["Starry", "Starfish", "Fishing"], correctOption: 1, explanation: "Star and Fish make Starfish." },
  { topic: "Compound Words", question: "Foot + Ball = ___", options: ["Football", "Footstep", "Ballfoot"], correctOption: 0, explanation: "Foot and Ball make Football." },
  { topic: "Compound Words", question: "Tooth + Brush = ___", options: ["Toothpaste", "Toothbrush", "Brushing"], correctOption: 1, explanation: "Tooth and Brush make Toothbrush." },
  { topic: "Compound Words", question: "Pan + Cake = ___", options: ["Pancake", "Panfry", "Cakepan"], correctOption: 0, explanation: "Pan and Cake make Pancake." },
  { topic: "Compound Words", question: "Butter + Fly = ___", options: ["Buttercup", "Butterfly", "Flying"], correctOption: 1, explanation: "Butter and Fly make Butterfly." },
  { topic: "Compound Words", question: "Key + Board = ___", options: ["Keyboard", "Keyhole", "Boardkey"], correctOption: 0, explanation: "Key and Board make Keyboard." },
  { topic: "Compound Words", question: "Snow + Man = ___", options: ["Snowball", "Snowman", "Mansnow"], correctOption: 1, explanation: "Snow and Man make Snowman." },
  { topic: "Compound Words", question: "Hand + Bag = ___", options: ["Handbag", "Handshake", "Baghand"], correctOption: 0, explanation: "Hand and Bag make Handbag." },

  // Singular and Plural
  { topic: "Singular and Plural", question: "What is the plural of 'Box'?", options: ["Boxs", "Boxes", "Boxies"], correctOption: 1, explanation: "Words ending in -x add -es." },
  { topic: "Singular and Plural", question: "What is the plural of 'Dish'?", options: ["Dishs", "Dishes", "Dishies"], correctOption: 1, explanation: "Words ending in -sh add -es." },
  { topic: "Singular and Plural", question: "What is the plural of 'Bus'?", options: ["Buses", "Buss", "Busies"], correctOption: 0, explanation: "Words ending in -s add -es." },
  { topic: "Singular and Plural", question: "What is the plural of 'Watch'?", options: ["Watchs", "Watches", "Watchies"], correctOption: 1, explanation: "Words ending in -ch add -es." },
  { topic: "Singular and Plural", question: "What is the plural of 'Glass'?", options: ["Glasss", "Glasses", "Glassies"], correctOption: 1, explanation: "Words ending in -ss add -es." },
  { topic: "Singular and Plural", question: "What is the plural of 'Baby'?", options: ["Babys", "Babies", "Babyes"], correctOption: 1, explanation: "Change -y to -ies." },
  { topic: "Singular and Plural", question: "What is the plural of 'City'?", options: ["Citys", "Cities", "Cityes"], correctOption: 1, explanation: "Change -y to -ies." },
  { topic: "Singular and Plural", question: "What is the plural of 'Leaf'?", options: ["Leafs", "Leaves", "Leafes"], correctOption: 1, explanation: "Change -f to -ves." },
  { topic: "Singular and Plural", question: "What is the plural of 'Knife'?", options: ["Knifes", "Knives", "Knifves"], correctOption: 1, explanation: "Change -fe to -ves." },
  { topic: "Singular and Plural", question: "What is the plural of 'Man'?", options: ["Mans", "Men", "Mens"], correctOption: 1, explanation: "Man changes to Men." },

  // Articles (A and An)
  { topic: "Articles (A and An)", question: "___ Elephant.", options: ["A", "An", "The"], correctOption: 1, explanation: "Elephant starts with E (vowel)." },
  { topic: "Articles (A and An)", question: "___ Umbrella.", options: ["A", "An", "The"], correctOption: 1, explanation: "Umbrella starts with U (vowel)." },
  { topic: "Articles (A and An)", question: "___ Computer.", options: ["A", "An", "The"], correctOption: 0, explanation: "Computer starts with C (consonant)." },
  { topic: "Articles (A and An)", question: "___ Orange.", options: ["A", "An", "The"], correctOption: 1, explanation: "Orange starts with O (vowel)." },
  { topic: "Articles (A and An)", question: "___ House.", options: ["A", "An", "The"], correctOption: 0, explanation: "House starts with H (consonant)." },
  { topic: "Articles (A and An)", question: "___ Aeroplane.", options: ["A", "An", "The"], correctOption: 1, explanation: "Aeroplane starts with A (vowel)." },
  { topic: "Articles (A and An)", question: "___ Uniform.", options: ["A", "An", "The"], correctOption: 0, explanation: "Uniform sounds like 'yoo' (consonant sound)." },
  { topic: "Articles (A and An)", question: "___ Honest man.", options: ["A", "An", "The"], correctOption: 1, explanation: "Honest starts with a silent H (vowel sound)." },
  { topic: "Articles (A and An)", question: "___ Book.", options: ["A", "An", "The"], correctOption: 0, explanation: "Book starts with B (consonant)." },
  { topic: "Articles (A and An)", question: "___ Island.", options: ["A", "An", "The"], correctOption: 1, explanation: "Island starts with I (vowel)." },

  // Days and Months
  { topic: "Days and Months", question: "Which day comes after Tuesday?", options: ["Monday", "Wednesday", "Thursday"], correctOption: 1, explanation: "Tuesday, Wednesday..." },
  { topic: "Days and Months", question: "Which day comes before Sunday?", options: ["Saturday", "Friday", "Monday"], correctOption: 0, explanation: "Saturday, Sunday." },
  { topic: "Days and Months", question: "How many months are in a year?", options: ["10", "12", "7"], correctOption: 1, explanation: "There are 12 months." },
  { topic: "Days and Months", question: "Which is the first month of the year?", options: ["January", "February", "March"], correctOption: 0, explanation: "January is the first month." },
  { topic: "Days and Months", question: "Which is the last month of the year?", options: ["November", "December", "October"], correctOption: 1, explanation: "December is the last month." },
  { topic: "Days and Months", question: "Which month comes after June?", options: ["May", "July", "August"], correctOption: 1, explanation: "June, July..." },
  { topic: "Days and Months", question: "Which month comes before April?", options: ["March", "May", "June"], correctOption: 0, explanation: "March, April." },
  { topic: "Days and Months", question: "Which day is the middle of the week?", options: ["Tuesday", "Wednesday", "Thursday"], correctOption: 1, explanation: "Wednesday is often called hump day." },
  { topic: "Days and Months", question: "Which month has the fewest days?", options: ["January", "February", "March"], correctOption: 1, explanation: "February has 28 or 29 days." },
  { topic: "Days and Months", question: "Which month do we celebrate Christmas?", options: ["January", "December", "August"], correctOption: 1, explanation: "Christmas is in December." },

  // Nouns (Naming Words)
  { topic: "Nouns (Naming Words)", question: "Which is a naming word for a person?", options: ["Teacher", "School", "Book"], correctOption: 0, explanation: "Teacher is a person." },
  { topic: "Nouns (Naming Words)", question: "Which is a naming word for a place?", options: ["John", "Lagos", "Pencil"], correctOption: 1, explanation: "Lagos is a place." },
  { topic: "Nouns (Naming Words)", question: "Which is a naming word for a thing?", options: ["Sister", "Market", "Table"], correctOption: 2, explanation: "Table is a thing." },
  { topic: "Nouns (Naming Words)", question: "Identify the noun: 'The cat is sleeping.'", options: ["Cat", "Sleeping", "Is"], correctOption: 0, explanation: "Cat is the naming word." },
  { topic: "Nouns (Naming Words)", question: "Which is a proper noun?", options: ["boy", "Nigeria", "country"], correctOption: 1, explanation: "Nigeria is a specific name." },
  { topic: "Nouns (Naming Words)", question: "Proper nouns always start with a ___ letter.", options: ["Small", "Capital", "Fancy"], correctOption: 1, explanation: "Names start with capitals." },
  { topic: "Nouns (Naming Words)", question: "Which is a common noun?", options: ["London", "City", "Africa"], correctOption: 1, explanation: "City is a general name." },
  { topic: "Nouns (Naming Words)", question: "Identify the noun: 'I have a red ball.'", options: ["Red", "Ball", "Have"], correctOption: 1, explanation: "Ball is a thing." },
  { topic: "Nouns (Naming Words)", question: "Which is a naming word for an animal?", options: ["Lion", "Forest", "Hunter"], correctOption: 0, explanation: "Lion is an animal." },
  { topic: "Nouns (Naming Words)", question: "Identify the noun: 'Sarah is my friend.'", options: ["Sarah", "Friend", "Both A and B"], correctOption: 2, explanation: "Sarah and Friend are both nouns." },

  // Verbs (Action Words)
  { topic: "Verbs (Action Words)", question: "Which is an action word?", options: ["Run", "Fast", "Shoes"], correctOption: 0, explanation: "Run is something you do." },
  { topic: "Verbs (Action Words)", question: "Identify the verb: 'The bird flies.'", options: ["Bird", "Flies", "The"], correctOption: 1, explanation: "Flies is the action." },
  { topic: "Verbs (Action Words)", question: "Which word tells us what a fish does?", options: ["Swim", "Water", "Blue"], correctOption: 0, explanation: "Fish swim." },
  { topic: "Verbs (Action Words)", question: "Identify the verb: 'I eat an apple.'", options: ["I", "Eat", "Apple"], correctOption: 1, explanation: "Eat is the action." },
  { topic: "Verbs (Action Words)", question: "Which is an action word?", options: ["Sleep", "Bed", "Pillow"], correctOption: 0, explanation: "Sleep is an action." },
  { topic: "Verbs (Action Words)", question: "Identify the verb: 'She writes a letter.'", options: ["She", "Writes", "Letter"], correctOption: 1, explanation: "Writes is the action." },
  { topic: "Verbs (Action Words)", question: "What do you do with a pencil?", options: ["Write", "Eat", "Jump"], correctOption: 0, explanation: "You write with a pencil." },
  { topic: "Verbs (Action Words)", question: "Identify the verb: 'The dog barks.'", options: ["Dog", "Barks", "Loud"], correctOption: 1, explanation: "Barks is the action." },
  { topic: "Verbs (Action Words)", question: "Which is an action word?", options: ["Dance", "Music", "Radio"], correctOption: 0, explanation: "Dance is an action." },
  { topic: "Verbs (Action Words)", question: "Identify the verb: 'We play football.'", options: ["We", "Play", "Football"], correctOption: 1, explanation: "Play is the action." },

  // Adjectives (Describing Words)
  { topic: "Adjectives (Describing Words)", question: "Which word describes a color?", options: ["Red", "Big", "Fast"], correctOption: 0, explanation: "Red is a color." },
  { topic: "Adjectives (Describing Words)", question: "Identify the adjective: 'The big elephant.'", options: ["The", "Big", "Elephant"], correctOption: 1, explanation: "Big describes the elephant." },
  { topic: "Adjectives (Describing Words)", question: "Which word describes how something feels?", options: ["Cold", "Blue", "Run"], correctOption: 0, explanation: "Cold describes feeling." },
  { topic: "Adjectives (Describing Words)", question: "Identify the adjective: 'A happy girl.'", options: ["A", "Happy", "Girl"], correctOption: 1, explanation: "Happy describes the girl." },
  { topic: "Adjectives (Describing Words)", question: "Which word describes a shape?", options: ["Round", "Sweet", "Loud"], correctOption: 0, explanation: "Round is a shape." },
  { topic: "Adjectives (Describing Words)", question: "Identify the adjective: 'The tall tree.'", options: ["Tall", "Tree", "The"], correctOption: 0, explanation: "Tall describes the tree." },
  { topic: "Adjectives (Describing Words)", question: "Which word describes a sound?", options: ["Loud", "Green", "Soft"], correctOption: 0, explanation: "Loud describes sound." },
  { topic: "Adjectives (Describing Words)", question: "Identify the adjective: 'A small mouse.'", options: ["A", "Small", "Mouse"], correctOption: 1, explanation: "Small describes the mouse." },
  { topic: "Adjectives (Describing Words)", question: "Which word describes a taste?", options: ["Sweet", "Fast", "High"], correctOption: 0, explanation: "Sweet is a taste." },
  { topic: "Adjectives (Describing Words)", question: "Identify the adjective: 'The hot sun.'", options: ["The", "Hot", "Sun"], correctOption: 1, explanation: "Hot describes the sun." },

  // Punctuation and Sentences
  { topic: "Punctuation and Sentences", question: "A sentence always starts with a ___ letter.", options: ["Small", "Capital", "Big"], correctOption: 1, explanation: "Sentences start with capitals." },
  { topic: "Punctuation and Sentences", question: "What do we put at the end of a telling sentence?", options: ["Full stop (.)", "Question mark (?)", "Comma (,)"], correctOption: 0, explanation: "Use a full stop." },
  { topic: "Punctuation and Sentences", question: "What do we put at the end of a question?", options: ["Full stop (.)", "Question mark (?)", "Comma (,)"], correctOption: 1, explanation: "Use a question mark." },
  { topic: "Punctuation and Sentences", question: "Which sentence is correct?", options: ["i am happy.", "I am happy.", "I am happy"], correctOption: 1, explanation: "Starts with capital and ends with full stop." },
  { topic: "Punctuation and Sentences", question: "Where does the question mark go? 'How are you'", options: ["At the start", "At the end", "In the middle"], correctOption: 1, explanation: "At the end." },
  { topic: "Punctuation and Sentences", question: "Which is a question?", options: ["I like cake.", "What is your name?", "The sun is hot."], correctOption: 1, explanation: "It asks something." },
  { topic: "Punctuation and Sentences", question: "Which is a telling sentence?", options: ["Where is the cat?", "The cat is on the mat.", "Is the cat hungry?"], correctOption: 1, explanation: "It tells us something." },
  { topic: "Punctuation and Sentences", question: "We use a ___ to separate items in a list.", options: ["Full stop", "Comma", "Question mark"], correctOption: 1, explanation: "Use a comma." },
  { topic: "Punctuation and Sentences", question: "Which is correct?", options: ["Apples, bananas and pears.", "Apples bananas and pears.", "Apples. bananas. and pears."], correctOption: 0, explanation: "Uses a comma correctly." },
  { topic: "Punctuation and Sentences", question: "A name of a person should start with a ___.", options: ["Small letter", "Capital letter", "Number"], correctOption: 1, explanation: "Names are proper nouns." }
];
