export const PRIMARY_3_MATH_POOL = [
  // Numbers up to 1000 (Place Value)
  { topic: "Numbers up to 1000 (Place Value)", question: "In the number 456, which digit is in the Hundreds place?", options: ["4", "5", "6"], correctOption: 0, explanation: "456 is 4 hundreds, 5 tens, and 6 units." },
  { topic: "Numbers up to 1000 (Place Value)", question: "What is the value of 7 in 702?", options: ["7", "70", "700"], correctOption: 2, explanation: "The 7 is in the hundreds place." },
  { topic: "Numbers up to 1000 (Place Value)", question: "What number is 9 hundreds, 0 tens, and 5 units?", options: ["95", "905", "950"], correctOption: 1, explanation: "900 + 0 + 5 = 905." },
  { topic: "Numbers up to 1000 (Place Value)", question: "How many tens are in 120?", options: ["1", "2", "12"], correctOption: 1, explanation: "120 has 2 tens (and 1 hundred)." },
  { topic: "Numbers up to 1000 (Place Value)", question: "What is the smallest 3-digit number?", options: ["100", "111", "999"], correctOption: 0, explanation: "100 is the first 3-digit number." },
  { topic: "Numbers up to 1000 (Place Value)", question: "What is the largest 3-digit number?", options: ["100", "900", "999"], correctOption: 2, explanation: "999 is the last 3-digit number." },
  { topic: "Numbers up to 1000 (Place Value)", question: "What is 300 + 40 + 8?", options: ["348", "384", "438"], correctOption: 0, explanation: "Standard form of the number." },
  { topic: "Numbers up to 1000 (Place Value)", question: "In 819, the 1 is in the ___ place.", options: ["Hundreds", "Tens", "Units"], correctOption: 1, explanation: "The middle digit is the tens place." },
  { topic: "Numbers up to 1000 (Place Value)", question: "What number comes after 999?", options: ["990", "1000", "1001"], correctOption: 1, explanation: "999 + 1 = 1000." },
  { topic: "Numbers up to 1000 (Place Value)", question: "How many hundreds are in 500?", options: ["5", "50", "500"], correctOption: 0, explanation: "500 has 5 hundreds." },

  // Addition (3-digit numbers)
  { topic: "Addition (3-digit numbers)", question: "What is 100 + 200?", options: ["200", "300", "400"], correctOption: 1, explanation: "1 hundred + 2 hundreds = 3 hundreds." },
  { topic: "Addition (3-digit numbers)", question: "What is 150 + 50?", options: ["100", "200", "250"], correctOption: 1, explanation: "150 + 50 = 200." },
  { topic: "Addition (3-digit numbers)", question: "What is 400 + 120?", options: ["500", "520", "420"], correctOption: 1, explanation: "400 + 100 = 500, then add 20." },
  { topic: "Addition (3-digit numbers)", question: "What is 250 + 250?", options: ["400", "500", "600"], correctOption: 1, explanation: "250 and 250 make 500." },
  { topic: "Addition (3-digit numbers)", question: "What is 125 + 125?", options: ["200", "250", "300"], correctOption: 1, explanation: "125 + 125 = 250." },
  { topic: "Addition (3-digit numbers)", question: "What is 310 + 40?", options: ["340", "350", "360"], correctOption: 1, explanation: "310 + 40 = 350." },
  { topic: "Addition (3-digit numbers)", question: "What is 500 + 500?", options: ["900", "1000", "1100"], correctOption: 1, explanation: "500 and 500 make 1000." },
  { topic: "Addition (3-digit numbers)", question: "What is 200 + 350?", options: ["450", "550", "650"], correctOption: 1, explanation: "200 + 300 = 500, then add 50." },
  { topic: "Addition (3-digit numbers)", question: "What is 105 + 105?", options: ["200", "210", "220"], correctOption: 1, explanation: "105 + 105 = 210." },
  { topic: "Addition (3-digit numbers)", question: "What is 600 + 400?", options: ["900", "1000", "1200"], correctOption: 1, explanation: "600 + 400 = 1000." },

  // Subtraction (3-digit numbers)
  { topic: "Subtraction (3-digit numbers)", question: "What is 500 - 200?", options: ["200", "300", "400"], correctOption: 1, explanation: "5 hundreds - 2 hundreds = 3 hundreds." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 250 - 50?", options: ["150", "200", "300"], correctOption: 1, explanation: "250 take away 50 is 200." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 1000 - 500?", options: ["400", "500", "600"], correctOption: 1, explanation: "Half of 1000 is 500." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 300 - 150?", options: ["100", "150", "200"], correctOption: 1, explanation: "300 - 150 = 150." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 450 - 100?", options: ["350", "400", "550"], correctOption: 0, explanation: "Subtract 1 from the hundreds place." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 800 - 400?", options: ["300", "400", "500"], correctOption: 1, explanation: "8 - 4 = 4." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 120 - 20?", options: ["100", "110", "140"], correctOption: 0, explanation: "120 - 20 = 100." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 600 - 300?", options: ["200", "300", "400"], correctOption: 1, explanation: "600 - 300 = 300." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 900 - 100?", options: ["700", "800", "1000"], correctOption: 1, explanation: "9 - 1 = 8." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 1000 - 1?", options: ["990", "999", "1001"], correctOption: 1, explanation: "Counting back from 1000." },

  // Multiplication (Tables up to 12)
  { topic: "Multiplication Tables", question: "What is 3 x 4?", options: ["7", "12", "15"], correctOption: 1, explanation: "3 groups of 4 is 12." },
  { topic: "Multiplication Tables", question: "What is 5 x 6?", options: ["25", "30", "35"], correctOption: 1, explanation: "5 groups of 6 is 30." },
  { topic: "Multiplication Tables", question: "What is 2 x 12?", options: ["22", "24", "26"], correctOption: 1, explanation: "2 groups of 12 is 24." },
  { topic: "Multiplication Tables", question: "What is 4 x 4?", options: ["8", "16", "20"], correctOption: 1, explanation: "4 x 4 = 16." },
  { topic: "Multiplication Tables", question: "What is 10 x 5?", options: ["15", "50", "55"], correctOption: 1, explanation: "10 groups of 5 is 50." },
  { topic: "Multiplication Tables", question: "What is 3 x 8?", options: ["21", "24", "27"], correctOption: 1, explanation: "3 x 8 = 24." },
  { topic: "Multiplication Tables", question: "What is 5 x 9?", options: ["40", "45", "50"], correctOption: 1, explanation: "5 x 9 = 45." },
  { topic: "Multiplication Tables", question: "What is 11 x 2?", options: ["13", "22", "33"], correctOption: 1, explanation: "11 x 2 = 22." },
  { topic: "Multiplication Tables", question: "What is 4 x 5?", options: ["15", "20", "25"], correctOption: 1, explanation: "4 x 5 = 20." },
  { topic: "Multiplication Tables", question: "What is 12 x 1?", options: ["1", "12", "13"], correctOption: 1, explanation: "Any number times 1 is itself." },

  // Division as Sharing
  { topic: "Division as Sharing", question: "What is 12 ÷ 3?", options: ["3", "4", "5"], correctOption: 1, explanation: "12 shared into 3 groups is 4." },
  { topic: "Division as Sharing", question: "What is 20 ÷ 4?", options: ["4", "5", "6"], correctOption: 1, explanation: "20 shared into 4 groups is 5." },
  { topic: "Division as Sharing", question: "What is 15 ÷ 5?", options: ["2", "3", "4"], correctOption: 1, explanation: "15 shared into 5 groups is 3." },
  { topic: "Division as Sharing", question: "What is 18 ÷ 2?", options: ["8", "9", "10"], correctOption: 1, explanation: "18 shared into 2 groups is 9." },
  { topic: "Division as Sharing", question: "What is 30 ÷ 5?", options: ["5", "6", "7"], correctOption: 1, explanation: "30 shared into 5 groups is 6." },
  { topic: "Division as Sharing", question: "What is 24 ÷ 3?", options: ["6", "8", "10"], correctOption: 1, explanation: "24 shared into 3 groups is 8." },
  { topic: "Division as Sharing", question: "What is 10 ÷ 2?", options: ["4", "5", "6"], correctOption: 1, explanation: "Half of 10 is 5." },
  { topic: "Division as Sharing", question: "What is 40 ÷ 10?", options: ["4", "10", "40"], correctOption: 0, explanation: "40 shared into 10 groups is 4." },
  { topic: "Division as Sharing", question: "What is 16 ÷ 4?", options: ["3", "4", "5"], correctOption: 1, explanation: "4 x 4 = 16." },
  { topic: "Division as Sharing", question: "What is 21 ÷ 3?", options: ["6", "7", "8"], correctOption: 1, explanation: "3 x 7 = 21." },

  // Fractions: Halves and Quarters
  { topic: "Fractions: Halves and Quarters", question: "What is 1/2 of 20?", options: ["5", "10", "15"], correctOption: 1, explanation: "Half of 20 is 10." },
  { topic: "Fractions: Halves and Quarters", question: "What is 1/4 of 12?", options: ["2", "3", "4"], correctOption: 1, explanation: "12 divided by 4 is 3." },
  { topic: "Fractions: Halves and Quarters", question: "How many thirds make a whole?", options: ["2", "3", "4"], correctOption: 1, explanation: "Three thirds make one whole." },
  { topic: "Fractions: Halves and Quarters", question: "What is 1/3 of 9?", options: ["2", "3", "4"], correctOption: 1, explanation: "9 divided by 3 is 3." },
  { topic: "Fractions: Halves and Quarters", question: "Which is smaller: 1/2 or 1/3?", options: ["1/2", "1/3", "Same"], correctOption: 1, explanation: "A third is smaller than a half." },
  { topic: "Fractions: Halves and Quarters", question: "What is 1/4 of 20?", options: ["4", "5", "6"], correctOption: 1, explanation: "20 divided by 4 is 5." },
  { topic: "Fractions: Halves and Quarters", question: "What is 1/2 of 100?", options: ["25", "50", "75"], correctOption: 1, explanation: "Half of 100 is 50." },
  { topic: "Fractions: Halves and Quarters", question: "How many quarters make a half?", options: ["1", "2", "4"], correctOption: 1, explanation: "Two quarters make a half." },
  { topic: "Fractions: Halves and Quarters", question: "What is 1/3 of 15?", options: ["3", "5", "15"], correctOption: 1, explanation: "15 divided by 3 is 5." },
  { topic: "Fractions: Halves and Quarters", question: "Which is bigger: 1/4 or 1/8?", options: ["1/4", "1/8", "Same"], correctOption: 0, explanation: "A quarter is bigger than an eighth." },

  // Measuring Length
  { topic: "Measuring Length", question: "How many centimeters are in 1 meter?", options: ["10cm", "100cm", "1000cm"], correctOption: 1, explanation: "1m = 100cm." },
  { topic: "Measuring Length", question: "What unit do we use for long distances?", options: ["Meters", "Kilometers", "Centimeters"], correctOption: 1, explanation: "Kilometers (km) measure long distances." },
  { topic: "Measuring Length", question: "How many grams are in 1 kilogram?", options: ["100g", "500g", "1000g"], correctOption: 2, explanation: "1kg = 1000g." },
  { topic: "Measuring Length", question: "How many milliliters are in 1 liter?", options: ["100ml", "500ml", "1000ml"], correctOption: 2, explanation: "1L = 1000ml." },
  { topic: "Measuring Length", question: "Which is heavier: 1kg or 500g?", options: ["1kg", "500g", "Same"], correctOption: 0, explanation: "1kg is 1000g, which is more than 500g." },
  { topic: "Measuring Length", question: "Which is longer: 2m or 200cm?", options: ["2m", "200cm", "They are same"], correctOption: 2, explanation: "2m = 200cm." },
  { topic: "Measuring Length", question: "What do we use to measure liquid?", options: ["Ruler", "Measuring Cup", "Scale"], correctOption: 1, explanation: "Measuring cups measure volume/capacity." },
  { topic: "Measuring Length", question: "Which is more: 1 Liter or 2 Liters?", options: ["1 Liter", "2 Liters"], correctOption: 1, explanation: "2 is more than 1." },
  { topic: "Measuring Length", question: "How many meters are in 1 kilometer?", options: ["100m", "500m", "1000m"], correctOption: 2, explanation: "1km = 1000m." },
  { topic: "Measuring Length", question: "Which is lighter: 10g or 10kg?", options: ["10g", "10kg"], correctOption: 0, explanation: "Grams are much smaller than kilograms." },

  // Telling Time
  { topic: "Telling Time", question: "How many minutes are in 1 hour?", options: ["30", "60", "100"], correctOption: 1, explanation: "1 hour = 60 minutes." },
  { topic: "Telling Time", question: "What time is 'quarter past 4'?", options: ["4:15", "4:30", "4:45"], correctOption: 0, explanation: "Quarter past means 15 minutes." },
  { topic: "Telling Time", question: "What time is 'quarter to 6'?", options: ["5:45", "6:15", "6:45"], correctOption: 0, explanation: "Quarter to means 15 minutes before the hour." },
  { topic: "Telling Time", question: "How many seconds are in 1 minute?", options: ["30", "60", "100"], correctOption: 1, explanation: "1 minute = 60 seconds." },
  { topic: "Telling Time", question: "If it is 10:15, how many minutes past 10 is it?", options: ["10", "15", "20"], correctOption: 1, explanation: "The minutes are 15." },
  { topic: "Telling Time", question: "What is 3:30 called?", options: ["Quarter past 3", "Half past 3", "Quarter to 4"], correctOption: 1, explanation: "30 minutes is half an hour." },
  { topic: "Telling Time", question: "How many minutes in half an hour?", options: ["15", "30", "60"], correctOption: 1, explanation: "Half of 60 is 30." },
  { topic: "Telling Time", question: "What time is 15 minutes after 2:00?", options: ["2:15", "2:30", "2:45"], correctOption: 0, explanation: "2:00 + 15 mins = 2:15." },
  { topic: "Telling Time", question: "How many hours in half a day?", options: ["6", "12", "24"], correctOption: 1, explanation: "Half of 24 is 12." },
  { topic: "Telling Time", question: "What time is 10 minutes to 5?", options: ["4:50", "5:10", "5:50"], correctOption: 0, explanation: "60 - 10 = 50, so 4:50." },

  // Money: Addition
  { topic: "Money: Addition", question: "What is N100 + N50?", options: ["N100", "N150", "N200"], correctOption: 1, explanation: "100 + 50 = 150." },
  { topic: "Money: Addition", question: "If you have N500 and spend N200, how much is left?", options: ["N200", "N300", "N700"], correctOption: 1, explanation: "500 - 200 = 300." },
  { topic: "Money: Addition", question: "What is N200 + N200?", options: ["N200", "N400", "N500"], correctOption: 1, explanation: "200 + 200 = 400." },
  { topic: "Money: Addition", question: "How many 50 Naira notes make 200 Naira?", options: ["2", "4", "6"], correctOption: 1, explanation: "50, 100, 150, 200." },
  { topic: "Money: Addition", question: "What is N1000 - N500?", options: ["N400", "N500", "N600"], correctOption: 1, explanation: "Half of 1000 is 500." },
  { topic: "Money: Addition", question: "If a book costs N350 and you pay N500, what is your change?", options: ["N100", "N150", "N200"], correctOption: 1, explanation: "500 - 350 = 150." },
  { topic: "Money: Addition", question: "What is N50 + N50 + N50?", options: ["N100", "N150", "N200"], correctOption: 1, explanation: "50, 100, 150." },
  { topic: "Money: Addition", question: "Which is more: N1000 or two N500 notes?", options: ["N1000", "Two N500 notes", "They are same"], correctOption: 2, explanation: "500 + 500 = 1000." },
  { topic: "Money: Addition", question: "What is N700 + N300?", options: ["N900", "N1000", "N1100"], correctOption: 1, explanation: "700 + 300 = 1000." },
  { topic: "Money: Addition", question: "If you buy two toys for N100 each, how much total?", options: ["N100", "N200", "N300"], correctOption: 1, explanation: "100 + 100 = 200." },

  // Perimeter
  { topic: "Perimeter", question: "What is the distance around a shape called?", options: ["Area", "Perimeter", "Volume"], correctOption: 1, explanation: "Perimeter is the boundary length." },
  { topic: "Perimeter", question: "What is the perimeter of a square with 2cm sides?", options: ["4cm", "6cm", "8cm"], correctOption: 2, explanation: "2 + 2 + 2 + 2 = 8cm." },
  { topic: "Perimeter", question: "How many sides does a hexagon have?", options: ["5", "6", "8"], correctOption: 1, explanation: "A hexagon has 6 sides." },
  { topic: "Perimeter", question: "What is the perimeter of a triangle with sides 3cm, 4cm, and 5cm?", options: ["10cm", "12cm", "15cm"], correctOption: 1, explanation: "3 + 4 + 5 = 12cm." },
  { topic: "Perimeter", question: "Which shape has 8 sides?", options: ["Hexagon", "Heptagon", "Octagon"], correctOption: 2, explanation: "An octagon has 8 sides." },
  { topic: "Perimeter", question: "How many faces does a cube have?", options: ["4", "6", "8"], correctOption: 1, explanation: "A cube has 6 square faces." },
  { topic: "Perimeter", question: "A cylinder has ___ flat faces.", options: ["1", "2", "3"], correctOption: 1, explanation: "A cylinder has 2 circular flat faces." },
  { topic: "Perimeter", question: "Which shape looks like a ball?", options: ["Circle", "Sphere", "Cylinder"], correctOption: 1, explanation: "A sphere is the 3D shape." },
  { topic: "Perimeter", question: "What is the perimeter of a rectangle with length 5cm and width 2cm?", options: ["7cm", "10cm", "14cm"], correctOption: 2, explanation: "5 + 2 + 5 + 2 = 14cm." },
  { topic: "Perimeter", question: "How many corners does a triangle have?", options: ["2", "3", "4"], correctOption: 1, explanation: "A triangle has 3 corners." },

  // Mixed Review
  { topic: "Numbers up to 1000 (Place Value)", question: "What is 100 x 2?", options: ["100", "200", "300"], correctOption: 1, explanation: "100 + 100 = 200." },
  { topic: "Division as Sharing", question: "What is 500 ÷ 2?", options: ["200", "250", "300"], correctOption: 1, explanation: "Half of 500 is 250." },
  { topic: "Numbers up to 1000 (Place Value)", question: "Which number is the largest?", options: ["789", "879", "978"], correctOption: 2, explanation: "978 has the most hundreds." },
  { topic: "Multiplication Tables", question: "What is 12 x 2?", options: ["22", "24", "26"], correctOption: 1, explanation: "12 + 12 = 24." },
  { topic: "Subtraction (3-digit numbers)", question: "What is 100 - 25?", options: ["50", "75", "85"], correctOption: 1, explanation: "100 - 25 = 75." },
  { topic: "Multiplication Tables", question: "How many days in 2 weeks?", options: ["7", "10", "14"], correctOption: 2, explanation: "7 x 2 = 14." },
  { topic: "Multiplication Tables", question: "What is 3 x 3 x 3?", options: ["9", "18", "27"], correctOption: 2, explanation: "3x3=9, 9x3=27." },
  { topic: "Numbers up to 1000 (Place Value)", question: "Which number is even?", options: ["101", "202", "303"], correctOption: 1, explanation: "202 ends in an even digit." },
  { topic: "Fractions: Halves and Quarters", question: "What is 1/4 of 100?", options: ["20", "25", "50"], correctOption: 1, explanation: "100 divided by 4 is 25." },
  { topic: "Subtraction (3-digit numbers)", question: "What number is 10 less than 100?", options: ["80", "90", "110"], correctOption: 1, explanation: "100 - 10 = 90." }
];
