import { Quiz } from '../types';

export const REVISION_QUIZZES: Quiz[] = [
  // Primary 1
  { id: 'p1-eng-1', title: 'P1 English: Phonics', level: 'Primary 1', subject: 'English', questions: [{ question: 'Which letter makes the /s/ sound?', options: ['S', 'A', 'T'], correctOption: 0 }, { question: 'Which word starts with /a/?', options: ['Tap', 'Ant', 'Pan'], correctOption: 1 }], timeLimit: 5, rewardPoints: 10 },
  { id: 'p1-math-1', title: 'P1 Math: Counting', level: 'Primary 1', subject: 'Math', questions: [{ question: 'What comes after 5?', options: ['4', '6', '7'], correctOption: 1 }, { question: 'How many fingers on one hand?', options: ['4', '5', '6'], correctOption: 1 }], timeLimit: 5, rewardPoints: 10 },
  { id: 'p1-sci-1', title: 'P1 Science: Living Things', level: 'Primary 1', subject: 'Science', questions: [{ question: 'Is a dog living?', options: ['Yes', 'No'], correctOption: 0 }, { question: 'Which needs food?', options: ['Stone', 'Bird', 'Car'], correctOption: 1 }], timeLimit: 5, rewardPoints: 10 },
  // Primary 2
  { id: 'p2-eng-1', title: 'P2 English: Vowels', level: 'Primary 2', subject: 'English', questions: [{ question: 'Which is a vowel?', options: ['B', 'E', 'D'], correctOption: 1 }, { question: 'How many vowels are there?', options: ['3', '5', '7'], correctOption: 1 }], timeLimit: 10, rewardPoints: 15 },
  { id: 'p2-math-1', title: 'P2 Math: Place Value', level: 'Primary 2', subject: 'Math', questions: [{ question: 'In 24, what is the tens digit?', options: ['2', '4', '6'], correctOption: 0 }, { question: 'What is 10 + 5?', options: ['12', '15', '20'], correctOption: 1 }], timeLimit: 10, rewardPoints: 15 },
  { id: 'p2-sci-1', title: 'P2 Science: Plants', level: 'Primary 2', subject: 'Science', questions: [{ question: 'Which part of a plant is in the soil?', options: ['Leaves', 'Roots', 'Stem'], correctOption: 1 }, { question: 'What do plants need?', options: ['Sunlight', 'Milk', 'Bread'], correctOption: 0 }], timeLimit: 10, rewardPoints: 15 },
  // Primary 3
  { id: 'p3-eng-1', title: 'P3 English: Nouns', level: 'Primary 3', subject: 'English', questions: [{ question: 'Which is a proper noun?', options: ['boy', 'Lagos', 'city'], correctOption: 1 }, { question: 'A noun is a name of a:', options: ['Action', 'Person/Place/Thing', 'Color'], correctOption: 1 }], timeLimit: 15, rewardPoints: 20 },
  { id: 'p3-math-1', title: 'P3 Math: Multiplication', level: 'Primary 3', subject: 'Math', questions: [{ question: '3 x 3 = ?', options: ['6', '9', '12'], correctOption: 1 }, { question: 'What is 1/2 of 10?', options: ['2', '5', '10'], correctOption: 1 }], timeLimit: 15, rewardPoints: 20 },
  { id: 'p3-sci-1', title: 'P3 Science: Solar System', level: 'Primary 3', subject: 'Science', questions: [{ question: 'Which is the center of our solar system?', options: ['Earth', 'Moon', 'Sun'], correctOption: 2 }, { question: 'How many planets are there?', options: ['7', '8', '9'], correctOption: 1 }], timeLimit: 15, rewardPoints: 20 },
  // Primary 4
  { id: 'p4-eng-1', title: 'P4 English: Verbs', level: 'Primary 4', subject: 'English', questions: [{ question: 'Past tense of "Walk"?', options: ['Walking', 'Walked', 'Walks'], correctOption: 1 }, { question: 'Which is an adverb?', options: ['Quickly', 'Quick', 'Quicker'], correctOption: 0 }], timeLimit: 20, rewardPoints: 25 },
  { id: 'p4-math-1', title: 'P4 Math: Division', level: 'Primary 4', subject: 'Math', questions: [{ question: '20 / 4 = ?', options: ['4', '5', '6'], correctOption: 1 }, { question: 'Area of 4x3 rectangle?', options: ['7', '12', '14'], correctOption: 1 }], timeLimit: 20, rewardPoints: 25 },
  { id: 'p4-sci-1', title: 'P4 Science: Digestion', level: 'Primary 4', subject: 'Science', questions: [{ question: 'Where does digestion start?', options: ['Stomach', 'Mouth', 'Heart'], correctOption: 1 }, { question: 'What is solar energy from?', options: ['Wind', 'Sun', 'Water'], correctOption: 1 }], timeLimit: 20, rewardPoints: 25 },
  // Primary 5
  { id: 'p5-eng-1', title: 'P5 English: Structure', level: 'Primary 5', subject: 'English', questions: [{ question: 'Which part comes first in an essay?', options: ['Body', 'Conclusion', 'Introduction'], correctOption: 2 }, { question: 'Passive voice of "He ate it"?', options: ['It was eaten by him', 'He is eating it', 'It ate him'], correctOption: 0 }], timeLimit: 25, rewardPoints: 30 },
  { id: 'p5-math-1', title: 'P5 Math: Percentages', level: 'Primary 5', subject: 'Math', questions: [{ question: '50% is equal to:', options: ['1/4', '1/2', '1/5'], correctOption: 1 }, { question: 'A 90 degree angle is:', options: ['Acute', 'Right', 'Obtuse'], correctOption: 1 }], timeLimit: 25, rewardPoints: 30 },
  { id: 'p5-sci-1', title: 'P5 Science: Circulation', level: 'Primary 5', subject: 'Science', questions: [{ question: 'What pumps blood?', options: ['Lungs', 'Heart', 'Liver'], correctOption: 1 }, { question: 'A lever is a simple machine.', options: ['True', 'False'], correctOption: 0 }], timeLimit: 25, rewardPoints: 30 },
  // Primary 6
  { id: 'p6-eng-1', title: 'P6 English: Figures', level: 'Primary 6', subject: 'English', questions: [{ question: '"He is as brave as a lion" is a:', options: ['Metaphor', 'Simile', 'Personification'], correctOption: 1 }, { question: 'Which is a complex sentence?', options: ['I ran.', 'I ran because I was late.', 'I ran and fell.'], correctOption: 1 }], timeLimit: 30, rewardPoints: 40 },
  { id: 'p6-math-1', title: 'P6 Math: Algebra', level: 'Primary 6', subject: 'Math', questions: [{ question: 'If x + 2 = 5, x = ?', options: ['2', '3', '7'], correctOption: 1 }, { question: 'Volume of 2x2x2 cube?', options: ['4', '6', '8'], correctOption: 2 }], timeLimit: 30, rewardPoints: 40 },
  { id: 'p6-sci-1', title: 'P6 Science: Electricity', level: 'Primary 6', subject: 'Science', questions: [{ question: 'A material that allows electricity to pass:', options: ['Insulator', 'Conductor', 'Resistor'], correctOption: 1 }, { question: 'Pollution harms the earth.', options: ['True', 'False'], correctOption: 0 }], timeLimit: 30, rewardPoints: 40 },
  // ICT & Civic (New)
  { id: 'p1-ict-1', title: 'P1 ICT: Computer Parts', level: 'Primary 1', subject: 'ICT', questions: [{ question: 'Which part is for typing?', options: ['Mouse', 'Keyboard', 'Monitor'], correctOption: 1 }], timeLimit: 5, rewardPoints: 10 },
  { id: 'p6-civic-1', title: 'P6 Civic: Democracy', level: 'Primary 6', subject: 'Civic Education', questions: [{ question: 'How do we choose leaders in a democracy?', options: ['Fighting', 'Voting', 'Guessing'], correctOption: 1 }], timeLimit: 30, rewardPoints: 40 }
];
